### PR TITLE
Statutory redundancy pay updates

### PR DESCRIPTION
**Pull request by BenJanecke**
Northern Ireland rates need to be displayed for all outcomes

### To test
/calculate-your-redundancy-pay/y/2012-01-01/22/3/333.0
Northern Ireland rates should be displayed in brackets

### CODE REVIEW

**Comment by tadast** [comment]
Good after addressing comments :+1:

**Comment by chrisroos** [comment]
What's going on with this pull request? Is it out for fact check?

**Comment by BenJanecke** [comment]
@chrisroos Yes it's in factcheck

**Comment by floehopper** [comment]
@BenJanecke: I've just rebased this (`statutory-redundancy-pay-updates`) branch against `master`, because it had got really out-of-date. Also I wanted to include the conversion of the flows to classes in (#1729) before you start working on it again.

**Comment by tadast** [comment]
Liz says it's good to go live

**Pull request merged**
