### PR TITLE
Add missing phrase for maternity-paternity-calculator

### PR DESCRIPTION
**Pull request by chrisroos**
The text was supplied by @lutgendorff.

This replaces the "adoption_spp_claim_link" placeholder with a useful phrase.

## Example URLs

* https://www.gov.uk/maternity-paternity-calculator/y/adoption/no/2015-04-05/2015-04-06/yes/no/yes/2015-04-06/2015-01-01/2014-11-01/every_4_weeks/3000.0/usual_paydates/2015-01-01

## Before

1-before

## After

2-after

### CODE REVIEW

**Comment by chrisroos** [comment]
NOTE. Liz is going to check this wording with the department. If/when we get the OK, I'll update the regression test file checksums and artefacts.

**Comment by chrisroos** [comment]
I've rebased this branch on master and updated it now that maternity-paternity-calculator uses ERB templates.

I've force pushed this branch.

**Comment by tadast** [comment]
LGTM but it looks like you'll need to rebase again

**Comment by chrisroos** [comment]
I've rebased on top of master and force pushed now that the ERB templates are indented.

**Comment by tadast** [comment]
:shipit: :shipit: :shipit:

**Comment by chrisroos** [comment]
@tadast: Did you hear from Liz that this is OK to deploy?

**Comment by floehopper** [comment]
@tadast: Bump! Did you hear from Liz that the wording has been approved?

**Comment by tadast** [comment]
Initially I thought it's good to go but I must've confused it with something else. Liz hasn't heard back yet for this change unfortunately.

**Comment by chrisroos** [comment]
I've just rebased and force pushed this branch.

@lutgendorff: Have you heard anything back from the department about this change?

**Comment by chrisroos** [comment]
I've just rebased and force pushed this branch again.

**Comment by chrisroos** [comment]
I've rebased and force-pushed this branch. One thing to note is that the message for paternity adoption has recently been changed to mention "15 days" while our new adoption message mentions "28 days". I wonder whether these should be the same.

**Comment by chrisroos** [comment]
Liz has said that we should update the text to use "15 days" instead of "28 days" and then to get this deployed. I'm going to make the change and get this merged.

**Pull request merged**
