### PR TITLE
Amend earliest application date

### PR DESCRIPTION
**Pull request by ikennaokpala**
Supersedes #2683

[Trello card](https://trello.com/c/7jcImWLw/274-check-state-pension-age-correction-content-change-request)

[Trello card](https://trello.com/c/7jcImWLw/342-check-state-pension-age-correction-content-change-request)

* Show notification message to soon to be pensioners who are 4months from receiving State Pension (SP) age can apply to get their State Pension. (i.e. advising them that they don't have to wait till their Sate Pension age before doing this.). #Previously, the notification message was also rendered for those within  4months and 4 days, but the rules have now been changed to only show the notification from 4months.

## Factcheck
[Preview Link](https://smart-answers-pr-2690.herokuapp.com/state-pension-age/y/)
[GOVU.UK](https://gov.uk/state-pension-age/y/)

### Expected changes
*  Display notification to only soon to be pensioners who are 4months from receiving State Pension (SP) and not for those within 4months and 4 days.
    * With a state pension date of 2016-12-17 and birthday of  1951-12-17
    * Under 4 months and 4 days rule 2016-12-21 is boundary with today's date of 2016-08-17
    * Under 4 months and 4 days rule 2016-12-17 is boundary with today's date of 2016-08-17

## Factcheck (4 months and 4 days)
[Preview Link](https://smart-answers-pr-2690.herokuapp.com/state-pension-age/y/age/1951-12-21/male)
[GOVU.UK](https://gov.uk/state-pension-age/y/age/1951-12-21/male)

### Before 

screen shot 2016-08-17 at 16 00 01

### After

screen shot 2016-08-17 at 16 02 51

## Factcheck (4 months) No Changes
[Preview Link](https://smart-answers-pr-2690.herokuapp.com/state-pension-age/y/age/1951-12-17/male)
[GOVU.UK](https://gov.uk/state-pension-age/y/age/1951-12-17/male)

### Before 

screen shot 2016-08-17 at 16 05 22

### After

screen shot 2016-08-17 at 16 04 52

### CODE REVIEW

**Comment by ikennaokpala** [comment]
at the moment the tests are failing.. because of a content schema update.. which has been fixed in #2691

**Comment by leenagupte** [comment]
@ikennaokpala I would have expected the dates tested in the unit tests to have changed as a result of these changes. As only the test titles have changed, it would appear that they aren't testing anything useful.

I would expect to see tests where the date is 4 months and 4 days in the past and that initially (before the changes) passed, and now fail, And tests for 4 months that always pass (before and after the changes).

**Comment by ikennaokpala** [comment]
@leenagupte Amends have now been made..

**Comment by leenagupte** [comment]
@ikennaokpala Thanks for updating the tests. 👍

**Comment by selfthinker** [comment]
@ikennaokpala, I guess the links (to gov.uk and heroku) are now wrong because this was two days ago, right? Can you update them so they can be checked today during the release?

**Comment by ikennaokpala** [comment]
@selfthinker thanks for letting me know I have updated the links and dates accordingly..  I will also make myself available post deploy to support in anyway I can

**Pull request merged**
