### PR TITLE
[do not merge] Hungary marriage abroad

### PR DESCRIPTION
**Pull request by hannahwhittaker**
https://trello.com/c/UOkYySE4/3466-hungary-getting-married-abroad-change-local-requirement-for-cnis

### CODE REVIEW

**Comment by theseanything** [comment]
@hannahwhittaker is this still being worked on?

**Comment by hannahwhittaker** [comment]
Hi @theseanything it still kinda is - it's taking a while for the dept to get to the bottom of a legal change and what that means for the content.

I'm not sure how long it'll take, so I can delete this PR and start again when I know more, if that's preferable for you?

**Comment by theseanything** [comment]
No worries! If its still progressing - happy to leave it in draft. Or feel free to close and re-open when you think you're ready.

**Comment by theseanything** [comment]
@hannahwhittaker I'm going to close this for now - feel free to re-open when this is ready to go.

**Pull request closed without merging**
