### PR TITLE
Refactor SmartAnswer::Question::Base

### PR DESCRIPTION
**Pull request by floehopper**
These changes were prompted by me preparing the ground for a new version of #2311.

There are still lots of improvements that could be made to this code, but I think the changes in this PR should make the work I want to do on automatic detection of permitted next nodes easier.

### CODE REVIEW

**Comment by floehopper** [comment]
I've just rebased this against master, added one extra commit on the end, and force-pushed. It is again ready for review.

**Comment by floehopper** [comment]
I've just rebased this against master, added a couple of small commits, and force-pushed.

**Comment by floehopper** [comment]
@chrisroos: Can you review this when you have a chance? I'm basing another branch on the changes in this one, so it would be good to get feedback on it as soon as possible. The changes in this one are all pretty minor.

**Comment by erikse** [comment]
Other than the question about the change from `proc` to `lambda` and how it effects `next_node` blocks that don't pass `response`, looks good. 

Also, might be worth verifying that the existing documentation on `next_node` rules include any changes or restrictions introduced by this PR https://github.com/alphagov/smart-answers/blob/master/doc/next-node-rules.md

**Comment by floehopper** [comment]
Thanks. I'll have a look to see whether any of the docs need updating.

**Comment by floehopper** [comment]
I've just pushed some updates/improvements to the docs for `next_node` as suggested by @erikse.

**Comment by floehopper** [comment]
I'm going to rebase this against master in preparation for merging.

**Comment by erikse** [comment]
This looks good to me

**Pull request merged**
