### PR TITLE
Convert estimate-self-assessment-penalties to use ERB templates for questions

### PR DESCRIPTION
**Pull request by floehopper**

### CODE REVIEW

**Comment by chrisroos** [comment]
I think we might want to fix the ampersand escaping before merging this one.

**Comment by floehopper** [comment]
@chrisroos: I've addressed the [ampersand-escaping issue](https://github.com/alphagov/smart-answers/commit/6aae53ecdc8e872253eb1eb5e35f187d66dc02a3#commitcomment-14497029) using an interactive rebase in this [new commit](1383b67f8ac8f515f145c2edb32994e5b01bb186). I've also updated the regression test checksums and force-pushed.

**Comment by chrisroos** [comment]
Looks good to me.

**Comment by chrisroos** [comment]
I've rebased on master and force pushed in preparation for merging.

**Pull request merged**
