### PR TITLE
Bump Slimmer to 10.0.0 and update code

### PR DESCRIPTION
**Pull request by Davidslv**
Finding Things has been working on migrating related links, part of that
work was to replace the breadcrumbs on a number of different frontend
applications like:

- calendars
- calculators
- business-support-finder
- frontend
- licence-finder
- smart-answers

That work has already been done, this commit aims to clean up things we
have missed during the migration.

This includes

- upgrading Slimmer to 10.0.0
- deletion of govuk-component-helpers.scss
- rename [Slimmer::SharedTemplates to Slimmer::GovukComponents](https://github.com/alphagov/slimmer/pull/173)

Trello: https://trello.com/c/5Utjs9qw/300-related-links-cleanup

### CODE REVIEW

**Comment by Davidslv** [comment]
From [slimmer 9.5.0](https://github.com/alphagov/slimmer/blob/master/CHANGELOG.md#950) it seems that there is something going wrong with `test/integration/engine/report_a_problem_test.rb`

**Comment by tijmenb** [comment]
This looks okay, but I wonder if there's any way to put `stub_shared_component_locales` in a shared before block.

**Comment by Davidslv** [comment]
@tijmenb I've tried to include it on the `test_helper` by defining the class ("mokey patching" like ActiveSupport::TestCase and others) and adding the setup method, but that didn't work. I'm not sure  how we could achieve it with test/unit.

**Comment by tijmenb** [comment]
Ok fair enough. Merge after rebase.

**Comment by leenagupte** [comment]
@Davidslv @tijmenb I'm running all of the tests at the moment...

**Comment by leenagupte** [comment]
@Davidslv @tijmenb The regression tests are failing, see: https://ci.dev.publishing.service.gov.uk/job/govuk_smart_answers_regressions/6184/console

Can you run the regression tests for one smartanswer and see if you can replicate the error?
e.g.
`RUN_REGRESSION_TESTS=student-finance-calculator bundle exec ruby test/regression/smart_answers_regression_test.rb`

**Comment by tijmenb** [comment]
@Davidslv looks like you missed some `stub_shared_component_locales`'s.

**Comment by Davidslv** [comment]
@leenagupte I believe I fixed the regression test. Would you mind having another look please?

Thank you

**Comment by leenagupte** [comment]
@Davidslv LGTM 👍 

All of the regression tests are passing now. Thanks!

**Pull request merged**
