### PR TITLE
Add living wage to wage calculator

### PR DESCRIPTION
**Pull request by chrisroos**
__This supersedes PR #2042.__

I rebased the original changes on master and updated them now that we store questions in ERB templates (rather than i18n YAML files). I've opened a new PR (instead of force-pushing to the original) because I ended up rewriting some of the commits to separate out the generation of regression test artefacts from the actual changes to the flow. One downside of this is that the commits now appear to be authored by me rather than @erik-eide, but I've not actually changed anything about them other than splitting them up.

--- Original description below here ---

PT Story - https://www.pivotaltracker.com/story/show/106292374

## Rationale

This change updates the "Am I getting minimum wage?" calculator with an option for people to check if they will receive the living wage when it goes live 1 April 2016.

All the logic remains the same and follows the path as if you were calculating a current rate, with only a minor change in the age question, asking how old will you be on 1 April 2016, instead of how old are you.

Those over 25 on 1 April 2016, who receive 7.20 or more per hour, will see that they will be receiving the living wage, and those receiving less than 7.20 per hour will see a message that they should be receiving the living wage.

## Expected changes

* [Example URL](https://www.gov.uk/am-i-getting-minimum-wage/y)
  * The start page should show a third choice "If you'll get the national living wage (from 1 April 2016)?

screen shot 2015-10-30 at 3 40 12 pm

* [Example URL](https://www.gov.uk/am-i-getting-minimum-wage/y/current_payment_april_2016)
 * Show question 'Will you be in the first year of an apprenticeship on 1 April 2016?'

screen shot 2015-12-07 at 13 04 07

* [Example URL](https://www.gov.uk/am-i-getting-minimum-wage/y/current_payment_april_2016)
  * Should now ask "How old will you be on 1 April 2016?"

screen shot 2015-10-30 at 3 41 05 pm

* [Example URL](https://www.gov.uk/am-i-getting-minimum-wage/y/current_payment_april_2016/25/7/40.0/300.0/0.0/no)
  * Outcome should say "You will be getting the national living wage"

screen shot 2015-10-30 at 3 43 57 pm

* [Example URL](https://www.gov.uk/am-i-getting-minimum-wage/y/current_payment_april_2016/25/7/40.0/280.0/0.0/no)
  * Outcome should include "You are getting the National Minimum wage but your pay should be increased to at least the national living wage from 1 April 2016."

screen shot 2015-10-30 at 3 45 10 pm

* [Example URL](https://www.gov.uk/am-i-getting-minimum-wage/y/current_payment_april_2016/25/7/40.0/200.0/0.0/no)
  * Outcome should include callout "Your actual pay should increase to at least £7.20 per hour from 1 April 2016."

screen shot 2015-10-30 at 3 47 48 pm

* [Example URL](https://www.gov.uk/am-i-getting-minimum-wage/y/current_payment/not_an_apprentice/33/5/33.0/333.0/3.0/3.0/no)
 * Asac helpline should be in bold text, and on separate line

screen shot 2015-11-10 at 10 43 40 am

### CODE REVIEW

**Comment by chrisroos** [comment]
I've just rebased on master, resolved some minor conflicts, and force pushed.

**Comment by erik-eide** [comment]
Just rebased with master and forced pushed

**Comment by erik-eide** [comment]
Now approved for release, has one additional commit needing review

**Comment by erkede** [comment]
Have rebased with master again and forced pushed

**Comment by chrisroos** [comment]
It looks like you need to update the following files for minimum-wage-calculator-employers:

* minimum-wage-calculator-employers-questions-and-responses.yml
* minimum-wage-calculator-employers-responses-and-expected-results.yml
* minimum-wage-calculator-employers-files.yml
* minimum-wage-calculator-employers regression test artefacts

**Comment by chrisroos** [comment]
Aside from updating the minimum-wage-calculator-employers files, the changes themselves all look good to me.

**Comment by chrisroos** [comment]
To expand on my comments from yesterday. The regression test for minimum-wage-calculator-employer currently fails with the following:

```
SmartAnswersRegressionTest#test_: Smart Answer: minimum-wage-calculator-employers should ensure all nodes are being exercised.  [test/regression/smart_answers_regression_test.rb:96]:
Not all nodes are being exercised: [:does_not_apply_to_first_year_apprentices, :will_you_be_a_first_year_apprentice?].
Expected: true
  Actual: false
```

Having chatted to @erkede I now understand that the changes in this PR should only apply to am-i-getting-minimum-wage. I think that means that the `:will_you_be_a_first_year_apprentice?` question and `:does_not_apply_to_first_year_apprentices` outcome node should be defined in am-i-getting-minimum-wage.rb rather than in the shared minimum_wage.rb. Making this change fixes the failing test listed above.

**Comment by erkede** [comment]
I've just rebased this with master and forced pushed

**Pull request merged**
