### PR TITLE
Simplified expenses checker: Amendments to content and logic flow change

### PR DESCRIPTION
**Pull request by ikennaokpala**
Supersedes #2944 

[Trello card](https://trello.com/c/8Hgtl17t/280-8-updates-for-simplified-expenses-smart-answer)

## Motivation

Prior to this change request, business owners were unable properly claim the right amounts on simplified expenses from usage of capital equipments like cars, vans and motorbikes. 

The simplified expenses checker was limited with the options provided, loosely graded emissions levels and the wrongly used context of existing versus new business to estimate claims.

Here in this PR, logic changes have been introduced to cater for the aforementioned gaps.

## Factcheck
- [Preview link](https://smart-answers-pr-2982.herokuapp.com/simplified-expenses-checker/y)
- [GOV.UK](https://www.gov.uk/simplified-expenses-checker/y)

## Expected changes

 - Remove Question one (SEC)
 - Split car and van option in Question 1
 - Rename motorcycle to motorbike
 - Refactoring the calculate blocks
 - Split type of expense question into two
 - Split Yes option to new and use
 - Add simplified expenses to question 4
 - Change flow for question 6
 - Update on vehicle emission question
 - Content change to start page title.
 - Change to start page body content.
 - Add Extra details to start page
 - Update question 2 description
 - Update question 3 description
 - Update body and hint for question 7
 - Update question 8 description
 - Update you_can_use_result outcome
 - Fix typos in simplified expenses checker
 - Add content for CA and SE claims
 - Change “Capital Allowances” to all lower case.
 - Update outcome result 2
 - Update to clarify SE
 - Consolidated update for outcome 2

### Before

screen shot 2017-01-30 at 00 45 54

### After

screen shot 2017-03-04 at 11 23 12

### CODE REVIEW

**Comment by chao-xian** [comment]
@leenagupte @ikennaokpala 🎉

**Comment by ikennaokpala** [comment]
Rebased from 7e2b900096009fdea0f1e1a419e52efc2e3cad28 -- new to e1c2de79bc47267aa9d67e159143993f894da3cf -- old

**Comment by ikennaokpala** [comment]
Rebasing from 9882955 to

**Comment by ikennaokpala** [comment]
I appears linter has been updated and it complained about empty case statements and assignment of variables within case and if blocks. c2c98e1 fixes the aforementioned linter error

**Pull request merged**
