### PR TITLE
Marriage abroad: refactor calculator for two outomes

### PR DESCRIPTION
**Pull request by pmanrubia**
### Changes

* Simplify code in the calculator so code is more readable
* Move flow logic to identify 2-outcomes countries into the calculator
* Also consolidates content for Ireland.

Ireland is consolidated (flattened) in this PR, because this was the only country that originally had two outcomes, and it was leading to confusion in our codebase as all countries migrated to two outcomes were already migrated.

### User changes

The content of all outcomes remains the same, so no user changes are expected.

### CODE REVIEW

**Comment by theleebriggs** [comment]
@pmanrubia it looks good to me. I noticed that Italy has the folder structure (third_country/ etc) AND the two outcomes. Wasn't sure whether they should be taken out in this  PR?

**Comment by pmanrubia** [comment]
True @theleebriggs. There is some back & forth in Italy. It is worth mentioning it tomorrow in the SU. 
What about creating a separate PR for Italy?

**Comment by theleebriggs** [comment]
@pmanrubia Agreed, a separate PR for Italy sounds appropriate.

**Comment by pmanrubia** [comment]
Thank you for your review @theleebriggs

**Pull request merged**
