### PR TITLE
check-uk-visa updates for Taiwan and Venezuala

### PR DESCRIPTION
**Pull request by chrisroos**
__NOTE.__ This is based on the refactor-check-uk-visa branch (PR #2095). I'll have to recreate this PR once that change has been merged to master.

PT story: https://www.pivotaltracker.com/story/show/106095812

Update the advice for people who are:

* Travelling on Taiwanese or Venezualan documents
* Transiting through the UK
* Not passing through UK border control

## Fact check

* [Change for Taiwan](https://smart-answers-pr-2096.herokuapp.com/check-uk-visa/y/taiwan/transit/no)
* [Change for Venezuela](https://smart-answers-pr-2096.herokuapp.com/check-uk-visa/y/venezuela/transit/no)

### Taiwan 

* [URL](https://www.gov.uk/check-uk-visa/y/taiwan/transit/no)

#### Before

pr-2096-taiwan-before

#### After

pr-2096-taiwan-after

### Venezuela

* [URL](https://www.gov.uk/check-uk-visa/y/venezuela/transit/no)

#### Before

pr-2096-venezuela-before

#### After

pr-2096-venezuela-after

### CODE REVIEW

**Comment by floehopper** [comment]
Other than the mixture of apostrophe style, this looks good to me.

**Comment by chrisroos** [comment]
I've rebased this on the updated refactor-check-uk-visa branch (PR #2095) and have updated outcome_transit_taiwan to consistently use `'` apostrophes.

**Comment by chrisroos** [comment]
I've also force pushed to the Heroku app for fact checking.

**Comment by chrisroos** [comment]
The refactor-check-uk-visa changes (PR #2095) have now been merged to master. I'm going to close this and create a new PR based on master.

**Comment by chrisroos** [comment]
I've created PR #2100 which supersedes this pull request.

**Pull request closed without merging**
