### PR TITLE
Name the app that's deployed to Heroku

### PR DESCRIPTION
**Pull request by chrisroos**
Naming the app using the pull request number should ensure the names are
unique but also easily guessable/discoverable.

### CODE REVIEW

**Comment by floehopper** [comment]
LGTM :+1:

**Comment by chrisroos** [comment]
I've realised that I should update the documentation in factcheck.md as part of this commit.

**Comment by chrisroos** [comment]
I've made a couple of changes to this branch. I'd appreciate you taking another look when you have a moment, @floehopper.

**Comment by floehopper** [comment]
LGTM :+1:

**Comment by chrisroos** [comment]
I've rebased on master and force-pushed in preparation for merging to master.

**Comment by chrisroos** [comment]
The test failure was to do with the problem described and fixed in PR #2107. I'm going to merge this to master.

**Pull request merged**
