### PR TITLE
Correcting consular fees links for Kazakhstan and Kyrgyzstan

### PR DESCRIPTION
**Pull request by ikennaokpala**
[Trello card](https://trello.com/c/XXPir5E4/158-remove-special-case-for-kazakhstan-kyrgyzstan-when-linking-to-consular-fees-in-marriage-abroad)

Related to #2575 

* This PR removes the condition added previously to redirect Kyrgyzstan to
Kazakhstan consular fees link.

## Factcheck Kazakhstan

[Preview Link](https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kazakhstan/ceremony_country/partner_local/opposite_sex)
[GOV.UK](https://gov.uk/marriage-abroad/y/kazakhstan/ceremony_country/partner_local/opposite_sex)

### Before

screen shot 2016-06-14 at 11 39 30

### After

screen shot 2016-06-14 at 11 38 58

## Factcheck Kyrgyzstan

[Preview Link](https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kyrgyzstan/ceremony_country/partner_local/opposite_sex)
[GOV.UK](https://gov.uk/marriage-abroad/y/kyrgyzstan/ceremony_country/partner_local/opposite_sex)

### Before
screen shot 2016-06-14 at 11 41 27

### After
screen shot 2016-06-14 at 11 40 55

#### Affected pages

https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kazakhstan/ceremony_country/partner_british/opposite_sex
https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kazakhstan/ceremony_country/partner_local/opposite_sex
https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kazakhstan/ceremony_country/partner_other/opposite_sex
https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kazakhstan/uk/partner_british/opposite_sex
https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kazakhstan/uk/partner_local/opposite_sex
https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kazakhstan/uk/partner_other/opposite_sex
https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kyrgyzstan/ceremony_country/partner_british/opposite_sex
https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kyrgyzstan/ceremony_country/partner_local/opposite_sex
https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kyrgyzstan/ceremony_country/partner_other/opposite_sex
https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kyrgyzstan/uk/partner_british/opposite_sex
https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kyrgyzstan/uk/partner_local/opposite_sex
https://smart-answers-pr-2580.herokuapp.com/marriage-abroad/y/kyrgyzstan/uk/partner_other/opposite_sex

### CODE REVIEW

**Comment by chrisroos** [comment]
I realise this is currently blocked (awaiting feedback from the department) but I've reviewed it nonetheless.

It looks good to me. Good work, @ikennaokpala!

**Comment by chrisroos** [comment]
I've added the "Don't merge" label to prevent us accidentally merging given that this is currently awaiting feedback from the department.

**Comment by chrisroos** [comment]
I've replaced the "Don't merge" label with "Waiting on factcheck" as I think that more correctly describes the state of this PR, and it should continue to ensure it's not merged in the meantime.

**Comment by ikennaokpala** [comment]
@chrisroos thannks for reviewing @sistephens.. over to you mate

**Comment by sistephens** [comment]
LGTM 👍

**Comment by ikennaokpala** [comment]
Revert back if neccesary c9b4c42ab2d1fea9d586d266c925b4b27bd3c8ba

**Comment by ikennaokpala** [comment]
@chrisroos thanks for reviewing this PR and creating  #2641 to further clarify things.. I have cheery picked and included it here

**Pull request merged**
