### PR TITLE
Updated to include the JSS.

### PR DESCRIPTION
**Pull request by alishaoniGDS**
:warning: This application is Continuously Deployed: :warning:

- Merged changes are automatically deployed to staging and production.

- Make sure you follow [the guidance for deployments](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) **before** you merge.

- Check your branch is being deployed in the [Release app](https://release.publishing.service.gov.uk/applications/smartanswers), after merging.

- Changes to start pages are **not** continuously deployed, and are [deployed using a different process](https://github.com/alphagov/smart-answers/blob/master/doc/smart-answer-flow-development/publishing.md).

### CODE REVIEW

**Comment by alishaoniGDS** [comment]
Update added to include reference to the new Job Support Scheme

**Comment by alishaoniGDS** [comment]
https://trello.com/c/HJK8NuFD/3195-1-november-cjrs-changes-redundancy-dismissal

**Comment by theseanything** [comment]
@alishaoniGDS Do you what the status is for this PR?

**Comment by theseanything** [comment]
This scheme has been delayed possibly until March 2021. Closing for now.

**Pull request closed without merging**
