### PR TITLE
Convert calculate-your-child-maintenance to use ERB templates

### PR DESCRIPTION
**Pull request by chrisroos**

### CODE REVIEW

**Comment by floehopper** [comment]
@chrisroos: The build failure looks legitimate:

```
  1) Failure:
CalculateChildMaintentanceTest#test_: answer paying answer 1 child answer yes answer 104 to 103 should take you to the nil rate outcome.  [/home/jenkins/workspace/govuk_smartanswers_branches/test/integration/smart_answer_flows/calculate_child_maintenance_test.rb:63]:
State variable nil_rate_reason is not a PhraseList


  2) Failure:
CalculateChildMaintentanceTest#test_: answer paying answer 2 children, receives benefits, child stays more than once a week should take you to flat rate result.  [/home/jenkins/workspace/govuk_smartanswers_branches/test/integration/smart_answer_flows/calculate_child_maintenance_test.rb:124]:
State variable nil_rate_reason is not a PhraseList
```

**Comment by chrisroos** [comment]
I hadn't even noticed that the build had failed! Thanks, @floehopper.

**Comment by chrisroos** [comment]
OK, the build should be fixed now. Can someone take a look at this, please?

**Comment by chrisroos** [comment]
The most recent build failure was caused by our intermittent Poltergeist issue #1624. I'm rebuilding it now.

**Comment by floehopper** [comment]
Other than my small suggestion above, this LGTM :+1:

**Comment by chrisroos** [comment]
@floehopper: I've updated the commit note as you suggested. See b30cdb4635dc72710441087a26b6c629dd43711f.

Manually merged in bb77b0e1848fb76588428b5a9b20d5f4885ce353.

**Pull request closed without merging**
