### PR TITLE
Marriage abroad FC feedback. Thailand

### PR DESCRIPTION
**Pull request by tadast**
Clarify affirmation/affidavit requirements in Thailand

Either of affirmation/affidavit document is accepted, so avoid confusion and make sure both are mentioned in the relevant sentences.

This is addressing FC feedback

### CODE REVIEW

**Comment by tadast** [comment]
To my knowledge China is the only other country that accepts both, but it's handled by China-specific phrases.

**Comment by chrisroos** [comment]
Presumably the text is different enough that we need both special cases (for China and Taiwan)?

**Comment by tadast** [comment]
Yes, the Chinese outcome has custom links to affirmation and affidavit documents https://www.gov.uk/marriage-abroad/y/china/ceremony_country/partner_british/opposite_sex

**Comment by chrisroos** [comment]
Fair enough :-)

**Pull request merged**
