### PR TITLE
Add a link to the 2015 to 2016 CCG2 form 

### PR DESCRIPTION
**Pull request by erik-eide**
Brings in pull request #2033 from remote repository for merging.

(Still waiting on link to go live: http://media.slc.co.uk/sfe/1516/ft/sfe_ccg2_1516_d.pdf)

@keithiopia @lutgendorff

### CODE REVIEW

**Comment by lutgendorff** [comment]
Looks like there was a slight typo. This is the right link, can @er-ke-de update this: http://media.slc.co.uk/sfe/1516/ft/sfe_ccg2_form_1516_d.pdf

**Comment by keithiopia** [comment]
Sorry about that - they gave me the wrong link. Glad we made them wait till it was meant to go live!

**Comment by er-ke-de** [comment]
Ok great, I noticed the file is 295KB instead of 289KB, will update also

**Comment by keithiopia** [comment]
Glad you're on the ball, Erik! I guess they didn't know the size.

**Pull request merged**
