### PR TITLE
Update apply tier 4 visa: service outage

### PR DESCRIPTION
**Pull request by lutgendorff**
Added service outage message for July 25 to July 26

### CODE REVIEW

**Comment by tadast** [comment]
Merged in 3672290c5a57900a01a2bf7ffc3929bff6a50014

**Comment by chrisroos** [comment]
It doesn't look like you updated the regression test artefacts when you merged, unless I'm missing something?

**Comment by tadast** [comment]
The new message is on the start page

**Comment by chrisroos** [comment]
Aha. My bad. Ignore me.

**Pull request closed without merging**
