### PR TITLE
Correcting consular fees links for Kazakhstan and Kyrgyzstan

### PR DESCRIPTION
**Pull request by ikennaokpala**
[Trello card](https://trello.com/c/XXPir5E4/158-remove-special-case-for-kazakhstan-kyrgyzstan-when-linking-to-consular-fees-in-marriage-abroad)

* This PR removes the condition added previously to redirect Kyrgyzstan to
Kazakhstan consular fees link.
* Absolute links (https://gov.uk/*)have been added to help reduce any confusion, this will be reverted back to relative links i.e these commits (629f2a46f and b0b8fca) will be removed 

#### Affected pages

https://smart-answers-pr-2575.herokuapp.com/marriage-abroad/y/kazakhstan/ceremony_country/partner_british/opposite_sex
https://smart-answers-pr-2575.herokuapp.com/marriage-abroad/y/kazakhstan/ceremony_country/partner_local/opposite_sex
https://smart-answers-pr-2575.herokuapp.com/marriage-abroad/y/kazakhstan/ceremony_country/partner_other/opposite_sex
https://smart-answers-pr-2575.herokuapp.com/marriage-abroad/y/kazakhstan/uk/partner_british/opposite_sex
https://smart-answers-pr-2575.herokuapp.com/marriage-abroad/y/kazakhstan/uk/partner_local/opposite_sex
https://smart-answers-pr-2575.herokuapp.com/marriage-abroad/y/kazakhstan/uk/partner_other/opposite_sex
https://smart-answers-pr-2575.herokuapp.com/marriage-abroad/y/kyrgyzstan/ceremony_country/partner_british/opposite_sex
https://smart-answers-pr-2575.herokuapp.com/marriage-abroad/y/kyrgyzstan/ceremony_country/partner_local/opposite_sex
https://smart-answers-pr-2575.herokuapp.com/marriage-abroad/y/kyrgyzstan/ceremony_country/partner_other/opposite_sex
https://smart-answers-pr-2575.herokuapp.com/marriage-abroad/y/kyrgyzstan/uk/partner_british/opposite_sex
https://smart-answers-pr-2575.herokuapp.com/marriage-abroad/y/kyrgyzstan/uk/partner_local/opposite_sex
https://smart-answers-pr-2575.herokuapp.com/marriage-abroad/y/kyrgyzstan/uk/partner_other/opposite_sex

### CODE REVIEW

**Comment by chrisroos** [comment]
I'm intrigued by the addition of the absolute link to gov.uk, @ikennaokpala. Is it so that the link works on Heroku?

**Comment by ikennaokpala** [comment]
@chrisroos.. in this case yes.. it is an intentional addition to help the user

**Comment by floehopper** [comment]
@ikennaokpala:

* Can you confirm that the link does *not* work on Heroku when the URL is relative?
* Also are you planning to change it back to a relative URL before merging?

I've created a [Trello card][1] to investigate whether there's a way we can make links with relative URLs work on Heroku. Ideally I'd want to keep all gov.uk URLs relative and if this is not possible, then I'd want to make all of them absolute.

[1]: https://trello.com/c/1yR3BM4t

**Comment by chrisroos** [comment]
Note that this has been superseded by PR #2580.

**Pull request closed without merging**
