### PR TITLE
Make smart answers log to stdout

### PR DESCRIPTION
**Pull request by djsd123**
Logging on the paas only works if the app logs to stdout.

### CODE REVIEW

**Comment by alexmuller** [comment]
Looks fine to me but it'd be good if the content tools team had a look too :+1:

(needs a rebase though)

**Comment by pmanrubia** [comment]
Hi, sorry for the delay in reviewing it. We will have a look at it today.

**Comment by pmanrubia** [comment]
Hi @djsd123, Thank you for your work on this

1. I have created a [Trello card](https://github.com/alphagov/smart-answers/pull/2678) in our Trello board to track this work.
2. Could you please rebase with master and remove 2bbe57f99a74db9d5283970cb30ab42ddb0f8230
3. Would we need to take any action to continue having logs in Kibana?
4.  We are planning a deploy for tomorrow. If this get merged tomorrow in the morning we can include it in the next release

LGTM

**Comment by pmanrubia** [comment]
sorry @djsd123 we can't merge it yet. We are having too much logging in our tests. I will get back to you once this is sorted out.

**Comment by djsd123** [comment]
@pmanrubia 
Apologies for the late reply. Thanks for the review. I'll rebase and you can merge whenever.

**Comment by alexmuller** [comment]
I've just come across ed9346f2a87ab3fe27231a7ebb6f16bd192b44c7 which is relevant to this pull request.

**Comment by alexmuller** [comment]
I've fixed the logging in test issue, it would be great if you could have a look!

**Comment by pmanrubia** [comment]
Rebasing with master and force-pushed in preparation for merging.

**Comment by pmanrubia** [comment]
LGTM 👍

**Pull request merged**
