### PR TITLE
Convert additional-commodity-code to use ERB templates for questions

### PR DESCRIPTION
**Pull request by floehopper**
This is based on #2103. I created a single commit containing all the changes in that PR (using `merge --squash use-erb-templates-for-questions`) before I started making changes. The hope is that this extra commit will disappear once the other branch is merged into master and this branch is rebased against that master.

Only the last two commits are new ones in this branch:

* "Use ERB templates for Qs in additional-commodity-code"
* "Update regression test artefacts & checksums"

### CODE REVIEW

**Comment by floehopper** [comment]
I've just rebased this against master and force-pushed which has meant that the "merge" commit mentioned in the description has now disappeared as we hoped.

**Comment by chrisroos** [comment]
I'm re-running the tests for this branch on Jenkins. I can't see what the failure was because [build 3381](https://ci.dev.publishing.service.gov.uk/job/govuk_smartanswers_branches/3381/) is now returning 404.

**Comment by chrisroos** [comment]
The test failure appears to be caused by outdated checksum data for additional-commodity-code.

**Comment by floehopper** [comment]
@chrisroos: Thanks. I've just updated the checksums and force-pushed.

**Comment by chrisroos** [comment]
Looks good to me.

**Comment by floehopper** [comment]
I've just rebased this against master and force-pushed in preparation for merging.

**Pull request merged**
