### PR TITLE
[In Fact Check - DO NOT MERGE] Updates to calculate-statutory-sick-pay

### PR DESCRIPTION
**Pull request by BenJanecke**
I believe this is the related [Pivotal Tracker story](https://www.pivotaltracker.com/story/show/93691714).

We now ask for previous periods of sickness earlier so we can use the correct dates when asking for and calculating AWE

Test url for deploy 

http://smartanswers.dev.gov.uk/calculate-statutory-sick-pay/y/none/yes/no/2014-08-10/2014-08-20/yes/2014-05-01/2014-08-20/eight_weeks_more/monthly/2013-04-01/2013-02-03/4000.0/1,2,3,4,5

### CODE REVIEW

**Comment by tadast** [comment]
I think it's worth spending some time and renaming the questions. It doesn't make much sense to have Q11 after Q5. Also, we need to update the logic document, because it was incorrect.

**Comment by chrisroos** [comment]
I wonder whether it's worth closing pull requests when they're in fact check. Is there any benefit to keeping them open?

**Comment by floehopper** [comment]
@BenJanecke: Please talk to me before working on this branch (`statutory-sick-pay-updates`). I'm currently trying to rebase it against `master` and there are a bunch of conflicts.

**Comment by floehopper** [comment]
I've just rebased this branch against `master` and force-pushed it.

**Comment by floehopper** [comment]
I've now rebased this again against `master` to pick up the changes in #1726.

**Comment by floehopper** [comment]
It turns out that I made a mistake in resolving some of the conflicts when I rebased this branch. @BenJanecke has reinstated the version of the branch which was deployed to Heroku for fact-checking. I'm now going to re-attempt to rebase this branch.

**Comment by floehopper** [comment]
I've just tried to run the integration test for the `calculate-statutory-sick-pay` flow in this (un-rebased) branch and I see the following failing tests:

    $ ruby test/integration/smart_answer_flows/calculate_statutory_sick_pay_test.rb
    Run options: --seed 7392

    # Running:

    .................F.FF..

    Finished in 0.973414s, 23.6282 runs/s, 289.7020 assertions/s.

      1) Failure:
    CalculateStatutorySickPayTest#test_: no SSP payable as already had maximum should take you to result A8 as already claimed > 28 weeks (max amount).  [test/integration/smart_answer_flows/calculate_statutory_sick_pay_test.rb:317]:
    Expected: :maximum_entitlement_reached
      Actual: :entitled_to_sick_pay


      2) Failure:
    CalculateStatutorySickPayTest#test_: tabular output for final SSP calculation should have consistent rates for all weekly rates that are produced.  [test/integration/smart_answer_flows/calculate_statutory_sick_pay_test.rb:376]:
    --- expected
    +++ actual
    @@ -1,4 +1,4 @@
    -"12 January 2013|£85.85
    +"12 January 2013|£28.62
     19 January 2013|£85.85
     26 January 2013|£85.85
      2 February 2013|£85.85



      3) Failure:
    CalculateStatutorySickPayTest#test_: tabular output for final SSP calculation should have the adjusted rates in place for the week crossing through 6th April.  [test/integration/smart_answer_flows/calculate_statutory_sick_pay_test.rb:339]:
    --- expected
    +++ actual
    @@ -1,4 +1,4 @@
    -"12 January 2013|£85.85
    +"12 January 2013|£0.00
     19 January 2013|£85.85
     26 January 2013|£85.85
      2 February 2013|£85.85

Having spoken to @tadast, we've agreed that the first thing is to sort out these failing tests i.e. either fix the behaviour or fix the tests as appropriate. Once this is done, we can think about rebasing against `master`.

**Comment by tadast** [comment]
Closing in favour of #1777

**Pull request closed without merging**
