### PR TITLE
[WIP] National minimum wage over 25 above

### PR DESCRIPTION
**Pull request by pmanrubia**
paired with @erikse 

Trello ticket: https://trello.com/c/kZ0I4a4G/58-national-minimum-wage-april-2016-update

## Fact check

https://smart-answers-pr-2390.herokuapp.com/national-minimum-wage

### CODE REVIEW

**Comment by floehopper** [comment]
What purpose is this PR serving? I wonder whether it's worth closing it for now.

**Comment by pmanrubia** [comment]
Thanks for the follow-up @floehopper. I am closing this PR, as a new one need to be open for the National Minimum Wage Flow.

**Comment by floehopper** [comment]
@pmanrubia: It looks like you forgot to close this PR (see your comment above).

**Comment by floehopper** [comment]
@pmanrubia: I hope you don't mind, but I'm going to close this PR. I think it helps to keep the number of open PRs as small as possible. Please re-open it if you disagree.

**Comment by pmanrubia** [comment]
:+1:

**Pull request closed without merging**
