### PR TITLE
Removal of factual error in Check UK Visa

### PR DESCRIPTION
**Pull request by ikennaokpala**
Trello Story: https://trello.com/c/SQyWbeEv/87-asap-check-if-you-need-a-uk-visa-content-change

## Expected changes

*URL on [GOV.UK](https://www.gov.uk/check-uk-visa/y/afghanistan/study/six_months_or_less)

### Before

screen shot 2016-04-07 at 14 12 15

### After

screen shot 2016-04-07 at 17 16 01

### CODE REVIEW

**Comment by ikennaokpala** [comment]
This supersedes #2430

**Comment by ikennaokpala** [comment]
@Lilboyce has approved the factcheck.. ready for code review @leenagupte

**Comment by pmanrubia** [comment]
I would apply the following changes to the PR:
- Remove the author from the title. You might add a link to the superseded PR in the description.
- `Content changes` feels a bit generic. Can you think of a different title that includes the flow name: `check-uk-visa`?
- The factcheck link appears twice in the description

**Comment by pmanrubia** [comment]
Before and after images are the same. You might have picked up the same one twice?

**Comment by pmanrubia** [comment]
Would you ind updating the commit title? `content change` is a bit generic to me. The committer won't be lost if you only rename the title.

**Comment by ikennaokpala** [comment]
@pmanrubia Thanks for reviewing this.. I have made changes as per your recommendations.

**Comment by pmanrubia** [comment]
Thank you @ikennaokpala. Great job :+1:

**Pull request merged**
