### PR TITLE
Restore indexable_content behaviour for outcome nodes

### PR DESCRIPTION
**Pull request by floehopper**
### Description

During the transition from YAML to ERB templates this behaviour got broken and then removed in order to avoid errors. See this [Trello card][1] for details.

Now that we have `MethodMissingHelper` we can avoid errors when outcome templates include ERB interpolation.

### Notes

* I've made a small change to the `OutcomePresenter` constructor to make it possible to specify extra helper modules c.f. `QuestionPresenter`.
* I've inlined `NODE_PRESENTER_METHODS`, because it was only being used in one place.
* I've added a new outcome template fixture in order to test ERB interpolation.

### External changes

Indexable content is used rather circuitously in the `panopticon:register` rake task which I believe is still invoked during deployment. I don't think it's used in the newer & related `publishing_api:publish` rake task.

I assume the indexable content eventually makes its way to the search app (rummager?). I suspect it'll be hard to test that this change has taken effect, but you could try using the GOV.UK search box to search for an unusual word in the content of an outcome.

### Deployment

We should probably notify Richard Boulton and Tara Stockford when this is deployed (see comments on Trello card).

[1]: https://trello.com/c/nZJqFYLE

### CODE REVIEW

**Comment by chrisroos** [comment]
The changes look good as far as I can tell, although I do have a couple of questions:

1. Is there a reason you haven't added a unit test for the change in behaviour of `OutcomePresenter#initialize`?

2. Have you tried running `rake panopticon:register` (or a subset of the task that exercises these changes) to ensure we won't have any problems on deployment?

**Comment by floehopper** [comment]
> 1. Is there a reason you haven't added a unit test for the change in behaviour of OutcomePresenter#initialize?

* I couldn't immediately see a nice way to unit test it
* The same behaviour in `QuestionPresenter#initialize` is not unit tested
* The behaviour is indirectly tested in `FlowRegistrationPresenterTest`

I'll have a look and see if I can come up with a decent way to test it now.

**Comment by floehopper** [comment]
> Have you tried running rake panopticon:register (or a subset of the task that exercises these changes) to ensure we won't have any problems on deployment?

No. Since all I've done is changed the implementation of the `indexable_content` method to return more data in the same format, I'm pretty confident this won't break anything. Also I'm not sure how I'd go about running the rake task without hitting the real panopticon. I'll see whether I can come up with a way to do this.

**Comment by floehopper** [comment]
> Is there a reason you haven't added a unit test for the change in behaviour of OutcomePresenter#initialize?

I have now addressed this in a fixup commit: 04725eff2641f1b1b736c46339803208b4361be7

**Comment by floehopper** [comment]
> Have you tried running rake panopticon:register (or a subset of the task that exercises these changes) to ensure we won't have any problems on deployment?

@chrisroos: Thanks for prompting me to do this - it turns out that there was a problem!

I ran the `panopticon:register` rake task in development against a local version of panopticon and there was an exception when generating indexable content for one of the marriage-abroad outcomes. I've fixed this problem in a [new commit][1] and I was able to run the rake task successfully:

```
$ rake panopticon:register
Registering with panopticon...
Looking up flows, with options: {:show_drafts=>true}
Registering flow: additional-commodity-code => Look up Meursing code
Registering flow: am-i-getting-minimum-wage => National Minimum Wage calculator for workers
Registering flow: benefit-cap-calculator => Benefit cap calculator
Registering flow: calculate-agricultural-holiday-entitlement => Calculate your agricultural worker holiday entitlement
Registering flow: calculate-employee-redundancy-pay => Calculate your employee's statutory redundancy pay
Registering flow: calculate-married-couples-allowance => Calculate your Married Couple's Allowance
Registering flow: calculate-statutory-sick-pay => Calculate your employee's statutory sick pay
Registering flow: calculate-your-child-maintenance => Child maintenance calculator
Registering flow: calculate-your-holiday-entitlement => Calculate holiday entitlement
Registering flow: calculate-your-redundancy-pay => Calculate your statutory redundancy pay
Registering flow: check-uk-visa => Check if you need a UK visa
Registering flow: childcare-costs-for-tax-credits => Tax credits: working out your childcare costs
Registering flow: energy-grants-calculator => Find energy grants and ways to improve your energy efficiency
Registering flow: estimate-self-assessment-penalties => Estimate your penalty for late Self Assessment tax returns and payments
Registering flow: help-if-you-are-arrested-abroad => Help if you're arrested abroad
Registering flow: inherits-someone-dies-without-will => Intestacy - who inherits if someone dies without a will?
Registering flow: landlord-immigration-check => Check if someone can rent your residential property
Registering flow: legalisation-document-checker => Check if documents can be legalised
Registering flow: marriage-abroad => Getting married abroad
Registering flow: maternity-paternity-calculator => Maternity and paternity calculator for employers
Registering flow: minimum-wage-calculator-employers => National Minimum Wage calculator for employers
Registering flow: overseas-passports => Overseas British passport applications
Registering flow: part-year-profit-tax-credits => Calculate your part-year profits to finalise your tax credits
Registering flow: pay-leave-for-parents => Calculate your leave and pay when you have a child
Registering flow: pip-checker => Check how Personal Independence Payment (PIP) affects you
Registering flow: plan-adoption-leave => Plan your adoption leave
Registering flow: register-a-birth => Register a birth abroad
Registering flow: register-a-death => Register a death
Registering flow: report-a-lost-or-stolen-passport => Cancel a lost or stolen passport
Registering flow: simplified-expenses-checker => Check if simplified expenses works for your business
Registering flow: state-pension-age => Check your State Pension age
Registering flow: state-pension-through-partner => Your partner’s National Insurance record and your State Pension
Registering flow: state-pension-topup => State Pension top up calculator
Registering flow: student-finance-calculator => Student finance calculator
Registering flow: student-finance-forms => Student finance forms
Registering flow: towing-rules => Towing: licence and age requirements
Registering flow: uk-benefits-abroad => UK benefits if you're going or living abroad
Registering flow: vat-payment-deadlines => VAT payment deadline calculator
```

[1]: 7edbaea2d2cb84fd8895d4cff461779f02261364

**Comment by floehopper** [comment]
@chrisroos: Thanks for reviewing this. I'd be grateful if you could have a look at my fixes and see if you're happy with them. I'm particularly interested to see what you think about the 2nd one.

**Comment by floehopper** [comment]
@chrisroos: Bump! :smile:

**Comment by chrisroos** [comment]
I haven't forgotten this, @floehopper. I'll look at it again soon.

**Comment by chrisroos** [comment]
Sorry it's taken so long for me to look at this again, @floehopper!

I see that the only template that was raising an exception was outcome_opposite_sex_in_other_countries. I have a local branch where I've split that outcome into multiple outcomes which means that the `raise` statement has been removed. _If_ that branch gets merged, do you still think it makes sense to rescue the `ActionView::Template::Error` exceptions? I guess I'm wondering whether we might be masking a real problem, although presumably we'd find out about that in some other way...

**Comment by floehopper** [comment]
@chrisroos:

Thanks for re-visiting this PR.

> I see that the only template that was raising an exception was outcome_opposite_sex_in_other_countries. I have a local branch where I've split that outcome into multiple outcomes which means that the raise statement has been removed. If that branch gets merged, do you still think it makes sense to rescue the `ActionView::Template::Error` exceptions? I guess I'm wondering whether we might be masking a real problem, although presumably we'd find out about that in some other way...

I agree that rescuing `ActionView::Template::Error` exceptions is not ideal. However, this rescuing of exceptions only happens in the rendering of templates triggered by a call to `indexable_content`. This rescuing of exceptions does not happen for a normal user request and so any exception raised inside a template would not be rescued and would either cause a test to fail or be recorded in Errbit in production.

Having said that I was a bit surprised to see that raising of an exception in the `outcome_os_other_countries` template. Do you know what would happen in your local branch if `calculator.ceremony_country` was `nil` or strictly speaking if it was an instance of `MethodMissingObject` (as it would be within a call to `indexable_content`)?

Since it doesn't look as if you've merged that branch yet, I think I'm inclined to merge this as it stands. I hope that's OK.

**Comment by floehopper** [comment]
@chrisroos: I've added a new "integration" test to call `FlowRegistrationPresenter#indexable_content` for all the flows in the app in this squash commit: 9f0b82b37d07743b552cef7bc2ffaa2a18235c26.

**Comment by floehopper** [comment]
I'm going to do an interactive rebase to incorporate the fixup & squash commits, then rebase against master and force push in preparation for merging.

**Comment by floehopper** [comment]
Superseded by #2454. Closing.

**Pull request closed without merging**
