### PR TITLE
Content changes to Energy Grants Calculator partials

### PR DESCRIPTION
**Pull request by ikennaokpala**
[Trello card](https://trello.com/c/3nvhp54o/291-change-copy-of-heating-partials-and-move-heating-section-into-partial-template-energy-grants-calculator)
## Description

Content changes to Energy Grants Calculator partials and move heating section into partial template.
## Factcheck

[Main Preview Link](https://smart-answers-pr-2703.herokuapp.com/energy-grants-calculator/y/all_help/benefits,permission/1950-01-01/child_tax_credit,esa,income_support,jsa,pension_credit,working_tax_credit/child_under_16,child_under_5,disabled,disabled_child,pensioner_premium,work_support_esa/1940s-1984/flat/ground_floor/mains_gas,electric_heating,modern_double_glazing,loft_attic_conversion,loft_insulation,solid_wall_insulation,cavity_wall_insulation,modern_boiler,draught_proofing)

[GOV.UK](https://gov.uk/energy-grants-calculator/y/all_help/benefits,permission/1950-01-01/child_tax_credit,esa,income_support,jsa,pension_credit,working_tax_credit/child_under_16,child_under_5,disabled,disabled_child,pensioner_premium,work_support_esa/1940s-1984/flat/ground_floor/mains_gas,electric_heating,modern_double_glazing,loft_attic_conversion,loft_insulation,solid_wall_insulation,cavity_wall_insulation,modern_boiler,draught_proofing)
### Expected changes
- Content changes to partails concerning heating.
### Before

screen shot 2016-08-23 at 17 07 47

screen shot 2016-08-23 at 17 27 11
### After

screen shot 2016-08-23 at 17 13 02

screen shot 2016-08-23 at 17 26 43
### Affected outcome

https://gist.github.com/ikennaokpala/635087c12fac1c2a7b68c96f14dba43d

### CODE REVIEW

**Comment by leenagupte** [comment]
@ikennaokpala I thought you were going to move the heating section into a partial?

**Comment by ikennaokpala** [comment]
@leenagupte thanks for hint.. will group the partials accordingly

**Comment by leenagupte** [comment]
@ikennaokpala You might want to re-write part of the last commit message:

> These have been **refused** in the same outcomes like before, only this time **throng** a single partial.

**Comment by ikennaokpala** [comment]
@leenagupte thanks 👍

**Comment by robinjam** [comment]
LGTM, but Jenkins appears to be dead

**Comment by ikennaokpala** [comment]
Closing this PR as BEIS plan to replace this smart answer with a new tool..

**Pull request closed without merging**
