### PR TITLE
Apply working pattern to linked period of sickness in calculate-statutory-sick-pay (without change in order of questions)

### PR DESCRIPTION
**Pull request by floehopper**
Supersedes #2031.

## Summary

Earlier this year the calculator was extended to take into account a previous linked period of sickness. However, this new functionality had a bug in it which was raised by HMRC in this [ZenDesk ticket](http://govuk.zendesk.com/tickets/1128193).

The problem was that the calculator was considering all calendar days in the linked period of sickness to be [Qualifying Days](https://www.gov.uk/guidance/statutory-sick-pay-manually-calculate-your-employees-payments#qualifying-days-qds) when in fact it should have only been considering the days the employee usually worked i.e. the same as for the current period of sickness.

The effect of this was to (in some circumstances) incorrectly credit the employee with more [Waiting Days](https://www.gov.uk/guidance/statutory-sick-pay-manually-calculate-your-employees-payments#waiting-days-wds) than they should've had. In these circumstances the calculator output might've said that the employee should've started receiving sick pay sooner than they should've done.

This pull request fixes that bug. It also fixes a couple of related minor issues and one unrelated minor issue that were requested during the fact check process. See below for details.

Note that the actual changes are not that big, but unfortunately there are a lot of changes to the regression test artefacts. I've attempted to break these changes down as much as possible into smaller commits so it's easier to see what's going on.

Note also that both the current and linked periods of sickness are referred to as [Periods of Incapacity for Work (PIW)](https://www.gov.uk/guidance/statutory-sick-pay-manually-calculate-your-employees-payments#period-of-incapacity-for-work-piw) in the policy documentation. I've used that terminology below.

### Linked PIW must be separate from the current PIW

New validation error message: **You need to enter a date at least 1 day before the start of the current period of sickness or it isn't a separate linked period of sickness**

* Before: https://www.gov.uk/calculate-statutory-sick-pay/y/ordinary_statutory_paternity_pay/yes/no/2015-01-07/2015-05-03/yes/2015-01-01/2015-01-07
* After: https://www.gov.uk/calculate-statutory-sick-pay/y/statutory_paternity_pay/yes/no/2015-01-07/2015-05-03/yes/2015-01-01/2015-01-07

### Linked PIW must be at least 4 calendar days long

New validation error message: **The linked period of sickness must be at least 4 calendar days long**

* Before: https://www.gov.uk/calculate-statutory-sick-pay/y/ordinary_statutory_paternity_pay/yes/no/2015-10-01/2015-10-04/yes/2015-09-01/2015-09-03
* After: https://www.gov.uk/calculate-statutory-sick-pay/y/statutory_paternity_pay/yes/no/2015-10-01/2015-10-04/yes/2015-09-01/2015-09-03

### Only usual working days are Qualifying Days in linked PIW

In the following scenario the linked period of sickness is 8 calendar days (Thursday-Thursday) and the employee works Sundays & Fridays. Previously it was assumed that all 8 days were qualifying days; whereas now only the Sunday & Friday are counted as qualifying days.

Thus previously the linked period of sickness accounted for all of the 3 waiting days (leaving 0 waiting days); whereas now it only accounts for 2 of the 3 waiting days (leaving 1 waiting day). Therefore where previously the 2 days was not reduced, now the 2 days is reduced by 1 day to 1 day; and the SSP amount for the week ending 14th March 2015 is reduced to £0 accordingly.

* Before: https://www.gov.uk/calculate-statutory-sick-pay/y/none/yes/no/2015-03-12/2015-03-19/yes/2015-03-02/2015-03-09/eight_weeks_more/weekly/2015-02-27/2015-01-02/1000.0/0,5
  * "Your employee is entitled to SSP for **2** days out of 2 working days"
  * Week ending 14 March 2015, SSP amount: **£43.78**

* After: https://www.gov.uk/calculate-statutory-sick-pay/y/none/yes/no/2015-03-12/2015-03-19/yes/2015-03-02/2015-03-09/eight_weeks_more/weekly/2015-02-27/2015-01-02/1000.0/0,5
  * "Your employee is entitled to SSP for **1** days out of 2 working days"
  * Week ending 14 March 2015, SSP amount: **£0.00**

### Remove 'Ordinary' from 'Ordinary Statutory Paternity Pay'

The **Ordinary** prefix should no longer be used anywhere in the SSP calculator.

* In the 'Is your employee getting any of the following?' question

  * Before/After: https://www.gov.uk/calculate-statutory-sick-pay/y

* In the URL when the above option is selected

  * Before: https://www.gov.uk/calculate-statutory-sick-pay/y/ordinary_statutory_paternity_pay
  * After: https://www.gov.uk/calculate-statutory-sick-pay/y/statutory_paternity_pay

* On the outcome page when the above option is selected and the employee is entitled to sick pay

In the 'What you need to know' section:

  * Before: https://www.gov.uk/calculate-statutory-sick-pay/y/additional_statutory_paternity_pay,ordinary_statutory_paternity_pay/no/no/2013-04-02/2013-04-10/yes/2013-01-01/2013-02-15/before_payday/fortnightly/2000.0/30/0,6
  * After: https://www.gov.uk/calculate-statutory-sick-pay/y/additional_statutory_paternity_pay,statutory_paternity_pay/no/no/2013-04-02/2013-04-10/yes/2013-01-01/2013-02-15/before_payday/fortnightly/2000.0/30/0,6/

## Useful references

* [Statutory Sick Pay (SSP)](https://www.gov.uk/statutory-sick-pay)
* [Statutory Sick Pay: manually calculate your employee’s payments](https://www.gov.uk/guidance/statutory-sick-pay-manually-calculate-your-employees-payments)
* [SPM10135 - Statutory Sick Pay (SSP) - General Information](http://www.hmrc.gov.uk/manuals/spmmanual/spm10135.htm)
* [Statutory Sick Pay calculator - LOGIC](https://drive.google.com/open?id=1qHAJUhXYR1ophsUkewRmkiSeY39StsElMvJzKMlhMTc)

### CODE REVIEW

**Comment by floehopper** [comment]
Note that although I'm pretty confident that this is now ready for deployment, I'm still waiting for the final go ahead from HMRC.

**Comment by floehopper** [comment]
We've had the go ahead from HMRC to deploy this. I'm removing the "Waiting on factcheck" label.

Could someone please review it? Thanks.

**Comment by chrisroos** [comment]
This looks good to me. Great work manually updating the regression test artefacts. It made it much easier to follow the changes we were expecting to see.

**Comment by floehopper** [comment]
I've updated the commit notes that @chrisroos highlighted, rebase against master and force-pushed in preparation for merging.

**Pull request merged**
