### PR TITLE
Update apply tier 4 visa: service outage

### PR DESCRIPTION
**Pull request by lutgendorff**

### CODE REVIEW

**Comment by heathd** [comment]
I've pushed a clone of this branch to alphagov:lutgendorff-patch-10 to trigger a branch build.

**Comment by floehopper** [comment]
Manually merged in 6ca437a3e052379fe24219cc0233eb33c9219c19.

**Comment by floehopper** [comment]
The build on master including this commit passed - https://ci-new.alphagov.co.uk/job/govuk_smart_answers/2592/

**Comment by floehopper** [comment]
FWIW here's a record of what I did. I think it would be good to update the README with instructions along these lines.

```
# Checked out the branch on my local machine

$ git remote add lutgendorff git@github.com:lutgendorff/smart-answers.git
$ git fetch lutgendorff
$ git co -b patch-10 lutgendorff/patch-10

# Reviewed the changes in the commit
# Removed trailing whitespace
# Ran the following command to re-generate the HTML artefacts for the regression tests [1]:

$ RUN_REGRESSION_TESTS=apply-tier-4-visa ruby test/regression/smart_answers_regression_test.rb

# Reviewed the changes to the HTML artefacts to check they were as expected
# Ran the following command to update the checksums for the smart answer [2]:

$ rails r script/generate-checksums-for-smart-answer.rb apply-tier-4-visa

# Ran the main test suite

$ rake

# Staged the changed files & amended the commit

$ git add .
$ git commit --amend

# Ran the regression test for the smart answer (now that HTML artefacts & file checksums had been updated)
 
$ RUN_REGRESSION_TESTS=apply-tier-4-visa ruby test/regression/smart_answers_regression_test.rb

# Merged the branch into master (I did a fast-forward merge because it was just one commit) & pushed to origin

$ git checkout master
$ git merge patch-10
$ git push

[1]: Point 11 in this section of the README - https://github.com/alphagov/smart-answers/blob/master/README.md#adding-regression-tests-to-smart-answers
[2]: Point 9 in this section of the README - https://github.com/alphagov/smart-answers/blob/master/README.md#adding-regression-tests-to-smart-answers
```

**Comment by tadast** [comment]
@floehopper I think instructions like this would be useful to have in the readme. Perhaps just change it to present tense to keep it consistent.

PS.: I have a git alias that makes it very easy to create a local branch given a PR id. Not sure if it's worth mentioning it in README, but I use it a lot and just wanted to share it :)
```
# ~/.gitconfig
[alias]
  # usage `git pr <ID>`
  pr = "!f() { git fetch origin pull/$1/head:pr-$1 && git checkout pr-$1; }; f"
```

**Comment by floehopper** [comment]
@tadast: I've added instructions in #1785. I haven't included your alias, because I think that's more of a personal preference...

**Pull request closed without merging**
