### PR TITLE
Pr 2580 consular fees kazakhstan kyrgyzstan

### PR DESCRIPTION
**Pull request by chrisroos**
This is a version of PR #2580 that's been rebased on master. I've created it to demonstrate how I think that PR should look given that master has changed since it was first created.

Differences between this PR and PR #2580:

* This PR only has two commits versus the three commits in PR #2580. The regeneration of marriage-abroad-files.yml was (confusingly) split between the first and third commit in PR #2580. It's regenerated in the first commit alone in this branch which meant that the third commit was empty and has disappeared.

* This PR only contains changes to the artefacts for residents of the ceremony_country, versus changes to the artefacts for residents of the UK and ceremony_country in PR #2580. This is because PR #2578 has been merged to master since #2580 was opened. PR #2578 ensures that we're only displaying the link to consular fees if there are chargeable services available for the combination of options leading to the outcome. For Kazakhstan and Kyrgyzstan the chargeable services are only available for ceremonies where the user is resident in the ceremony_country (see [marriage_abroad_services.yml](https://github.com/alphagov/smart-answers/blob/master/lib/data/marriage_abroad_services.yml#L464)).

### CODE REVIEW

**Comment by chrisroos** [comment]
I'm going to close this. It doesn't need to be open to serve as a demonstration.

**Comment by pmanrubia** [comment]
Hi @chrisroos, I am curious to know if you found any particular reason for not generating the artefacts as a part of the first commit.

**Comment by ikennaokpala** [comment]
@chrisroos thanks for reviewing this PR #2580  and creating this  PR to further clarify things.. I have cheery picked and included it here

**Comment by chrisroos** [comment]
> Hi @chrisroos, I am curious to know if you found any particular reason for not generating the artefacts as a part of the first commit.

@pmanrubia: This is how the commits were structured in PR #2580. I simply rebased on master and edited the commits so that they continued to work after some of the more recent changes in master.

**Pull request closed without merging**
