### PR TITLE
Refactor overseas passports flow

### PR DESCRIPTION
**Pull request by erikse**
This PR aims to tidy up the smart answer flow for overseas passports, extracting logic from the flow definition into a calculator class where it can be unit tested.

With the exception of the `overseas_passports_embassies` value calculated in question 1 (which are not currently available for the location options of question 1a), the calculator class provides a complete encapsulation of the logic required by the flow, outcomes and partials in overseas passports.

This PR supersedes #2331, and is based on #2341, which should be merged before this PR.

### CODE REVIEW

**Comment by erikse** [comment]
With PR #2341 merged, which this was branched from, I've just based this with master

**Comment by floehopper** [comment]
Minor: Quite a lot of the commit subjects talk about "adding" or "removing" things when actually they are really "moving" logic (often from a block to a method on the calculator).

**Comment by floehopper** [comment]
Ideally I'd like to see at least the non-minor comments addressed before this is merged, but overall this is a massive improvement. Great work, @erikse! :tada:

**Comment by erikse** [comment]
Thanks for the review and all your comments @floehopper.

I've started addressing them and will reply to each one here, and then push changes to a new PR based off branch `refactor_overseas_passports_flow` updates.

**Comment by erikse** [comment]
This PR is superseded by #2367 where I'm addressing the comments.

**Pull request closed without merging**
