### PR TITLE
Update collection offices for Jamaica, Jordan and Zimbabwe in overseas passports

### PR DESCRIPTION
**Pull request by robinjam**
Continued from #2692 and #2709
[Trello card](https://trello.com/c/plrA8XWq/292-6-september-overseas-passports-durham-office-moving-content-change-request)

## Description

* Update Durham passport office address in `_sending_your_application` partial of Overseas Passports smart answer.
* Update the collection offices for Jamaica, Jordan and Zimbabwe in the "Getting your passport" section of the Overseas Passports smart answer.

**Needs to go live on 06/09/2016**

## Factcheck

[Preview link for factcheck](https://smart-answers-pr-2710.herokuapp.com/overseas-passports)
[Original version on gov.uk](https://www.gov.uk/overseas-passports)

#### Before

screen shot 2016-09-05 at 11 05 56

#### After

screen shot 2016-09-05 at 11 06 00

#### Before

screen shot 2016-09-05 at 11 07 04

#### After

screen shot 2016-09-05 at 11 07 08

#### Before

screen shot 2016-09-05 at 11 07 48

### After

screen shot 2016-09-05 at 11 07 50

### CODE REVIEW

**Comment by leenagupte** [comment]
👍

**Comment by robinjam** [comment]
I've merged #2709 into this PR, so it'll need another code review.

**Comment by ikennaokpala** [comment]
@robinjam I have looked through this PR and found that you have updated overseas-passports-questions-and-responses.yml and overseas-passports-responses-and-expected-results.yml with jamaica, jordan and zimbabwe. This has allowed you to generate regenerate artefacts that only show the current state. 

It would be nice if this is done before the commit that actually makes the changes.

This way we get to learn more about its initial state and difference after  changes were made to the passport application and collection office address and content.

**Comment by ikennaokpala** [comment]
Closing this PR as we prepare for tomorrow's release and it is now being superseded by #2714

**Comment by pmanrubia** [comment]
Closing this PR as it has been superseded by #2714

**Pull request closed without merging**
