### PR TITLE
Marriage abroad gibraltar

### PR DESCRIPTION
**Pull request by pmanrubia**
### Note for code-review

The artefacts are regenerated several times to facilitate the review. They mimic the development process I followed. So this PR will be superseded by a new PR that regenerate artefacts once at the end of the commits. I am following a similar approach to: similar approach to https://github.com/alphagov/smart-answers/pull/2511 and https://github.com/alphagov/smart-answers/pull/2504

### Trello card

[Trello card for Gibraltar marriage tool](https://trello.com/c/lCpa3jdM/110-gibraltar-marriage-tool-content-change-request)

## Description
* For all opposite sex marriage outcomes in Gibraltar British nationals need to contact the Gibraltar government to find out about marriage there. They can contact the Civil Status and Registration Office
* For all same sex marriage outcomes in Gibraltar British nationals need to contact the Gibraltar government to find out about marriage or civil partnerships there. They can contact the Civil Status and Registration Office

## Factcheck
[Gibraltar marriage tool update](https://smart-answers-pr-2512.herokuapp.com/marriage-abroad)

## Expected changes

* [URL on GOV.UK](https://www.gov.uk/marriage-abroad)

### Opposite sex

* Before 

screen shot 2016-05-09 at 12 56 07

* After
screen shot 2016-05-09 at 12 54 23

### Same sex

* Before

screen shot 2016-05-09 at 12 55 07

* After

screen shot 2016-05-09 at 12 55 17

### CODE REVIEW

**Comment by sistephens** [comment]
This looks good to me - ready for code review.

Original request from FCO is here: https://govuk.zendesk.com/agent/tickets/1300731

**Comment by pmanrubia** [comment]
@sistephens thank you for your review.
I have made the Gibraltar email address a link in https://github.com/alphagov/smart-answers/pull/2512/commits/709e00cab59725947ad051a7874c747efad9e928. Thank you for spotting it.

**Comment by ikennaokpala** [comment]
@pmanrubia I noticed that you have generated artefacts and checksums twice for each

Are these intentional??

I believe f1861a14b10ecc7dc44d41a75077b9a54034e534 and 6692873c5e2492677440799625bc178e47e69d0c have made redundant by the commits that follow.

**Comment by ikennaokpala** [comment]
The commit message for e3b441034fe08347ce967c0b8ee8bbd72c3b06b4 appears too long.

SEE [this](https://github.com/alphagov/styleguides/blob/master/git.md) for more information.

**Comment by pmanrubia** [comment]
Thank you for reviewing  

#### Commits structure
The commits: aad9456be0be0ece5dccc9b21f839beb16fb5641, f1861a14b10ecc7dc44d41a75077b9a54034e534 and 6692873c5e2492677440799625bc178e47e69d0c are intentional. 

Let me explain you, because I forgot to update the PR notes:

The idea is to create a new PR superseding this; the new PR will regenerate the artefacts once, following a similar approach to https://github.com/alphagov/smart-answers/pull/2511 and https://github.com/alphagov/smart-answers/pull/2504.

These commits facilitate the review because they mimic the development process I followed.
The next step for this PR would be to close it, and generate a new PR with only 1 commit for the artefacts (https://github.com/alphagov/smart-answers/pull/2511 and https://github.com/alphagov/smart-answers/pull/2504.) 

Sorry if It wasn't clear in the PR description. I should have explained it.

I hope this makes sense.

#### Commits length.
Thank you for the reference to the style guide. Sometimes it's hard to find a balance between what you want to say and the space to have (50 characters), especially with such a long names for our outcomes and partials (they have many prefixes)
It happens in most of the commits for Marriage Abroad:
https://github.com/alphagov/smart-answers/pull/2504/commits/28a10b52658597d6bb5f78a1125426b907ec46c1
https://github.com/alphagov/smart-answers/pull/2504/commits/d5a438459de7fb432b41afb29dd295d27b9cda67
https://github.com/alphagov/smart-answers/commit/1db82d9314a84ad1dce0a8c4e2e3c339e0e33bc7
If you have a better title for the commit, please, let me know; I will gladly update it.

**Comment by pmanrubia** [comment]
@ikennaokpala I have updated the PR notes with:

> The artefacts are regenerated several times to facilitate the review. They mimic the development process I followed. So this PR will be superseded by a new PR that regenerate artefacts once at the end of the commits. I am following a similar approach to: similar approach to #2511 and #2504

**Comment by chrisroos** [comment]
I have a couple of questions about the commit titled "Update outcome_opposite_sex_marriage_in_british_overseas_territory" (709e00cab59725947ad051a7874c747efad9e928):

1. Do you know why this organisation isn't available via the organisations API (https://www.gov.uk/api/world-locations/gibraltar/organisations.json)? I don't really know much about the organisations API but it would seem like this data belongs there.

2. Did you consider adding the address to _contact_method.govspeak.erb partial rather than to the outcome (I know it's extracted to a partial in a later commit)? Unfortunately I don't really understand the purpose of the _contact_method partial so it may well be that the address doesn't belong there.

**Comment by chrisroos** [comment]
In the commit titled "Update outcome_same_sex_marriage_and_civil_partnership_in_other_countries for Gibraltar" (9b1ccb0867676a5dc5b8668465489775598b3f1b) did you consider adding a new Gibraltar-specific partial? I ask because it feels as though the outcome is now being overloaded to do two things:  explain that the ceremony isn't possible and to explain that it is possible in Gibraltar. This is also related to PR #2410 in which I'm trying to remove the duplication between `outcome_same_sex_marriage_and_civil_partnership_in_other_countries` and `outcome_same_sex_marriage_and_civil_partnership_not_possible`.

**Comment by chrisroos** [comment]
I found these commits really easy to follow. Good stuff, @pmanrubia! I know it's painful to run the regression tests multiple times in a single branch but I find that it makes it much easier to review.

**Comment by ikennaokpala** [comment]
@pmanrubia for clarifying your thought process earlier.. based on that this PR Look good to me.

**Comment by chrisroos** [comment]
Sorry to be a pain @pmanrubia but can I ask you to create a new outcome for Gibraltar (as suggested in https://github.com/alphagov/smart-answers/pull/2512#issuecomment-218686290)? This is because I've now heard back about PR #2410 and the `outcome_same_sex_marriage_and_civil_partnership_in_other_countries` outcome is going to disappear. Please let me know if you have any questions.

**Comment by pmanrubia** [comment]
> Do you know why this organisation isn't available via the organisations API (https://www.gov.uk/api/world-locations/gibraltar/organisations.json)? I don't really know much about the organisations API but it would seem like this data belongs there.

Good point, @chrisross; 
1. I have asked about it: the API is populated in Whitehall. So I will talk to the content editors to see if they can add this organisation. It might take a few days, so I have created this [Trello card][1] to track this work. From that conversation, we have agreed on documenting the interface between `smart-answers` and the endpoint so we are notified if this interface is updated. 
2. I have also created another [Trello card][2] to investigate the endpoint: https://country.register.gov.uk/; this is currently in Beta, but it seems that it might be the way to go in order to get a country list.

> Did you consider adding the address to `_contact_method.govspeak.erb` partial rather than to the outcome (I know it's extracted to a partial in a later commit)? Unfortunately I don't really understand the purpose of the _contact_method partial so it may well be that the address doesn't belong there.

Yes, I thought about it, but I didn’t see it clear. Not sure why, but it felt to me that the data has different nature: all entries in that partial are links with this format: [Make an appointment at the embassy in Jakarta.](https://www.consular-appointments.service.gov.uk/fco/#!/british-embassy-jakarta/oaths-affirmations-and-affidavits/slot_picker), whereas for Gibraltar, we need the address of a new organisation.
I would prefer to come back to this suggestion, once the new [outcome is extracted](https://github.com/alphagov/smart-answers/pull/2512#issuecomment-219273658)
> In the commit titled "Update outcome_same_sex_marriage_and_civil_partnership_in_other_countries for Gibraltar" (9b1ccb0) did you consider adding a new Gibraltar-specific partial? I ask because it feels as though the outcome is now being overloaded to do two things: explain that the ceremony isn't possible and to explain that it is possible in Gibraltar. This is also related to PR #2410 in which I'm trying to remove the duplication between outcome_same_sex_marriage_and_civil_partnership_in_other_countries and outcome_same_sex_marriage_and_civil_partnership_not_possible.

No, I didn’t think about it, but if feels like a good idea.  Thanks :+1:

> Sorry to be a pain @pmanrubia but can I ask you to create a new outcome for Gibraltar (as suggested in #2512 (comment))? This is because I've now heard back about PR #2410 and the outcome_same_sex_marriage_and_civil_partnership_in_other_countries outcome is going to disappear. Please let me know if you have any questions.

Thank you again for your review in this PR. It is much appreciated :)

@chrisross, I am happy to:
1. Extract the new outcome for Gibraltar
2. Check if Gibraltar contact details sits better on the `_contact_method` partial

But I would prefer to tackle this feedback in separate cards, as there are many moving parts on this PR / story. I will split the work in the following cards:

1. Trello card to extract the new outcome and see if the contact details sits better in `_contact_details.govspeak.erb` partial. Just a refactor on top of what we have. I will start working on it today or tomorrow, but I would prefer to finish up this PR first. 
2. Trello card to track the work of adding Gibraltar organisation to Whitehall (so it will appear in the endpoint), and use it in Gibraltar.
3. Trello card to investigate the endpoint about countries and organisations, so we know what is the best / official way to retrieve this information.
4. Trello card to [track other organisations in the same situation as Gibraltar](https://github.com/alphagov/smart-answers/blob/marriage-abroad-gibraltar/lib/smart_answer_flows/marriage-abroad/outcomes/outcome_opposite_sex_marriage_in_consular_cni_countries_when_residing_in_uk_or_ceremony_country.govspeak.erb#L183-L232) 

I hope this makes sense for you.

**Comment by floehopper** [comment]
`@chrisross` -> @chrisroos

**Comment by pmanrubia** [comment]
Sorry @chrisroos, I misspelled your GitHub username.
Thank you @floehopper for finding out 👍

**Comment by pmanrubia** [comment]
Superseded by #2533

**Comment by floehopper** [comment]
> I have also created another Trello card to investigate the endpoint: https://country.register.gov.uk/; this is currently in Beta, but it seems that it might be the way to go to get a country list.

Do you know whether there are plans for that registry to also contain the data relating to organisations? I suspect it might not and therefore, it's probably more sensible to continue to use the Worldwide API backed by Whitehall and then have Whitehall use that register for the canonical list of countries.

**Comment by pmanrubia** [comment]
@floehopper, yes it makes sense. 
The goal of the Trello card is to gather information about the endpoints and the data they provide. Once we have this data, we might be in a better place to decide the best way to go, or at least, be aware of the incoming changes that could impact in `smart-answers`.

**Comment by floehopper** [comment]
👍

**Pull request closed without merging**
