### PR TITLE
Marriage Abroad. Ticket 16

### PR DESCRIPTION
**Pull request by tadast**
This is a batch of marriage abroad process changes in Poland, United Arab Emirates, Indonesia, Vietnam, Cambodia, Thailand. All commits in this branch have been reviewed in sub-PRs. 

This is currently being fact-checked and is not ready to be merged yet. Opening a PR so it doesn't get lost.

No need to review this until we hear back from FC.

### CODE REVIEW

**Comment by chrisroos** [comment]
@tadast: Does this need to be reviewed again given that it's already been reviewed in sub-PRs?

**Comment by tadast** [comment]
No, not until we get feedback from fact check at least. Sorry, i should've made it clear in the PR description, I'll update it.

**Comment by floehopper** [comment]
@tadast: Is someone chasing the fact-check on this? I'm getting nervous that this branch has been sitting around so long, especially given the number of changes it includes.

**Comment by tadast** [comment]
@floehopper I've seen some [activity on zendesk](https://govuk.zendesk.com/agent/tickets/1140229): it should soon be ready for Erik to implement the changes originating from FCO feedback.

**Comment by floehopper** [comment]
@tadast: Thanks. /cc @er-ke-de

**Comment by erik-eide** [comment]
Rather than over-writing the history in this branch, I've pushed a new branch that updates this pull-request with the recent changes merged in master to:

[smart-answers branch: update_country_specific_outcomes_for_marriage_abroad](https://github.com/alphagov/smart-answers/tree/update_country_specific_outcomes_for_marriage_abroad)

**Comment by floehopper** [comment]
@erik-eide: I assume you're intending to open a new PR once the new branch is ready. If so, I think I would close this PR.

**Comment by erik-eide** [comment]
Yep, still a bit to go on the new branch but will close this one

**Pull request closed without merging**
