### PR TITLE
Maternity paternity calculator update

### PR DESCRIPTION
**Pull request by pmanrubia**
### Trello card
* [maternity and paternity calculator update](https://trello.com/c/7qdiyJQt/301-maternity-and-paternity-calculator-for-employers-content-change-request)

## Description

We have had a number of complaints regarding the maternity/paternity calculator. The calculator is calculating correctly payments under normal circumstances but not when payments are paid earlier than normal e.g. Christmas or bank holidays.

Calculations are on occasions incorrect and in some cases resulting in no entitlement. This may result in increased disputes and increased customer contact which will impact HMRC resources: [example](https://www.gov.uk/maternity-paternity-calculator/y/maternity/2016-03-25/yes/2016-01-03/yes/yes/2015-12-11/2015-09-30/monthly/6000.0/usual_paydates/last_working_day_of_the_month/1,2,3,4,5)

The same hint has also been updated in `calculate-statutory-sick-pay`

## Factcheck
[maternity-paternity-calculator-1](https://smart-answers-pr-2722.herokuapp.com/maternity-paternity-calculator/y/maternity/2016-03-25/yes/2016-01-03/yes/yes)
[calculate-statutory-sick-pay-2](https://smart-answers-pr-2722.herokuapp.com/calculate-statutory-sick-pay/y/statutory_paternity_pay/no/no/2012-03-03/2015-02-02/yes/2010-04-02/2012-03-01/eight_weeks_more/fortnightly)
## Expected changes 

* [URL on GOV.UK-1](https://gov.uk/maternity-paternity-calculator/y/maternity/2016-03-25/yes/2016-01-03/yes/yes)
* [URL on GOV.UK-2](https://gov.uk/calculate-statutory-sick-pay/y/statutory_paternity_pay/no/no/2012-03-03/2015-02-02/yes/2010-04-02/2012-03-01/eight_weeks_more/fortnightly)

### Before

https://gov.uk/maternity-paternity-calculator/y/maternity/2016-03-25/yes/2016-01-03/yes/yes

image

### After

https://smart-answers-pr-2722.herokuapp.com/maternity-paternity-calculator/y/maternity/2016-03-25/yes/2016-01-03/yes/yes

image

### Before

https://gov.uk/calculate-statutory-sick-pay/y/statutory_paternity_pay/no/no/2012-03-03/2015-02-02/yes/2010-04-02/2012-03-01/eight_weeks_more/fortnightly

image

### After

https://smart-answers-pr-2722.herokuapp.com/calculate-statutory-sick-pay/y/statutory_paternity_pay/no/no/2012-03-03/2015-02-02/yes/2010-04-02/2012-03-01/eight_weeks_more/fortnightly

image

### CODE REVIEW

**Comment by leenagupte** [comment]
@pmanrubia The new hint text is the same everywhere that it is used. I think it should be moved into a partial template.

**Comment by pmanrubia** [comment]
You are right @leenagupte, thank you. 
I have addressed your comment in: https://github.com/alphagov/smart-answers/pull/2722/commits/7541ccfbbb0f4eb7ffeb05a825a6a606eda2a7aa

**Comment by leenagupte** [comment]
@pmanrubia You missed one: `last_payday_before_sickness.govspeak.erb` 😢

**Comment by pmanrubia** [comment]
Thank you @leenagupte. It's in a different calculator I will update the description accordingly, because I didn't clarify it.

**Comment by leenagupte** [comment]
@pmanrubia Thanks. I missed that.

**Comment by leenagupte** [comment]
Thannks @pmanrubia 👍

**Pull request merged**
