### PR TITLE
Marriage abroad ticket 15. Estonia

### PR DESCRIPTION
**Pull request by tadast**
Add a callout for Estonia's outcomes when residing in the country.

There is a CNI exception for long-time residents.

### CODE REVIEW

**Comment by chrisroos** [comment]
Should this also contain updates to the regression test html outcomes in test/artefacts?

**Comment by chrisroos** [comment]
Other than my question about html outcomes this looks good to me.

**Comment by tadast** [comment]
@chrisroos ideally it would, but I'm planning to do that on a tt_ma_ticket_15 -> master PR (note that this is a PR for tt_ma_ticket_15 branch).

I'm not doing that simply because it takes 1h to generate HTML artefacts and I will have 20 or so PRs for this batch of changes.

However, if I could somehow restrict the set of answers to use for a specific question when generating HTML artefacts e.g. `ceremony_country=estonia,latvia` it would improve the experience for me :)

**Comment by chrisroos** [comment]
> I'm not doing that simply because it takes 1h to generate HTML artefacts and I will have 20 or so PRs for this batch of changes.

Bah, sorry. I didn't realise it took so long to generate the output. We'll have a think about whether there's anything we could do to speed it up.

**Comment by tadast** [comment]
Merged manually https://github.com/alphagov/smart-answers/commit/34d1ae59098475b82a43c3edac7ba86c415d95f2

**Pull request closed without merging**
