### PR TITLE
Delegate to MarriageAbroadDataQuery from MarriageAbroadCalculator

### PR DESCRIPTION
**Pull request by chrisroos**
This was initially opened as WIP PR #2298.

My main motivation in this branch is to have a single object that encapsulates all the logic required by the marriage-abroad flow and views. I've updated the flow and views so that we always access methods on `MarriageAbroadDataQuery` via their wrapper methods on `MarriageAbroadCalculator`.

In PR #2298 I'd started to rename some of the methods in an attempt to better reflect their purpose. This was proving quite difficult so I'm now using the original `MarrageAbroadDataQuery` method names in most cases.

### CODE REVIEW

**Comment by floehopper** [comment]
Given that I originally reviewed #2298, I haven't reviewed this in as much detail - in fact I wasn't sure whether you wanted it to be reviewed. However, as far as I can see this looks good to me.

**Comment by chrisroos** [comment]
Apologies for leaving this open for so long. I'm getting back to it now with the aim of getting it rebased and merged to master.

**Comment by chrisroos** [comment]
> Given that I originally reviewed #2298, I haven't reviewed this in as much detail - in fact I wasn't sure whether you wanted it to be reviewed. However, as far as I can see this looks good to me.

@floehopper: Thanks for reviewing this PR, and apologies for not being clearer that I wanted it reviewed again.

**Comment by chrisroos** [comment]
I'm going to close this PR and then open a new PR now that I've rebased this branch on master.

**Comment by chrisroos** [comment]
This has been superseded by PR #2346.

**Pull request closed without merging**
