### PR TITLE
Same-sex marriage outcomes in Australia: "High Commission" for "Embassy"

### PR DESCRIPTION
**Pull request by ikennaokpala**
[Trello card](https://trello.com/c/oxNfm4u0/144-same-sex-marriage-outcomes-in-australia-british-high-commission-not-british-embassy-content-change-request)

* This PR makes Content changes to the Same-sex marriage outcomes in Australia
i.e replacing "High Commission" for "Embassy".

## Factcheck
[Preview Link]( https://smart-answers-pr-2557.herokuapp.com/marriage-abroad/y/australia/ceremony_country/partner_british/same_sex)
[GOV.UK]( https://gov.uk/marriage-abroad/y/australia/ceremony_country/partner_british/same_sex)

### Before

screen shot 2016-05-31 at 15 16 28

### After

screen shot 2016-05-31 at 15 16 42

#### Affected pages

https://smart-answers-pr-2557.herokuapp.com/marriage-abroad/y/australia/ceremony_country/partner_british/same_sex
https://smart-answers-pr-2557.herokuapp.com/marriage-abroad/y/australia/ceremony_country/partner_local/same_sex
https://smart-answers-pr-2557.herokuapp.com/marriage-abroad/y/australia/ceremony_country/partner_other/same_sex
https://smart-answers-pr-2557.herokuapp.com/marriage-abroad/y/australia/third_country/partner_british/same_sex
https://smart-answers-pr-2557.herokuapp.com/marriage-abroad/y/australia/third_country/partner_local/same_sex
https://smart-answers-pr-2557.herokuapp.com/marriage-abroad/y/australia/third_country/partner_other/same_sex
https://smart-answers-pr-2557.herokuapp.com/marriage-abroad/y/australia/uk/partner_british/same_sex
https://smart-answers-pr-2557.herokuapp.com/marriage-abroad/y/australia/uk/partner_local/same_sex
https://smart-answers-pr-2557.herokuapp.com/marriage-abroad/y/australia/uk/partner_other/same_sex

### CODE REVIEW

**Comment by leenagupte** [comment]
👍

**Comment by ikennaokpala** [comment]
@leenagupte for letting me know.. @sistephens over to you.

**Comment by sistephens** [comment]
Looks good, ready for deployment 👍

**Comment by ikennaokpala** [comment]
@sistephens thanks for the feedback.. thank you all

**Pull request merged**
