### PR TITLE
Opposite sex marriages in Rwanda to Mirror other Commonwealth countries

### PR DESCRIPTION
**Pull request by ikennaokpala**
[Trello Story](https://trello.com/c/IFID2fDT/119-rwanda-marriage-tool-content-change-request)

* Content changes for all opposite sex marriages in Rwanda

## Factcheck
[Preview Link]( https://smart-answers-pr-2516.herokuapp.com/marriage-abroad/y/rwanda/ceremony_country/partner_local/opposite_sex)
[GOV.UK]( https://gov.uk/marriage-abroad/y/rwanda/ceremony_country/partner_local/opposite_sex)

### Expected changes
* Outcome for (all) opposite sex marriages in Rwanda to mirror that of other Commonwealth countries.

### Before
screen shot 2016-05-10 at 12 40 51

### After
screen shot 2016-05-10 at 12 40 31

#### Other affected pages

 https://smart-answers-pr-2516.herokuapp.com/marriage-abroad/y/rwanda/ceremony_country/partner_british/opposite_sex
 https://smart-answers-pr-2516.herokuapp.com/marriage-abroad/y/rwanda/ceremony_country/partner_local/opposite_sex
 https://smart-answers-pr-2516.herokuapp.com/marriage-abroad/y/rwanda/ceremony_country/partner_other/opposite_sex
 https://smart-answers-pr-2516.herokuapp.com/marriage-abroad/y/rwanda/third_country/partner_british/opposite_sex
 https://smart-answers-pr-2516.herokuapp.com/marriage-abroad/y/rwanda/third_country/partner_local/opposite_sex
 https://smart-answers-pr-2516.herokuapp.com/marriage-abroad/y/rwanda/third_country/partner_other/opposite_sex
 https://smart-answers-pr-2516.herokuapp.com/marriage-abroad/y/rwanda/uk/partner_british/opposite_sex
 https://smart-answers-pr-2516.herokuapp.com/marriage-abroad/y/rwanda/uk/partner_local/opposite_sex
 https://smart-answers-pr-2516.herokuapp.com/marriage-abroad/y/rwanda/uk/partner_other/opposite_sex

### CODE REVIEW

**Comment by sistephens** [comment]
Ready for code review 😃

**Reason for change:**
Rwanda is a Commonwealth country - we don't issue CNIs in Commonwealth countries.

[Zendesk ticket.](https://govuk.zendesk.com/agent/tickets/1306190)

**Comment by pmanrubia** [comment]
Regarding https://github.com/alphagov/smart-answers/pull/2516/commits/3e8b8cd3947fadfa3d4826494c8389179a0b6279...

* **Reuse of calculator method ```#ceremony_country_in_the_commonwealth?```**

If Rwanda is a Common Wealth country would it be possible to reuse the calculator check?: ```SmartAnswer::Calculators::MarriageAbroadCalculator#ceremony_country_in_the_commonwealth?```

Something like: 
```ruby
if calculator.ceremony_country_in_the_commonwealth?  
	outcome :outcome_opposite_sex_marriage_in_commonwealth_countries
```
It does not feel right to me being so specific about a country check: ```calculator.ceremony_country == 'rwanda'``` and then assign a wider scoped outcome.

*  **Common Wealth countries list**
I have also noticed that Rwanda is not included in the list of Common Wealth countries in:
```ruby
module SmartAnswer::Calculators
  class RegistrationsDataQuery
    COMMONWEALTH_COUNTRIES = %w(anguilla australia bermuda british-indian-ocean-territory british-virgin-islands cayman-islands canada falkland-islands gibraltar ireland montserrat new-zealand pitcairn south-africa south-georgia-and-south-sandwich-islands st-helena-ascension-and-tristan-da-cunha turks-and-caicos-islands)
```
If we include the country in this list, and we update the flow as described above, would it do the trick? 

* **It happens the same to `Zimbabwe`** 
```
 elsif calculator.ceremony_country_in_the_commonwealth? ||
   calculator.ceremony_country == 'zimbabwe'
```
We would need to delete the `||` condition and reuse the global check by updating the list of common wealth countries (I have created [this ticket in Trello](https://trello.com/c/FKjVHna5/132-zimbawe-is-not-listed-as-a-common-wealth-country) to tackle this issue)

**Comment by ikennaokpala** [comment]
@pmanrubia  I have followed your comments and noticed that the `COMMONWEALTH_COUNTRIES` is being use by other smart answers especially register-a-death.

SEE [this](2131c6dad1...a7e48ad995) comparison for more details.

**Comment by floehopper** [comment]
@ikennaokpala: I think @pmanrubia makes some good points. Whether or not a country is in the Commonwealth should be stored in a single place in the code. You mention that changing this list might affect other Smart Answers, but it's still probably the right thing to do. Although obviously you'll need to check with the Content Team that the changes to other Smart Answers are also correct.

**Comment by ikennaokpala** [comment]
@floehopper I agree.. @pmanrubia is right and he is looking at it at the moment.

**Comment by pmanrubia** [comment]
@ikennaokpala @floehopper thank you for your feedback. I am happy we all agree on this.

I have moved [the Trello card into blocked](https://trello.com/c/IFID2fDT/119-rwanda-marriage-tool-content-change-request), and I have created another to [track the work around including Rwanda in the list of Commonwealth countries](https://trello.com/c/U0dnbMdv/148-include-rwanda-in-the-list-of-commonwealth-countries).

I would prefer to sort out first having a unique list of Commonwealth countries, and after that, continue with the work of this PR.

I have created a spike in https://github.com/alphagov/smart-answers/pull/2536, so we can disscuss on real scenarios / data.

**Comment by pmanrubia** [comment]
@ikennaokpala @floehopper 

Following the work on this [Trello card] [1] and this [spike][2], if we include Rwanda in the Commonwealth list, then we would have inconsistencies with `register-a-birth`, and `register-a-death`.

The creation of the [spike][2] allowed us to discover that both flows `register-a-birth` and `register-a-death` are not dealing with CommonWealth countries properly, because:

> You should only get this outcome (Commonwealth outcome) if for Q1 in the tool you select one of 5 countries (Canada, South Africa, Ireland, New Zealand or Australia).

We are [in the process of fixing it](3), but a final fix might take time (need to be fact-checked).

So, I think this PR is good to go, because:
1. It’s been blocked for a while for an issue related to our codebase, and we are not sure when it is going to be fixed as the solution would need to be fact-checked
2. Once both flows (`register-a-birth` and `register-a-death`) are updated, then we will be able to include Rwanda in the list of Commonwealth countries and [get rid of the check][4] in `marriage-abroad`
3. We will track this tech-debt [in the Trello][3] card as this is something we need to sort out (see post-release check); and although it is important to unify in one list all the countries belonging to the Commonwealth list, I don’t think this could create any issue while we put a final solution in place.

[1]: https://trello.com/c/U0dnbMdv/148-include-rwanda-in-the-list-of-commonwealth-countries
[2]: https://github.com/alphagov/smart-answers/pull/2536
[3]: https://trello.com/c/WWExcqcM/157-register-a-birth-and-register-a-death-remove-commonwealth-list-check
[4]: https://github.com/alphagov/smart-answers/blob/2131c6dad1091d7825f05c4f28898192afd07488/lib/smart_answer_flows/marriage-abroad.rb#L145-L146

**Comment by pmanrubia** [comment]
@ikennaokpala: Please, rebase with `master` before merging.

LGTM

**Comment by floehopper** [comment]
It looks as if merging this pull request has broken the [govuk_smart_answers_regressions CI build](https://ci.dev.publishing.service.gov.uk/job/govuk_smart_answers_regressions/3884/console). The artefacts generated when running the regression tests do not match those in the git repo.

I can't be sure whether the problem is with the actual behaviour or with the test artefacts in the repo, so I'm unsure how to fix it.

**Comment by ikennaokpala** [comment]
@floehopper I ran the regression tests and checksum before merging this. I am not sure the root cause of the artefact mis-match, will looking into it.

**Comment by floehopper** [comment]
It looks as if only some of the changes in the first commit are reflected in the changes to the artefacts. Is it possible you might have re-written the first commit to include some extra changes, but then forgot to re-run the regression tests...?

**Comment by ikennaokpala** [comment]
@floehopper I don't think so.. after review I rebase with master and allow the tests to run.. which gave me a green.. before I clicked merge.

**Pull request merged**
