### PR TITLE
Add appointment links to overseas passports

### PR DESCRIPTION
**Pull request by erikse**
Pivotal Ticket: https://www.pivotaltracker.com/story/show/114558095

Kyrgyzstan, Tajikistan, Turkmenistan and Uzbekistan are all switching to allowing online booking of consular appointments.

## Fact check

https://smart-answers-pr-2329.herokuapp.com/overseas-passports

## Expected changes
 [URL on gov.uk](https://www.gov.uk/overseas-passports/y/kyrgyzstan/renewing_new/adult#making-your-application)
 * Remove content "You’ll need to book an appointment by email. Include your first name and last name and 3 alternative dates and times. You will receive an email confirming your appointment."
 * Remove embassy address
 * Remove embassy contact details
 * Add link to book appointment online

### Before
screen shot 2016-03-03 at 11 26 56 am

### After
screen shot 2016-03-03 at 11 27 27 am

Note: this PR supersedes #2329

### CODE REVIEW

**Comment by erikse** [comment]
This has been approved by fact check for a March 15 deploy

**Comment by erikse** [comment]
I've just rebased this PR with master

**Comment by floehopper** [comment]
I've only just glanced at this. Presumably most of the commits are refactoring the flow (yay! :tada:) and a few commits are making the actual change requested in the PT story. If so, it'd be great if you could separate them into two different PRs.

**Comment by erikse** [comment]
@floehopper only the first commit changes content, all subsequent commits are refactoring changes to tidy up overseas passports, including the file changed in first commit.

**Comment by erikse** [comment]
This PR has been superseded by #2341 that contains content changes only, and I'll open a new PR for the refactoring changes once I finishing rebasing it.

**Pull request closed without merging**
