### PR TITLE
Embassy Address and Appointment Link changes for Kyrgyzstan and Kazakhstan

### PR DESCRIPTION
**Pull request by ikennaokpala**
#PT Stories: 

Kyrgyzstan: https://www.pivotaltracker.com/n/projects/1270592/stories/115618321
Kazakhstan: https://www.pivotaltracker.com/n/projects/1270592/stories/115618165

* Change Embassy location Kyrgyzstan & Kazakhstan

### Expected changes

*  [URL on Gov.UK](//gov.uk/marriage-abroad/y/kyrgyzstan/ceremony_country/partner_british/opposite_sex)
* Change to City to Almaty to Bishkek and appointment booking link

### Before
screen shot 2016-03-14 at 17 11 23

### After

screen shot 2016-03-14 at 17 11 40

### Expected changes

*  [URL on Gov.UK](//gov.uk/marriage-abroad/y/kazakhstan/ceremony_country/partner_british/opposite_sex)
* Change to City to Almaty to Astana and appointment booking link

### Before
screen shot 2016-03-14 at 17 10 26

### After
 
screen shot 2016-03-14 at 17 10 35

### CODE REVIEW

**Comment by ikennaokpala** [comment]
@erikse @pmanrubia factcheck has comethrough kindly review

**Comment by erikse** [comment]
@ikennaokpala - with the screenshots, one thing I've been trying to do is only highlight the text that is changed, so I don't have read through content that doesn't

**Comment by erikse** [comment]
@ikennaokpala - is there an update to the marriage abroad checksums file missing in this PR?

**Comment by ikennaokpala** [comment]
Will regenerate it and push

**Comment by erikse** [comment]
Other than than the commit notes in the first two commits wrapping and probably being over 72 characters, this looks good to rebase, and merge

**Pull request merged**
