### PR TITLE
Enable Autumn changes as default (Benefit Cap Calculator)

### PR DESCRIPTION
**Pull request by ikennaokpala**
Supersedes #2779 

[Trello card](https://trello.com/c/YVrqzM52/153-remove-second-flow-from-benefit-cap-calculator-needs-to-be-live-by-7-november-2016)
## Motivation

In preparation for the new Autumn rules to benefits, this PR makes changes to enable the new rules as default.

In the Trello card the steps have defined and the commits reflect the steps. 

**NB:**
Kindly take your time whilst reviewing this PR. See the Trello checklist for guidance.
On purpose I have created a commit per step, with the intention of making clear what is actually going on.
## Factcheck

[Preview link](//smart-answers-pr-2774.herokuapp.com/benefit-cap-calculator/y)
[GOV.UK](//gov.uk/benefit-cap-calculator/y)
## Expected changes
- Removal of routing question 
- Only autumn flow available, replaces the former default.
### Before

screen shot 2016-10-07 at 10 22 50
### After

screen shot 2016-10-07 at 10 22 35

### CODE REVIEW

**Comment by leenagupte** [comment]
@ikennaokpala This looks really good. There are just a couple of things:

1.  After commit ae51057c5ee0bc0915059fca7d32eafceb25152d, I where you remove all references to chosen_cap, I would add more commits that remove `version` from the method declarations in `benefit_cap_calculator_configuration`. That way you don't have to pass `default` to the methods in the flow, e.g.: 
   ```
   calculate :exempt_benefits do
       config.exempt_benefits(:default)
   end
   ```
would become:
   ```
   calculate :exempt_benefits do
       config.exempt_benefits
   end
   ```
I'll admit to missing this step when I created the original checklist. Sorry!

2. There is a small problem with the copy on the outcome templates. 
   
   Gabriella's changes in PR #2779 should have gone live on their own so that the users of the benefit-cap-calculator are aware of that the changes to the cap come into effect on 7th November. 

   The changes in this PR need to go live on 7th November, so the copy in the outcomes needs to be changed to the present tense. 

   This is a minor change and should be able to replace commit 9b20b8b

**Comment by ikennaokpala** [comment]
@leenagupte I have updated this PR.. will make content changes once they are available..

**Comment by leenagupte** [comment]
@ikennaokpala I've just noticed this. In commit 178c1c1d1629498905715a4dba9b09844439b8c0 you should delete the associated template.

Apart from that, 👍 

If I were you, I would take a first stab at the content changes in the outcomes, and then push this to factcheck. There are only 5 affected outcomes.

e.g. Change 

`This means your Housing Benefit in autumn 2016 will now be: £<%= new_housing_benefit %>.`

To

`Your Housing Benefit is: £<%= new_housing_benefit %>.`

And change

` Based on your answers, you'll be affected by the outside London benefit cap from autumn 2016.`

To

` Based on your answers, you are affected by the outside London benefit cap.`

etc...

Or something like that.

**Comment by ikennaokpala** [comment]
@leenagupte I have reviewed the redundant template.. I will raise the content changes you mentioned with Ray and @gabrielleacosta

**Comment by gabrielleacosta** [comment]
@ikennaokpala , I would go with: 

Your Housing Benefit from 7 November 2016 will be: £<%= new_housing_benefit %>.

and 

Based on your answers, you'll be affected by the outside London benefit cap from 7 November 2016.

**Comment by leenagupte** [comment]
@gabrielleacosta These changes are due to go live on 7th November, so won't referring to the date be a bit odd?

**Comment by ikennaokpala** [comment]
@leenagupte I had a chat with @gabrielleacosta and she explained that therre will be further changes post 7 November..

**Comment by gabrielleacosta** [comment]
Hi, I was under the impression that these changes were going live before 7
November, and there was another ticket with changes Ray was working on that
was going to be updated on 7 November - and that these would include
changing the date again. If this isn't the case I'll talk to Ray and see if
we can work out a better solution. The ticket I had been working on was
just to update the date to 7 November, as autumn 2016 is vague.

**Comment by leenagupte** [comment]
@gabrielleacosta This ticket is for the changes that Ray is working on. The changes from your ticket, to update the date to 7 November was deployed as part of [release 3416](https://github.com/alphagov/smart-answers/releases/tag/release_3416)

**Comment by gabrielleacosta** [comment]
@leenagupte sorry, I'm confusing the tickets. I spoke to Ray and he's
working on changing the date again as part of the changes being deployed
7/11.

**Comment by ikennaokpala** [comment]
I have received word from Ray.. about factcheck.. Merging this PR will have to wait until Friday.. in preparation of its deployment on Monday 7 November 2016.

**Pull request merged**
