### PR TITLE
Update Philippines marriage abroad

### PR DESCRIPTION
**Pull request by emmabeynon**
Trello: https://trello.com/c/lipiOhG1/61-1-getting-married-in-the-philippines-change-request
Zendesk: https://govuk.zendesk.com/agent/#/tickets/2530654

This updates pricing information for same sex and opposite sex outcomes for marriage abroad in the Philippines.

**1. Getting married abroad - Philippines - Opposite sex**
_Preview URL_: https://smart-answers-preview-pr-3367.herokuapp.com/marriage-abroad/y/philippines/opposite_sex

_Before_
philippines-marriage-abroad-os-before

_After_
screen shot 2018-02-07 at 09 28 24

**2. Getting married abroad - Philippines - Same sex - Text change 1**
_Preview URL_: https://smart-answers-preview-pr-3367.herokuapp.com/marriage-abroad/y/philippines/same_sex

_Before_
philippines-marriage-abroad-ss-1-before

_After_
philippines-marriage-abroad-ss-1-after

**3. Getting married abroad - Philippines - Same sex - Text change 2**

_Before_
philippines-marriage-abroad-ss-2-before

_After_
screen shot 2018-02-07 at 09 30 46

### CODE REVIEW

**Comment by h-lame** [comment]
The old versions all linked `local currency` to https://www.gov.uk/government/publications/philippines-consular-fees, but we've only retained that link in one of the outcomes we've changed in this PR.  Is that intentional?  I'd assume we'd remove it from all, or leave it in all, not mix it up like this.

**Comment by emmabeynon** [comment]
Hi @JamesButlerGDS could you advise on the above comment?

**Comment by JamesButlerGDS** [comment]
@h-lame @emmabeynon Excellent spot... Sorry for letting that slip through.

Is it a pain to add it back in for the /opposite-sex outcome?

**Comment by emmabeynon** [comment]
@JamesButlerGDS Would you also like it to be added back in in the second change for the /same-sex outcome?

**Comment by JamesButlerGDS** [comment]
@emmabeynon Again, good spot! Yes please. Thanks a lot for picking up on that.

**Comment by JamesButlerGDS** [comment]
@h-lame These look good to me, happy to okay the fact check. Thanks

**Pull request merged**
