### PR TITLE
Display marriage-abroad services and fees for ceremonies in France, Monaco and French overseas territories

### PR DESCRIPTION
**Pull request by chrisroos**
Trello cards: https://trello.com/c/JRlOtA86 and https://trello.com/c/7TlLXjXb.

This branch adds the services/fees information to outcomes for France, Monaco and the French overseas territories.

## Expected changes

* Marriage in France
  * [Before](https://www.gov.uk/marriage-abroad/y/france/marriage) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/france/marriage) - "Issuing a certificate of custom and law" service/fee
* PACS in France
  * [Before](https://www.gov.uk/marriage-abroad/y/france/pacs) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/france/pacs) - "Issuing a certificate of custom and law" service/fee
* Marriage in New Caledonia
  * [Before](https://www.gov.uk/marriage-abroad/y/new-caledonia/marriage) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/new-caledonia/marriage) - "Issuing a certificate of custom and law" service/fee
* PACS in New Caledonia
  * [Before](https://www.gov.uk/marriage-abroad/y/new-caledonia/pacs) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/new-caledonia/pacs) - "Issuing a certificate of custom and law" service/fee
* Marriage in Wallis and Futuna
  * [Before](https://www.gov.uk/marriage-abroad/y/wallis-and-futuna/marriage) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/wallis-and-futuna/marriage) - "Issuing a certificate of custom and law" service/fee
* PACS in Wallis and Futuna
  * [Before](https://www.gov.uk/marriage-abroad/y/wallis-and-futuna/pacs) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/wallis-and-futuna/pacs) - "Issuing a certificate of custom and law" service/fee
* Marriage in Monaco
  * [Before](https://www.gov.uk/marriage-abroad/y/monaco/marriage) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/monaco/marriage) - "Issuing a certificate of custom and law" service/fee
* PACS in Monaco
  * [Before](https://www.gov.uk/marriage-abroad/y/monaco/pacs) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/monaco/pacs) - "Issuing a certificate of custom and law" service/fee
* Ceremonies in French Guiana
  * [Before](https://www.gov.uk/marriage-abroad/y/french-guiana) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/french-guiana) - "Issuing a certificate of custom and law" service/fee
* Ceremonies in French Polynesia
  * [Before](https://www.gov.uk/marriage-abroad/y/french-polynesia) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/french-polynesia) - "Issuing a certificate of custom and law" service/fee
* Ceremonies in Guadeloupe
  * [Before](https://www.gov.uk/marriage-abroad/y/guadeloupe) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/guadeloupe) - "Issuing a certificate of custom and law" service/fee
* Ceremonies in Martinique
  * [Before](https://www.gov.uk/marriage-abroad/y/martinique) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/martinique) - "Issuing a certificate of custom and law" service/fee
* Ceremonies in Mayotte
  * [Before](https://www.gov.uk/marriage-abroad/y/mayotte) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/mayotte) - "Issuing a certificate of custom and law" service/fee
* Ceremonies in Reunion
  * [Before](https://www.gov.uk/marriage-abroad/y/reunion) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/reunion) - "Issuing a certificate of custom and law" service/fee
* Ceremonies in St Pierre & Miquelon
  * [Before](https://www.gov.uk/marriage-abroad/y/st-pierre-and-miquelon) - No services
  * [After](https://smart-answers-pr-2526.herokuapp.com/y/st-pierre-and-miquelon) - "Issuing a certificate of custom and law" service/fee

### CODE REVIEW

**Comment by sistephens** [comment]
Hey @chrisroos. The preview links are all https://smart-answers-pr-2525.herokuapp.com. You meant them to be https://smart-answers-pr-2526.herokuapp.com right?

**Comment by sistephens** [comment]
@chrisroos Looks good to me! Thanks.

**Comment by floehopper** [comment]
Given that it sounds as if this has been given the go-ahead, I've taken the liberty of reviewing the code.

This all looks good to me from a technical point of view.

**Comment by chrisroos** [comment]
> Hey @chrisroos. The preview links are all https://smart-answers-pr-2525.herokuapp.com. You meant them to be https://smart-answers-pr-2526.herokuapp.com right?

I did indeed, @sistephens! Sorry! I've updated the description and the links should all now be correct.

**Comment by chrisroos** [comment]
Thanks for reviewing, @sistephens and @floehopper. I'm going to get this rebased and merged.

**Comment by chrisroos** [comment]
I've force pushed the branch in preparation for merging to master. There were no commit comments so we haven't lost anything through the force push.

**Pull request merged**
