### PR TITLE
Refactor calculate-agricultural-holiday-entitlement to new-style flow

### PR DESCRIPTION
**Pull request by floehopper**
## Description

This moves the flow towards the style described in the [refactoring documentation][1]. I've concentrated on moving logic out of the flow and into the calculator. I have not spent any time trying to improve the code in the calculator (e.g. by extracting domain concepts).

I've added some unit tests for the validation that I've extracted, because this behaviour is not covered in the regression tests. However, otherwise I have not moved the tests closer to how it's described in the [new-style testing documentation][2].

So, although there is more work that could be done on this flow and its associated classes, I think the changes in this PR are useful in their own right and if we can do just this much for all the flows, I think we'll be able to dramatically simplify the DSL.

Note that in doing this work I came across some suspect looking code, but rather than get sucked into sorting that out, I've captured the possible problems in a couple of Trello cards:

* https://trello.com/c/0WNxygY4
* https://trello.com/c/HXgHxbpp

## External changes

None. This is just an internal refactoring.

[1]: https://github.com/alphagov/smart-answers/blob/master/doc/refactoring.md
[2]: https://github.com/alphagov/smart-answers/blob/master/doc/new-style-testing.md

### CODE REVIEW

**Comment by floehopper** [comment]
Rebased against master to resolve conflicts and force-pushed. Ready for review.

**Comment by chrisroos** [comment]
Commit "Move first holiday_entitlement_days to be a calculator method" (27e040f96fa25afc8448c33c37da34f81bfb223d):

It looks as though `if response == 'same-employer'` has been removed as part of moving `holiday_entitlement_days` from a `calculate` block to the calculator. I presume this doesn't cause any problems?

**Comment by chrisroos** [comment]
Aside from my question about `if response == 'same-employer'`, this looks good to me.

**Comment by floehopper** [comment]
Re-writing commits to address feedback, rebasing against master, and force-pushing in preparation for merging.

**Comment by floehopper** [comment]
> Commit "Move first holiday_entitlement_days to be a calculator method" (27e040f96fa25afc8448c33c37da34f81bfb223d):
>
> It looks as though `if response == 'same-employer'` has been removed as part of moving `holiday_entitlement_days` from a `calculate` block to the calculator. I presume this doesn't cause any problems?

I've re-written the commit mentioned above so that it no longer removes the `if` statement: 2d017b8257fda7569ec8ffccc094b08b12e836f5.

I've then added a new commit which removes the `if` statement and explains why it is redundant: 99240c6cc0e9151fed32c8c89f6000b29e152b67.

**Comment by floehopper** [comment]
Once #2565 was merged, I found that I needed to make some changes to `MethodMissingHelper` and `MethodMissingObject` in order to keep `IndexableContentTest` passing. Since I was doing quite a bit of re-writing the git history, I've created a new PR (#2570). The relevant commits are:

* "Ensure MethodMissingObject#description is always a string" (c5c43494586b1dbcc1fb4431cb8889aac3030086)
* "Change MethodMissingObject overrides to return actual object" (d4af6921061e3941909494c07cf920b63b0cce83)

These changes allowed me add an "override" for "holiday_entitlement_days" and "calculator.holiday_entitlement_days" in the following two commits respectively:

* "Move formatting of holiday_entitlement_days into templates" (721ee3b78f92ee00a95ea30826c8f2efcec445ca)
* "Inline holiday_entitlement_days calculate blocks into templates" (65b72982f246875fe6acf436119a064589b76e04)

@chrisroos: Please could you review those new/edited commits for me?

**Comment by floehopper** [comment]
Superseded by #2570. Closing.

**Comment by chrisroos** [comment]
I've looked at the commits you've asked me to review, @floehopper. They look good to me. I'll add a comment to PR #2570 too.

**Pull request closed without merging**
