### PR TITLE
Calculate your statutory redundancy pay uprate

### PR DESCRIPTION
**Pull request by BenJanecke**
Uprated max amount for 2015/2016 from 13,920 to 14,250

### CODE REVIEW

**Comment by jackscotti** [comment]
I am not sure you should keep a v2 not updated with these changes floating around. What if someone merges it into a v1 and you are going to revert these new changes?

**Comment by BenJanecke** [comment]
We could apply these changes to the V2 as well?

**Comment by jackscotti** [comment]
You will then need to go through all the changes made on it... I'd say, kill the v2 in another PR. If they'll get back to us we will revert it?

**Comment by BenJanecke** [comment]
Done see #1586

**Comment by jackscotti** [comment]
:+1:

**Pull request merged**
