### PR TITLE
Standardise conditions around draught proofing text

### PR DESCRIPTION
**Pull request by leenagupte**
Trello card: https://trello.com/c/FJVXjW0E

## Motivation

Draught proofing can be displayed by four outcome templates.

Of those four, only one displays the text is Draught proofing hasn't been selected in the previous question.

In the other three outcomes, Mains gas has to not have been selected (deselected) as well.

So this link will show draught proofing: https://www.gov.uk/energy-grants-calculator/y/all_help/benefits,permission/1954-01-01/none/1940s-1984/flat/top_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation

but this one will not: https://www.gov.uk/energy-grants-calculator/y/all_help/benefits,permission/1954-01-01/none/1940s-1984/flat/top_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

To be consistent, and as there is a clear majority, I have changed the one outlying outcome to match the others.

## Factcheck

Will be added to final PR created on the feature branch.

## Expected Changes

[URL on GOV.UK](https://www.gov.uk/energy-grants-calculator/y/help_energy_efficiency/permission/before-1940/house/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation)

[Heroku Preview](https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/permission/before-1940/house/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation)
* Only show "draught proofing" bullet if both "main gas" and "draught proofing" are selected in the previous question.

### Before

screen shot 2016-07-29 at 11 03 53

screen shot 2016-07-29 at 11 04 27

### After

screen shot 2016-07-29 at 11 07 12

screen shot 2016-07-29 at 11 08 04

### CODE REVIEW

**Comment by pmanrubia** [comment]
I would expect to have artefacts changed after bfc4c52f7879c16e00e9ae2054c7585efc6cec10

**Comment by ikennaokpala** [comment]
@pmanrubia @leenagupte 

I have updated the regression config files and generated regression tests artefacts for only the mains_gas and draught_proofing options.

This I have done with the help of git and placed before commit e0c2008, to ensure that the difference as a result of the change from e0c2008 actually is apparent. 

I found that commit e0c2008 hasn't actually changed as a result of the change within.

**Comment by ikennaokpala** [comment]
@pmanrubia @leenagupte

I have updated the regression config files and generated regression tests artefacts for only the none option.

I have done with the help of git and placed it before commit 067265d, to ensure that the difference as a result of the change from 067265d actually is apparent.

I found that commit 067265d hasn't actually changed as a result of the change within.

**Comment by ikennaokpala** [comment]
@pmanrubia

Following @leenagupte's description above I noticed that the screenshots probably used these sets of options:

* Before 1940s
  - electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

And the links in the description above were setup with:

* 1940s-1984
  - cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation
  - cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation


I have added the aforementioned options to the test data YAML files to help
setup regression test artefacts.

The intention here is to track changes to the outcomes that the users selection
of the any of the aforementioned options.

From the regression test artefacts, I found the following outcomes were unaffected by the changes:

## Affected outcomes

* 1940s-1984
  - cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation


https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,permission/1940s-1984/flat/ground_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,permission/1940s-1984/flat/top_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,permission/1940s-1984/house/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,property/1940s-1984/flat/ground_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,property/1940s-1984/flat/top_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,property/1940s-1984/house/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,permission/1940s-1984/flat/ground_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,permission/1940s-1984/flat/top_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,permission/1940s-1984/house/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,property/1940s-1984/flat/ground_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,property/1940s-1984/flat/top_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,property/1940s-1984/house/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation




And the following outcomes were affected by the changes:

## Affected outcomes

* 1940s-1984
  - cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation


https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,permission/1940s-1984/flat/ground_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,permission/1940s-1984/flat/top_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,permission/1940s-1984/house/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,property/1940s-1984/flat/ground_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,property/1940s-1984/flat/top_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,property/1940s-1984/house/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,permission/1940s-1984/flat/ground_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,permission/1940s-1984/flat/top_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,permission/1940s-1984/house/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,property/1940s-1984/flat/ground_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,property/1940s-1984/flat/top_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,property/1940s-1984/house/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation








## Affected outcomes


* Before 1940s
  - electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation
  

https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,permission/before-1940/flat/ground_floor/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation
https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,permission/before-1940/flat/top_floor/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation
https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,permission/before-1940/house/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation
https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,property/before-1940/flat/ground_floor/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation
https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,property/before-1940/flat/top_floor/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation
https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_boiler_measure/benefits,property/before-1940/house/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation
https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,permission/before-1940/flat/ground_floor/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation
https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,permission/before-1940/flat/top_floor/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation
https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,permission/before-1940/house/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation
https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,property/before-1940/flat/ground_floor/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation
https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,property/before-1940/flat/top_floor/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation
https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/benefits,property/before-1940/house/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

**Comment by pmanrubia** [comment]
Great work @ikennaokpala

**Comment by leenagupte** [comment]
@ikennaokpala Thanks. I tried the same thing you did, and added new expected results that didn't include draught proofing and regenerate the test artefacts before making the change to the template.

As with your change, the new expected results (commit 33c5ce6) generate close to 1000 new test artefacts (commit d0a10b3), but the changes to the templates only modified a handful of the artefacts (commit 	b52573a). 

As I could not be sure that the artefacts modified had been added in commit d0a10b3, I decided not to keep the new expected results and artefacts.

I have no problem keeping commits 33c5ce6 and d0a10b3 if you and @pmanrubia think they add value.

**Comment by pmanrubia** [comment]
@leenagupte: thank you for the update.
As we are sure that the changes are correct (as per b52573adf66a4ccd0bf77b939ac643b380b4c10f), it might be a good idea to remove:
* 33c5ce63276d7ee9da992477735c2cf714f4df4a
* d0a10b3f8d1f303da3eba0a6c6277513d6b0bb9e
* d0a10b3f8d1f303da3eba0a6c6277513d6b0bb9e
So we don't pollute our artefacts folder.

👍 to remove those commits, rebase with master and force push

**Comment by leenagupte** [comment]
Superseded by https://github.com/alphagov/smart-answers/pull/2679

**Comment by leenagupte** [comment]
Superseded by https://github.com/alphagov/smart-answers/pull/2679

**Pull request closed without merging**
