### PR TITLE
Convert apply-tier-4-visa to ERB

### PR DESCRIPTION
**Pull request by chrisroos**

### CODE REVIEW

**Comment by tadast** [comment]
Nice! Have you regenerated HTML artefacts for regression tests? I'm pleasantly surprised not even whitespace changes were introduced.

:+1:

**Comment by chrisroos** [comment]
> Have you regenerated HTML artefacts for regression tests? I'm pleasantly surprised not even whitespace changes were introduced.

Yup, and me too :-) I think the template could be made slightly nicer with a little more whitespace but for now I'm mostly interested in keeping the output identical.

**Comment by floehopper** [comment]
The "Update apply-tier-4-visa-files.yml" commit looks as if it's at the wrong point in the git history i.e. I would've expected it to be last. Otherwise this looks good to me.

**Comment by chrisroos** [comment]
> The "Update apply-tier-4-visa-files.yml" commit looks as if it's at the wrong point in the git history i.e. I would've expected it to be last.

I reordered the commits and merged this branch to master in f0081a48c31345397619304d6ce9fa8f724567e2.

**Pull request closed without merging**
