### PR TITLE
Convert calculate-state-pension to ERB

### PR DESCRIPTION
**Pull request by chrisroos**
The amount_result.govspeak.erb template is pretty lengthy and can almost certainly be DRYed up. I did try extracting the four main branches to partials but ran into problems as I needed to pass `locals` in to each of the partials and it wasn't obvious to me that the result was going to be much better than what I have here.

At the moment I'm planning to leave the template as it is unless anyone has any insights as to how to effectively DRY it up.

### CODE REVIEW

**Comment by chrisroos** [comment]
@tadast has just pointed out that merging this to master will probably make it harder to merge #1714.

**Comment by floehopper** [comment]
I'm consciously not going to review this for now until we've decided what to do about the potential merge conflicts that @chrisroos mentions in his comment above.

**Comment by floehopper** [comment]
@chrisroos: Is it worth closing this until we decide what to do with it?

**Comment by chrisroos** [comment]
Having looked at #1714 more closely, I'm confident that I'll be able to merge this to master and then update #1714 to take this changes into account. Can someone give this a look so that I can get it merged, please?

**Comment by chrisroos** [comment]
I've just pushed some fixup commits to fix the indenting in the ERB templates, as per https://github.com/alphagov/smart-answers/pull/1766#issuecomment-117579072.

**Comment by chrisroos** [comment]
It looks like #1714 is going to get merged first so I'm going to close this for now.

**Pull request closed without merging**
