### PR TITLE
Extract marriage-abroad service data

### PR DESCRIPTION
**Pull request by chrisroos**
This branch extracts the marriage-abroad services from the ERB templates to a new YAML file.

This should make it easier to standardise the service names (https://trello.com/c/qMeYVdfh) and update the services that are offered in different circumstances (https://trello.com/c/D0ZMM9v5).

In order to verify that these changes haven't inadvertently broken anything, I generated the regression test artefacts for _all_ marriage-abroad countries and ran the tests before and after the changes in this branch. There were no changes to the artefacts.

### CODE REVIEW

**Comment by ikennaokpala** [comment]
@chrisroos needs documents especially the use of the new script

**Comment by chrisroos** [comment]
I've rebased on master and force pushed in preparation for merging given that @ikennaokpala's said this is good to merge.

**Comment by chrisroos** [comment]
I reran the marriage-abroad regression tests locally to ensure that this was still all good. Merging now.

**Comment by chrisroos** [comment]
> needs documents especially the use of the new script

@ikennaokpala: I'm not sure what to do about these new scripts yet. Given how trivial they are I think I might remove them rather than try to document how to use them. I've added a task to my todo list to do something about them.

**Pull request merged**
