### PR TITLE
Refactor inherits someone dies without will

### PR DESCRIPTION
**Pull request by svenagnew**
I've made changes as per pivotal ticket #87802440

Please review and merge if all looks good.

ticket: https://www.pivotaltracker.com/story/show/87802440

### CODE REVIEW

**Comment by bradleywright** [comment]
I've made some style comments - will leave reviewing the actual smart answers code to someone else.

**Comment by svenagnew** [comment]
Ugh .. sorry you're absolutely right. I had intended to remove that cruft prior to pushing. My apologies. I'll clean everything up now.

**Comment by jackscotti** [comment]
Can you please provide the URL of the ticket? 
Also, can you fix your GitHub user settings and rebase all the commits?

**Comment by svenagnew** [comment]
Ticket URI as requested: https://www.pivotaltracker.com/story/show/87802440

**Pull request merged**
