### PR TITLE
Refactor marriage-abroad

### PR DESCRIPTION
**Pull request by chrisroos**
This is a continuation of the work started in PR #2270.

I'm storing the responses to `marriage_or_pacs?` and `partner_opposite_or_same_sex?` on the `MarriageAbroadCalculator` and have added convenience methods to remove the duplication of comparing strings.

I've also inlined a number of `next_node_calculations` in `partner_opposite_or_same_sex?` where I didn't think they were adding any value.

### CODE REVIEW

**Comment by chrisroos** [comment]
@floehopper / @erikse. I'd really appreciate it if one of you were able to take a look at this PR.

**Comment by floehopper** [comment]
This all looks good to me. :+1:

**Comment by chrisroos** [comment]
Thanks for the review, @floehopper! I've addressed all your concerns, rebased on master and will merge to master now.

**Comment by chrisroos** [comment]
I've opened PR #2278 with the updated version of this branch so that I can preserve these comments. I'll merge to master from the new PR.

**Comment by floehopper** [comment]
:+1:

**Pull request closed without merging**
