### PR TITLE
Content for same sex marriage in Italy

### PR DESCRIPTION
**Pull request by ikennaokpala**
[Trello card](https://trello.com/c/Eu4O452N/240-italy-marriage-tool-same-sex-marriage-unions-content-change-request)

## Motivation

With the recent legalisation of same sex marriage in Italy.

This PR shows the definition of and Content changes to the same sex marriage outcome for Italy.

This includes extraction of similar text from the opposite sex outcome to partials that have been shared with the same and opposite sex outcome for Italy.

## Factcheck 

[Preview link](https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/ceremony_country/partner_british/same_sex)
[GOV.UK](https://www.gov.uk/marriage-abroad/y/italy/ceremony_country/partner_british/same_sex)

### Expected changes

Replace `no same sex marriage` content with content to support legalisation of same sex marriage

### Before

screen shot 2016-08-05 at 11 11 18

### After

screen shot 2016-08-05 at 11 11 03

##### Affected outcomes

https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/ceremony_country/partner_british/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/ceremony_country/partner_local/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/ceremony_country/partner_other/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/third_country/partner_british/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/third_country/partner_local/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/third_country/partner_other/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/uk/partner_british/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/uk/partner_local/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/uk/partner_other/same_sex

### CODE REVIEW

**Comment by pmanrubia** [comment]
@ikenna thank you for your work on this PR; I know you have worked towards meeting a tight deadline, but my feeling is that we would need to work a bit on this PR to merge it to master.

There are a lot of things happening in 3ae5f4e. It is a bit difficult for me to review it. I would suggest splitting up the first commit into smaller commits including:

* A separate commit to create the outcome you are about to extract (`outcome_same_sex_marriage_in_italy`). You might get some inspiration in #2653.
Copy `outcome_same_sex_marriage_and_civil_partnership_not_possible` to `outcome_same_sex_marriage_in_italy` and update `marriage_abroad.rb`
In this commit the file `marriage-abroad-responses-and-expected-results.yml` will be updated but regression tests should not change. We have an atomic commit (all tests passing, this is easy to understand and review)
* Update the content of `outcome_same_sex_marriage_and_civil_partnership_not_possible` and update regression tests. This is a new outcome, so you could copy the govspeak of the word document[1] as provided.
You can generate the regression tests and verify that the content is the expected.
* I would create a few commits to extract partials from the content. In each commit, I would run the regression tests writing in the commit notes that no artefacts changed (as expected)
* I would create a commit to extract the fees into the YML file. Again updating the commit notes to say that the regression tests didn’t change. 
* I have noted you have also refactored the template for opposite_sex, if so, I would create a separate commit for it.

This is just a suggestion, feel free to choose a different approach if you think it is going to be easier to review.

**Comment by pmanrubia** [comment]
As a general comment, it seems that you have extracted partials (in isolation) without following existing patterns; I know the codebase is quite messy, but still it is in our benefit to follow similar patterns of existing countries, so we make the code less painful to read.
As a side note, this is also, in my opinion, the perfect scenario to work alongside a content designer to adapt the content for existing countries so we simplify our codebase.

**Comment by pmanrubia** [comment]
Template: `_evidence_of_nationality_or_residence_in_the_country`
If you search for the text `provide evidence of nationality` you will find references in 6 templates. It would be good to discuss with the content designer if there is a way to share the same content across them. 
The last sentence `if you’re a woman you must wait 300 days…` seems to be too specific for Italy, as there is no other reference to it anywhere. I don’t think it belongs to such a generic outcome like `_evidence_of_nationality_or_residence_in_the_country`

**Comment by pmanrubia** [comment]
Template `_legalisation_and_translation_italy`. 
Could you please talk to a content designer and check this copy can be accommodated to another template? 
As a side note, other countries are rendering the partial `_legalisation_and_translation` for the header.

**Comment by pmanrubia** [comment]
Template `applying_for_a_nulla_osta` and `nulla_osta_instructions_itally` as this is not being used in other places (new creation), I would try to create a single template: `applying_for_a_nulla_osta` that includes the header and interpolate the country and embassy (the same way it is done for other countries). 
The benefit for us is that our templates are not country specific, and other countries rendering similar data can  reuse it (we can talk to a content designer and explain to him that we want to reuse it if possible)

**Comment by pmanrubia** [comment]
Template: `_supporting_documents_italy`
It seems that the name of the template is not consistent with other countries. I would expect something similar to `_required_supporting_documents(_country).govspeak`. 
Again, this could be a good opportunity of reusing content from other countries. Could you please discuss it with a content designer?

**Comment by pmanrubia** [comment]
Template: `_what_happens_next`
In other countries, this is usually inlined in the template. I would follow the same pattern unless you have certainty that the content is (or will be) the default for all countries. 
If this is not the case, I would accommodate the name to something specific to Italy or just inline the content as other countries are doing, because the title seems to be generic.

**Comment by ikenna** [comment]
I am not sure I am the Ikenna you want. Can I be removed off this thread please? Thanks.                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Pablo ManrubiaSent: Friday, August 5, 2016 4:41 PMTo: alphagov/smart-answersReply To: alphagov/smart-answersCc: Ikenna Nwaiwu; MentionSubject: Re: [alphagov/smart-answers] Content to support legalisation of same sex marriage in Italy (#2677)Template: _supporting_documents_italy
It seems that the name of the template is not consistent with other countries. I would expect something similar to _required_supporting_documents(_country).govspeak. 
Again, this could be a good opportunity of reusing content from other countries. Could you please discuss it with a content designer?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alphagov/smart-answers","title":"alphagov/smart-answers","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/modules/aws/aws-bg.jpg","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alphagov/smart-answers"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pmanrubia in #2677: Template: `_supporting_documents_italy`\r\nIt seems that the name of the template is not consistent with other countries. I would expect something similar to `_required_supporting_documents(_country).govspeak`. \r\nAgain, this could be a good opportunity of reusing content from other countries. Could you please discuss it with a content designer?"}],"action":{"name":"View Pull Request","url":"https://github.com/alphagov/smart-answers/pull/2677#issuecomment-237885238"}}}

**Comment by pmanrubia** [comment]
Again @ikennaokpala I think this is a good work 👍 , and I know that it might feel very nitpicking, but I don't want that a deadline prevent you from creating the PRs you are used to.

**Comment by ikennaokpala** [comment]
@pmanrubia I have split the commits, am attmept at making apparent the thought and change process.

**Comment by ikennaokpala** [comment]
@pmanrubia

> There are a lot of things happening in 3ae5f4e. It is a bit difficult for me to review it. I would suggest splitting up the first commit into smaller commits including:
> A separate commit to create the outcome you are about to extract (outcome_same_sex_marriage_in_italy). You might get some inspiration in #2653. Copy outcome_same_sex_marriage_and_civil_partnership_not_possible to outcome_same_sex_marriage_in_italy and update marriage_abroad.rb In this commit the file marriage-abroad-responses-and-expected-results.yml will be updated but regression tests should not change. We have an atomic commit (all tests passing, this is easy to understand and review)
> Update the content of outcome_same_sex_marriage_and_civil_partnership_not_possible and update regression tests. This is a new outcome, so you could copy the govspeak of the word document[1] as provided. You can generate the regression tests and verify that the content is the expected.

As requested in your first comment, I have split commits to show a somewhat more natural progression to arriving at the actual Content changes for same sex marriage in Italy.

See commit a3a9acd9dfb573c65796946053a5d79bd78bcf35 and fe9b3c6ba487d6af8d2cd3c9677c1c5db1de424e.


> I would create a few commits to extract partials from the content. In each commit, I would run the regression tests writing in the commit notes that no artefacts changed (as expected)

I have made these in this commit fceac9041cad69aa892a9b03a63b8ae3307ded99.. Where I have identified some similaritues and created erb partials that capture the content that have been reused as part of the same sex content in fe9b3c6ba487d6af8d2cd3c9677c1c5db1de424e.

> I have noted you have also refactored the template for opposite_sex, if so, I would create a separate commit for it.

Yes I have, like I mentioned above.. Kindly see fceac9041cad69aa892a9b03a63b8ae3307ded99

**Comment by ikennaokpala** [comment]
@pmanrubia

> Template: _evidence_of_nationality_or_residence_in_the_country
> If you search for the text provide evidence of nationality you will find references in 6 templates. It would be good to discuss with the content designer if there is a way to share the same content across them.
> The last sentence if you’re a woman you must wait 300 days… seems to be too specific for Italy, as there is no other reference to it anywhere. I don’t think it belongs to such a generic outcome like _evidence_of_nationality_or_residence_in_the_country

I had a chat with @AmyLaurence and she said we could use the exisitng text in the ```_provide_evidence_of_nationality_or_residence_for_divorce_or_dissolution.govspeak.erb``` partial. This I have introduced [here](https://github.com/alphagov/smart-answers/pull/2677/files#diff-0d93371947f89b4dc734f012bf7c61daR31)

> Template _legalisation_and_translation_italy.
> Could you please talk to a content designer and check this copy can be accommodated to another template?
> As a side note, other countries are rendering the partial _legalisation_and_translation for the header.

At the moment we are still waiting for factcheck to come through and confirm this

> Template applying_for_a_nulla_osta and nulla_osta_instructions_itally as this is not being used in other places (new creation), I would try to create a single template: applying_for_a_nulla_osta that includes the header and interpolate the country and embassy (the same way it is done for other countries).
> The benefit for us is that our templates are not country specific, and other countries rendering similar data can reuse it (we can talk to a content designer and explain to him that we want to reuse it if possible)

The reason why (at the moment) creating a single template isn't going to suffice, is becuase content within ``` nulla_osta_instructions_italy ``` and ``` applying_for_a_nulla_osta ``` don't follow each other, as you will observe [here](https://github.com/alphagov/smart-answers/pull/2677/files#diff-4dc771d8c8da7d9a304ef90a61921df3R32).

> Template: _supporting_documents_italy
> It seems that the name of the template is not consistent with other countries. I would expect something similar to _required_supporting_documents(_country).govspeak.
> Again, this could be a good opportunity of reusing content from other countries. Could you please discuss it with a content designer?

I have renamed ``` _supporting_documents_italy ``` to ``` _required_supporting_documents_italy ```. See [this](https://github.com/alphagov/smart-answers/pull/2677/files#diff-4dc771d8c8da7d9a304ef90a61921df3R44).

> Template: _what_happens_next
> In other countries, this is usually inlined in the template. I would follow the same pattern unless you have certainty that the content is (or will be) the default for all countries.
> If this is not the case, I would accommodate the name to something specific to Italy or just inline the content as other countries are doing, because the title seems to be generic.

This content is unique for italy

I have renamed this from ```_what_happens_next``` to ```_what_happens_next_italy```. This can been seen [here](https://github.com/alphagov/smart-answers/pull/2677/files#diff-0d93371947f89b4dc734f012bf7c61daR35)

**Comment by ikennaokpala** [comment]
Closing this PR to be continued in #2688

**Pull request closed without merging**
