### PR TITLE
Update tier 4 outcome: adding in IHS info

### PR DESCRIPTION
**Pull request by lutgendorff**
Need to add qualification about applying when you've already paid the IHS surcharge and how to refund if you can't finish your application on time.

### CODE REVIEW

**Comment by heathd** [comment]
I've pushed a clone of this branch to alphagov:lutgendorff-patch-11 to trigger a branch build.

**Comment by floehopper** [comment]
I'm going to look at getting this merged now.

**Comment by floehopper** [comment]
Manually merged in 9eeb308d62c93ac906de9c5d791a1f09e6eb8313.

**Comment by floehopper** [comment]
The build for this commit on master has just passed - https://ci-new.alphagov.co.uk/job/govuk_smart_answers/2593/.

**Comment by floehopper** [comment]
Manually closing.

**Comment by floehopper** [comment]
See [this comment](https://github.com/alphagov/smart-answers/pull/1778#issuecomment-118304137) for a detailed explanation of what I did to merge this change.

**Pull request closed without merging**
