### PR TITLE
Revert handling of template exceptions when generating indexable content

### PR DESCRIPTION
**Pull request by floehopper**
## Description

Trello card: https://trello.com/c/W7EDHYFB

This PR (mostly) reverts [this commit][1]. Note, however,  that I have *not* reverted the introduction of `IndexableContentTest`, because it's still a useful test to make sure we don't introduce any more code which results in raising exceptions.

The reverted commit was originally introduced so that we could generate `indexable_content` for the `outcome_os_other_countries` outcome in `marriage-abroad`. We had to add this special case to handle the potential exception raised by the outcome.

This [later pull request][2] updates the `outcome_os_other_countries` outcome such that it no longer raises an exception, which means that we can simplify the code by reverting the commit mentioned above.

However, in the meantime there have been some other changes which also cause template exceptions to be raised. Initially I was thinking that I might just not bother implementing the idea in this card, but then I realised there's a danger that we may unknowingly keep introducing problematic code thereby reducing the indexable content that we can generate.

To this end, all of the commits in this PR except for the last one fix place where template exceptions were being raised during the generation of indexable content. Once all of these were applied, I was able to do revert the commit as planned.

## External changes

It's likely that the changes in this PR will mean that more indexable content is supplied to Panopticon (and thence Rummager?) for the flows in which template exceptions were previously being raised (`register-a-birth`, `register-a-death` & `marriage-abroad`). However, there's no easy way to test this directly and in any case such changes are very low risk.

[1]: https://github.com/alphagov/smart-answers/commit/50ab9b8d4963530eae7142f230d07ae75d04fb93
[2]: https://github.com/alphagov/smart-answers/pull/2504

### CODE REVIEW

**Comment by floehopper** [comment]
Rebased against master to resolve conflicts and force-pushed. Ready for review.

**Comment by chrisroos** [comment]
Commit: "Add MethodMissingObject#to_str" (6fd4263202e503a32129152a833e49974ae8d659)

Is there a reason you didn't test this alias?

**Comment by chrisroos** [comment]
Commit: "Allow custom return value for MethodMissingObject#to_s" (b6299034d23bba5939ed1c45f293786c31844894)

Is there a reason you didn't test this change in behaviour?

**Comment by chrisroos** [comment]
Commit: "Extract oru_documents_variant_for_death? method in RegistrationsDataQuery" (30a63db3a455295abad9f433367f51d6a144d1b2)

The test context name (`oru_documents_variant_for_birth?`) doesn't match the method being tested (`oru_documents_variant_for_death?`).

**Comment by chrisroos** [comment]
How did you work out that you needed to make the changes you've made in commits 1 to 8 (i.e. all but the final revert commit)? By removing the error handling in `FlowRegistrationPresenter#indexable_content` and then running the indexable_content_test?

**Comment by chrisroos** [comment]
I'm holding off adding the LGTM label until @floehopper has chance to respond to my questions.

**Comment by floehopper** [comment]
> Commit: "Add MethodMissingObject#to_str" (6fd4263202e503a32129152a833e49974ae8d659)
> Is there a reason you didn't test this alias?

> Commit: "Allow custom return value for MethodMissingObject#to_s" (b6299034d23bba5939ed1c45f293786c31844894)
> Is there a reason you didn't test this change in behaviour?

I think it was because there weren't any unit tests for `MethodMissingObject` and I felt as if they were small changes that were covered by the `IndexableContentTest`. That and me being lazy, obviously! 😄

**Comment by floehopper** [comment]
> Commit: "Extract oru_documents_variant_for_death? method in RegistrationsDataQuery" (30a63db3a455295abad9f433367f51d6a144d1b2)
>
> The test context name (`oru_documents_variant_for_birth?`) doesn't match the method being tested (`oru_documents_variant_for_death?`).

Thanks. Well spotted. I will fix this.

**Comment by floehopper** [comment]
> How did you work out that you needed to make the changes you've made in commits 1 to 8 (i.e. all but the final revert commit)? By removing the error handling in `FlowRegistrationPresenter#indexable_content` and then running the indexable_content_test?

Yes. That's exactly what I did. In fact I reverted the commit, then wrote commits to fix the problems, and finally reordered the commits to put the revert last. I'll explain that somewhere in a commit note or the PR description.

**Comment by floehopper** [comment]
Superseded by #2565. Closing.

**Comment by floehopper** [comment]
In the new version of this PR (#2565) I've added a new commit which introduces a unit test for `MethodMissingObject` (af46c0e9fbb0fcef09b418a0b0d8bc4a51aed4e8)

> Commit: "Add MethodMissingObject#to_str" (6fd4263202e503a32129152a833e49974ae8d659)
> Is there a reason you didn't test this alias?

In the new PR, I've added unit tests for this change (3bf979f4c93a05de2589968a8538605e250f3a63)

> Commit: "Allow custom return value for MethodMissingObject#to_s" (b6299034d23bba5939ed1c45f293786c31844894)
> Is there a reason you didn't test this change in behaviour?

In the new PR, I've added unit tests for this change (d47a50b776d97b270e3b7bf6ebd15bd69ff54278)

**Comment by floehopper** [comment]
> How did you work out that you needed to make the changes you've made in commits 1 to 8 (i.e. all but the final revert commit)? By removing the error handling in `FlowRegistrationPresenter#indexable_content` and then running the indexable_content_test?

I've added a paragraph towards the end of the new PR (#2565) description which hopefully explains this a bit more.

**Comment by chrisroos** [comment]
I've added a [comment on #2565](https://github.com/alphagov/smart-answers/pull/2565#issuecomment-223492153) to say that all the changes look good.

**Pull request closed without merging**
