### PR TITLE
Marriage abroad - Create one outcome per path for Moldova

### PR DESCRIPTION
**Pull request by mgrassotti**
In order to simplify the maintenance of marriage abroad smart answers, we are going to create one outcome per path for Moldova.

Trello: https://trello.com/c/Reg7JGI9/666-3-marriage-abroad-create-one-outcome-per-path-for-moldova

### CODE REVIEW

**Comment by mgrassotti** [comment]
👍 this looks fine to me LGTM

**Comment by mgrassotti** [comment]
👍 @ikennaokpala I did some changes let me know if that could be ok now

**Comment by ikennaokpala** [comment]
This is looking better..
- I noticed that commit summary/title (2da32d7) are running over the 50 character limit. See style guide [here](https://github.com/alphagov/styleguides/blob/master/git.md#structure).
- I would  the title for (566e372).. suggest that templates are created.. no indication of enabling moldova as an outcome per path country.

**Comment by mgrassotti** [comment]
@ikennaokpala 👍 I tried to improve the commit messages

**Comment by ikennaokpala** [comment]
I just run the regression tests [1] against your branch and realised that Moldova has no regression artefacts in the first place.. You need to create the artefacts as the first commit.. because the artefacts will serve as a source of validation that the changes from this commit has not affected the content for getting married in Moldova.

[1] RUN_REGRESSION_TESTS=marriage-abroad test/regression/smart_answers_regression_test.rb

**Comment by mgrassotti** [comment]
👍 we did this pairing, thanks for your help

**Comment by mgrassotti** [comment]
@ikennaokpala now I ran regression tests on my machine and updated the commits to fix the errors. Let me know if that could be ok. Thanks

**Comment by ikennaokpala** [comment]
@mgrassotti Cheers for the updates..  I have had a look and I think we need to pair on this tomorrow

**Pull request merged**
