### PR TITLE
Update register_a_birth.govspeak.erb

### PR DESCRIPTION
**Pull request by AmyLaurence**
Added section for HM Armed Forces abroad.

### CODE REVIEW

**Comment by benthorner** [comment]
Hi @AmyLaurence. Do we still need this PR, or can we close it?

**Comment by AmyLaurence** [comment]
Hi Ben,

I need that one still. Can you tell me why I can't see it in Heroku?

Thanks,

Amy

**Comment by benthorner** [comment]
Thanks for replying @AmyLaurence! We usually try to merge PRs in quickly, so that the outstanding changes to the repo are clearer. Since this one has been around for quite a while, I think the Heroku preview app for it has been rotated-out (they're prioritised for more recent PRs). Since this has test failures and code conflicts, it'll be easier to close this one and start a new one.

**Comment by AmyLaurence** [comment]
Oh, this is annoying. I keep having to ask for the link again because it's
pinging between FCO and HO. Any change of keeping this one working for a
while - just until I can get sign off?

**Comment by benthorner** [comment]
@AmyLaurence I've had a quick look, and it seems like the live version of this has changed in a few ways. If you login to the GitHub interface and scroll to the bottom, you could try the 'Resolve conflicts' button yourself. I had a go, but the conflicts confused me, which is why it may be easier to start over.

**Comment by AmyLaurence** [comment]
I couldn't do it. It's groundhog day!!

**Comment by AmyLaurence** [comment]
Thanks @BenThorner - I didn't realise. You can get rid of this one.

**Pull request closed without merging**
