### PR TITLE
Add appointment links to overseas passports

### PR DESCRIPTION
**Pull request by erikse**
Pivotal Ticket: https://www.pivotaltracker.com/story/show/114558095

Kyrgyzstan, Tajikistan, Turkmenistan and Uzbekistan are all switching to allowing online booking of consular appointments.

## Fact check

https://smart-answers-pr-2329.herokuapp.com/overseas-passports

## Expected changes
 [URL on gov.uk](https://www.gov.uk/overseas-passports/y/kyrgyzstan/renewing_new/adult#making-your-application)
 * Remove content "You’ll need to book an appointment by email. Include your first name and last name and 3 alternative dates and times. You will receive an email confirming your appointment."
 * Remove embassy address
 * Remove embassy contact details
 * Add link to book appointment online

### Before
screen shot 2016-03-03 at 11 26 56 am

### After
screen shot 2016-03-03 at 11 27 27 am

Note: this PR supersedes #2329, and #2331

### CODE REVIEW

**Comment by erikse** [comment]
Marking as don't merge, with this changed is booked for deploy on 15 March 2016

**Comment by floehopper** [comment]
This looks good to me. Apologies for my over-enthusiastic commenting. :+1:

Is there any reason this PR has the "Don't merge" label on it?

**Comment by erikse** [comment]
The Don't merge label is to hold back merging it until closer to March 15 when it can be deployed. I can update the title/description to make this more noticeable.

**Comment by floehopper** [comment]
Cool. What do you think about creating a GitHub "Milestone" with that date and adding this PR to that?

**Comment by erikse** [comment]
Ok, I'll give it a go

**Comment by erikse** [comment]
This PR has been superseded by #2344

**Pull request closed without merging**
