### PR TITLE
Remove first sentence on the landing page for state-pension-through-partner

### PR DESCRIPTION
**Pull request by leenagupte**
Trello story: https://trello.com/c/zlSaZmkf/73-6-april-text-change-only-your-partner-s-national-insurance-record-and-your-state-pension

## Factcheck
[Your partner’s National Insurance record and your State Pension](https://smart-answers-pr-2422.herokuapp.com/state-pension-through-partner)

## Expected Changes
* [URL on GOV.UK](https://www.gov.uk/state-pension-through-partner)
    * Delete the first sentence on Your partner’s National Insurance record and your State Pension landing page

### Before

screen shot 2016-03-31 at 16 35 21

### After

screen shot 2016-03-31 at 16 36 02

### CODE REVIEW

**Comment by chrisroos** [comment]
Given that it's such a small change, I would've been inclined to make the change, update the regression test artefacts and update the checksums in a single commit (i.e. combine the first three commits in this branch).

I'd also move the fourth commit to a new branch as it's unrelated to the main changes in this PR. I realise the fourth commit only contains a very small change but I still think it's useful to keep branches as focussed as possible.

**Comment by leenagupte** [comment]
@chrisroos I've moved the documentation update into a separate PR: https://github.com/alphagov/smart-answers/pull/2435

**Comment by pmanrubia** [comment]
@leenagupte thank you for addressing @chrisroos suggestions.

**Comment by leenagupte** [comment]
Superseded by https://github.com/alphagov/smart-answers/pull/2432

**Pull request closed without merging**
