### PR TITLE
Refactor calculate-your-child-maintenance to new style flow

### PR DESCRIPTION
**Pull request by floehopper**
## Description

Similar to #2561, this moves the flow towards the style described in the [refactoring documentation][1]. I've concentrated on moving logic out of the flow and into the calculator and presentational concerns into the templates. The idea is to change all the flows to use this approach so we can significantly simplify the DSL.

There are still one `calculate` block and a bunch of `precalculate` blocks towards the end of the flow which are horribly tangled up with both calculation and presentational concerns. I couldn't see an easy way to untangle them while retaining the same rounding, number formatting, etc. My suspicion is that there is some unintentional behaviour in here, but at this stage I want to avoid getting sucked into needing any fact-checking for this PR.

I haven't really done any significant work on the calculator itself e.g. extracting domain concepts. Also I haven't made any significant changes to the tests - we'll still need to move them towards the [new-style approach][2] at some point.

## External changes

None. This is just an internal refactoring.

[1]: https://github.com/alphagov/smart-answers/blob/master/doc/refactoring.md
[2]: https://github.com/alphagov/smart-answers/blob/master/doc/new-style-testing.md

### CODE REVIEW

**Comment by chrisroos** [comment]
__Commit 3a578b5477a892024d8494ea8523be52f5aa8c79 ("Inline rate_type_formatted into outcome template")__

It wasn't immediately obvious to me why you were able to use `humanize` when inlining the `rate_type_formatted` precalculate block. Presumably none of the other values of `rate_type` will be changed by this method?

**Comment by chrisroos** [comment]
Aside from my single comment this all looks great to me, @floehopper!

**Comment by floehopper** [comment]
Improving commit comment based on feedback, rebasing against master, and force-pushing in preparation for merging.

**Comment by floehopper** [comment]
> It wasn't immediately obvious to me why you were able to use `humanize` when inlining the `rate_type_formatted` precalculate block. Presumably none of the other values of `rate_type` will be changed by this method?

I've expanded the commit note to explain my thinking here: cd118ace4062524e3dbed9153b9857387a4b91e2.

**Comment by chrisroos** [comment]
> I've expanded the commit note to explain my thinking here: cd118ac.

Awesome. Thanks, @floehopper.

**Pull request merged**
