### PR TITLE
Outcome Content changes for all opposite sex marriage in Bulgaria

### PR DESCRIPTION
**Pull request by ikennaokpala**
Trello story: https://trello.com/c/EpD6CVwE/74-marriage-abroad-bulgaria-march-2016-changes

Changes made in this PR affects marriage outcomes for all opposite sex couples
planing on getting married in Bulgaria. Under the following groups:

* UK Resident
* None UK Resident
* Third Country

### Expected changes

  * Content changes for opposite sex (UK Resident)

[UK Resident](https://smart-answers-pr-2414.herokuapp.com/marriage-abroad/y/bulgaria/uk/partner_british/opposite_sex)
[URL on GOV.UK](https://www.gov.uk/marriage-abroad/y/bulgaria/uk/partner_british/opposite_sex)

#### Before

screen shot 2016-03-30 at 13 27 09

#### After

screen shot 2016-03-30 at 13 27 02

### Expected changes

  * Content changes for opposite sex (UK Resident)
  
[None UK Resident](https://smart-answers-pr-2414.herokuapp.com/marriage-abroad/y/bulgaria/ceremony_country/partner_british/opposite_sex)
[URL on GOV.UK](https://www.gov.uk/marriage-abroad/y/bulgaria/ceremony_country/partner_british/opposite_sex)

#### Before

screen shot 2016-03-30 at 13 41 52

#### After

screen shot 2016-03-30 at 13 42 03

### Expected changes

  * Content changes for opposite sex (Third Country)

[Third Country](https://smart-answers-pr-2414.herokuapp.com/marriage-abroad/y/bulgaria/third_country/partner_other/opposite_sex)
[URL on GOV.UK](https://www.gov.uk/marriage-abroad/y/bulgaria/third_country/partner_other/opposite_sex)

#### Before
screen shot 2016-03-30 at 13 43 12

#### After
screen shot 2016-03-30 at 13 43 23

### CODE REVIEW

**Comment by floehopper** [comment]
Is this related to #2200?

**Comment by ikennaokpala** [comment]
@floehopper From the [trello card](https://trello.com/c/EpD6CVwE/74-marriage-abroad-bulgaria-march-2016-changes) I am led to believe that these are probably another set of changes for March 2016.. It is relationship with #2200 isn't clear

**Comment by chrisroos** [comment]
Hey @ikennaokpala. Why have you closed this branch? The associated Trello card looks as though it's still in fact check.

**Comment by ikennaokpala** [comment]
@chrisroos this PR is close because.. a totally new set of changes is expected and this is looking unlikely to go live.. I will move the card

**Comment by chrisroos** [comment]
That's good to know, thanks @ikennaokpala.

I wonder whether the new changes will also include this change. If they do, then I'd encourage us to make this live and not wait for the new changes. If they don't then I think it'd be interesting to understand why this change is no longer required. Are there things we can learn to avoid having to do unnecessary work in future?

**Comment by ikennaokpala** [comment]
@chrisroos I share your view as well..

**Pull request closed without merging**
