### PR TITLE
Refactor check-uk-visa

### PR DESCRIPTION
**Pull request by chrisroos**
This is in preparation for making a couple of minor changes to this Smart Answer.

There are quite a lot of commits but they're all fairly small so I'd hope it's not too painful to review.

In general I've tidied the flow, moved logic to the new `UkVisaCalculator` and split the `outcome_visit_waiver` outcome into three separate outcomes.

### CODE REVIEW

**Comment by floehopper** [comment]
Looks good to me.

**Comment by chrisroos** [comment]
I've re-worked this to get rid of the meta-programming. I'm closing this and will open a new pull request shortly.

**Comment by chrisroos** [comment]
I've edited this branch to remove the use of meta-programming.

**Comment by chrisroos** [comment]
I've rebased on master and force-pushed in preparation for merging.

**Pull request merged**
