### PR TITLE
DRY up marriage-abroad same-sex ceremony-not-possible outcomes

### PR DESCRIPTION
**Pull request by chrisroos**
I noticed that `outcome_same_sex_marriage_and_civil_partnership_in_other_countries` and `outcome_same_sex_marriage_and_civil_partnership_not_possible` were almost identical. The only difference was the use of "a same-sex relationship" versus "your same-sex relationship".

I've removed that duplication by standardising on "a same-sex relationship" and am opening this PR in the hope that I can get feedback from someone in the content team or department.

While capturing before/after screenshots for this PR I've realised that it might be better to standardise on "your same-sex relationship". There are some countries where same-sex relationships are legally recognised in some circumstances (e.g. in Russia when your partner is British) but not others (e.g. when your partner is Russian or from another country). In these cases, it feels more correct to say "your same-sex relationship". I'll leave that up to someone that knows better than me, though.

## Expected changes

* [Example URL - Same-sex ceremony in Russia with resident of Russia](https://www.gov.uk/marriage-abroad/y/russia/uk/partner_local/same_sex).

### Before

pr-2410-before

### After

pr-2410-after

### CODE REVIEW

**Comment by floehopper** [comment]
@chrisroos: Have you contacted anyone in the Content Team about this? I suspect you won't hear anything back about it unless you do.

**Comment by peternoble** [comment]
I’ll pick this up – I’ll reply on this thread tomorrow.

Peter

**Comment by chrisroos** [comment]
Great. Thanks, @peternoble.

**Comment by peternoble** [comment]
@chrisroos I've checked with FCO, and we agree that 'your same sex relationship' makes sense - there are countries where one relationship is recognised and another isn't. We'd like to check with the consular team though - do you need a response now? Is this holding anything up?

**Comment by chrisroos** [comment]
@peternoble: Thanks for checking with FCO. This isn't currently holding anything up so please feel free to check with the consular team.

**Comment by chrisroos** [comment]
@peternoble: Have you heard anything back from the consular team about this?

**Comment by chrisroos** [comment]
Hi @peternoble. Are we still hoping to get a response from the consular team about this? Or can we make the decision ourselves?

**Comment by sistephens** [comment]
I think we can just go for it , thanks @chrisroos.

**Comment by floehopper** [comment]
Since I saw that this has been given the go-ahead, I've taken the liberty of reviewing it.

Other than the change from "a same-sex relationship" to "your same-sex relationship", this looks good to me from a technical point of view.

**Comment by chrisroos** [comment]
Thanks for reviewing, @sistephens and @floehopper.

I'm going to close this PR while I rework the branch to use "your same-sex" instead of "a same-sex". I'll open a new PR when I'm ready.

**Pull request closed without merging**
