### PR TITLE
Remove regression test checksum file for part-year-profit-tax-credits flow

### PR DESCRIPTION
**Pull request by floehopper**
Remove unnecessary regression test checksum file.

This flow uses a newer style of testing and so doesn't have a regression test associated with it.

A flow [only has a regression test][1] if it has a `*-responses-and-expected-results.yml` file associated with it and this flow does not have such a file.

I believe this checksum file was accidentally added in [this commit][2].

### Expected changes

None

[1]: https://github.com/alphagov/smart-answers/blob/aabf580f3fbf53d6cdd4475380cb197d6dcacaea/lib/smart_answer_test_helper.rb#L10-L12
[2]: https://github.com/alphagov/smart-answers/commit/e757b611f3c1bae61ab26d9fdaf642ad0c0bb3c4

### CODE REVIEW

**Comment by erikse** [comment]
The commit link in the description is broken for me

**Comment by erikse** [comment]
Other than the broken link the description, seems ok

**Comment by floehopper** [comment]
@erikse: Thanks. I've just fixed the link.

**Comment by floehopper** [comment]
I'm about to rebase this against master and force-push in preparation for merging.

**Comment by floehopper** [comment]
No rebase needed. Merging.

**Pull request merged**
