### PR TITLE
Marriage abroad changes Japan

### PR DESCRIPTION
**Pull request by ikennaokpala**
Pivotal Tracker: https://www.pivotaltracker.com/projects/1270592/stories/112348951

* Changes affecting all opposite-sex marriage scenarios in Japan

## Factcheck
https://smart-answers-pr-112348951.herokuapp.com/marriage-abroad/y/japan/third_country/partner_other/opposite_sex

## Expected Changes
  [URL on Gov.UK](https://www.gov.uk/marriage-abroad/y/japan/third_country/partner_other/opposite_sex)
     * Changes that affect opposite-sex marriage scenarios in Japan

### Before
screen shot 2016-02-24 at 15 16 28

### After

screen shot 2016-02-24 at 15 16 08

### CODE REVIEW

**Comment by ikennaokpala** [comment]
Factcheck has come through from FCO

**Comment by floehopper** [comment]
Looks good to me :+1:

**Comment by floehopper** [comment]
I hope what I've suggested about combining commits makes sense. I know it feels a bit like re-writing history, but I think the key thing is to take advantage of the fact that the changes haven't yet been merged into `master` to curate the git history to make it as easy to follow as possible for our future selves.

**Comment by ikennaokpala** [comment]
@floehopper I understand your points and will get to it..

**Comment by ikennaokpala** [comment]
@floehopper yes it was intentional.. becuase it was a late update from google docs edit..

**Comment by floehopper** [comment]
All my most recent comments are very minor and I'd be happy for this to be merged, although ideally it would be nice to address the comments.

**Pull request merged**
