### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by chrisroos**
I'm updating the documentation to help developers new to the project get started. It covers a number of cards in our [Smart Answers Tasks Trello board](https://trello.com/b/7HgyU4hy/smart-answers-tasks).

### CODE REVIEW

**Comment by floehopper** [comment]
This all looks good to me. :+1:

**Comment by chrisroos** [comment]
OK, I think I'm done with documentation changes in this branch. Could you take another look when you have a minute please, @floehopper?

**Comment by floehopper** [comment]
Other than all my minor comments, this looks great to me.

**Comment by chrisroos** [comment]
I plan to address the feedback in this PR and get it merged tomorrow.

**Comment by chrisroos** [comment]
I'm happy that I've addressed all the feedback. I'm going to rebase on master locally and then manually merge to master.

**Pull request closed without merging**
