### PR TITLE
Same sex marriage in Italy

### PR DESCRIPTION
**Pull request by ikennaokpala**
Supersedes #2677 

[Trello card](https://trello.com/c/Eu4O452N/240-italy-marriage-tool-same-sex-marriage-unions-content-change-request)

## Motivation

With the recent legalisation of same sex marriage in Italy.

This PR shows the definition of and Content changes to the same sex marriage outcome for Italy.

This includes extraction of similar text from the opposite sex outcome to partials that have been shared with the same and opposite sex outcome for Italy.

## Factcheck 

[Preview link](https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/ceremony_country/partner_british/same_sex)
[GOV.UK](https://www.gov.uk/marriage-abroad/y/italy/ceremony_country/partner_british/same_sex)

### Expected changes

Replace `no same sex marriage` content with content to support legalisation of same sex marriage

### Before

screen shot 2016-08-05 at 11 11 18

### After

screen shot 2016-08-12 at 14 51 57

##### Affected outcomes

https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/ceremony_country/partner_british/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/ceremony_country/partner_local/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/ceremony_country/partner_other/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/third_country/partner_british/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/third_country/partner_local/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/third_country/partner_other/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/uk/partner_british/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/uk/partner_local/same_sex
https://smart-answers-pr-2677.herokuapp.com/marriage-abroad/y/italy/uk/partner_other/same_sex

### CODE REVIEW

**Comment by pmanrubia** [comment]
Following [the comments](https://github.com/alphagov/smart-answers/pull/2677#issuecomment-237884926) in #2677 

* The only difference between `_cni_at_local_register_office.govspeak` and `_cni_at_local_register_office_in_italy` is one word:
'marriage' or 'civil partnership’.

Would it be possible to use the same helper function in _cni_at_local_register_office.govspeak?:

```ruby
<%= calculator.partner_is_opposite_sex? ? 'marriage' : 'civil partnership' %>
```
* Template `_legalisation_and_translation_italy`. 
Could you please talk to a content designer and check this copy can be accommodated to another template? 

* Template: `_supporting_documents_italy`
This could be a good opportunity of reusing content from other countries. Could you please discuss it with a content designer?

Could you please talk to a designer and write down your conclusions? If it is not possible to reuse content from other countries, it is important to write it down to prevent other developers from trying to do the same work twice.

**Comment by pmanrubia** [comment]
I would prefer having atomics commit. Could you please swap commits 773795a29a932f6b0e79504b02579e6dd12bf3a1 and 773795a29a932f6b0e79504b02579e6dd12bf3a1 and update the regression tests in each commit?

**Comment by ikennaokpala** [comment]
@pmanrubia 

>Template _legalisation_and_translation_italy. 
> Could you please talk to a content designer and check this copy can be accommodated to another template?

>Template: _supporting_documents_italy
>This could be a good opportunity of reusing content from other countries. Could you please discuss it with a content designer?

Yes a helper function would suffice.. 

> The only difference between _cni_at_local_register_office.govspeak and _cni_at_local_register_office_in_italy is one word: 'marriage' or 'civil partnership’.
> Would it be possible to use the same helper function in _cni_at_local_register_office.govspeak?:

Will talk with the @amylaurence and @sistephens about 

> I would prefer having atomics commit. Could you please swap commits 773795a and 773795a and update the regression tests in each commit?

Not sure will commits you are refering to.. will catch up with you on Monday for more insight..

Thanks

**Comment by ikennaokpala** [comment]
@pablomanrubia 
I have had a brief chat with @amylaurence2 and she feel no change is required to be made, becuase the italian scenarios appears unique and with thier choice of phrases/words example marriage for opposite sex vs civil partnership for same sex.

the helper method has been implemented with tests and ready for review.

**Comment by pmanrubia** [comment]
Ikenna, in order to have atomics commits (all tests passing in each commit), could you please remove last commit (artefacts regeneration of the last commit) and include the artefacts in 30a740c and d47ce21. 
It is also consistent with having already included the checksums.

**Comment by ikennaokpala** [comment]
@pmanrubia 

As a result, of the addition of the consular fees table options for ceremony and
third country, on running the regression tests no changes were recorded.

This is because the changes will only affect same sex marriages and not opposite
 sex.

On applying the created Italian partials and text from the document.

I ran the regresstion tests and at this point, apparent changes merged and recorded.

**Comment by pmanrubia** [comment]
LGTM

**Comment by ikennaokpala** [comment]
@pmanrubia thanks for reviewing.. waiting for @amylaurence for the 👍  up

**Pull request merged**
