### PR TITLE
Landlord immigration check amends

### PR DESCRIPTION
**Pull request by erikse**
This PR supersedes #2210, #2212, #2213, #2214 and #2224

The landlord immigration check pilot now rolls out to England wide, requiring landlords to perform checks on tenancies start on or after Feb 1, 2016, as well as the existing requirement for checks to be performed inside the pilot Boroughs and Councils since 2014.

## Fact check
https://afternoon-citadel-5721.herokuapp.com/landlord-immigration-check/y

## Expected changes
 * [URL on gov.uk](https://www.gov.uk/landlord-immigration-check)
  * New content allowing tenancy checks after Feb 1, 2016 for all of England, e.g. "You can only do this check for tenancies which start on or after 1 February 2016."

### Before
screen shot 2015-12-22 at 11 32 42 am

### After
screen shot 2015-12-22 at 11 32 52 am

### CODE REVIEW

**Comment by keithiopia** [comment]
@erikse Home Office have just said this is all good to merge and deploy on Monday!

**Comment by erikse** [comment]
@keithiopia that's great, we just need a code review and good to go!

**Comment by tadast** [comment]
Some rebasing/squashing could make history easier to follow, but generally it LGTM

**Comment by erikse** [comment]
Well, the partials were created by Keith, I wanted him to retain this contributions in the project history, otherwise I would probably add the partials as I was using them. 

What do you reckon, squash and overwrite authorship or leave as?

**Comment by erikse** [comment]
I've just rebased this with the master branch and forced pushed to the branch of this PR

**Comment by keithiopia** [comment]
I can live with having no contributions!

**Comment by erikse** [comment]
I've just squashed the commits adding the partials into the commit using them

**Comment by tadast** [comment]
:shipit:

**Pull request merged**
