### PR TITLE
Add a developer checklist to the docs

### PR DESCRIPTION
**Pull request by leenagupte**
This checklist is something that new developers on the team can refer when
they are first becoming familiar with the code base and structure of the tests.

### CODE REVIEW

**Comment by pmanrubia** [comment]
I would [update this document](https://github.com/alphagov/smart-answers/blob/master/doc/regression-tests.md) with your checklist. It feels to me like a better place as the checklist is focused in regression tests. 
When it comes to the title, could you think on something more concrete than `checklist`? Something like: `Steps to update the tests after a change`?

**Comment by leenagupte** [comment]
@pmanrubia Thanks for the suggestion, I'll do that.

**Comment by leenagupte** [comment]
@pmanrubia I've updated the regression tests doc as suggested.

**Comment by pmanrubia** [comment]
LGTM 👍

**Pull request merged**
