### PR TITLE
Marriage abroad japan amends

### PR DESCRIPTION
**Pull request by erikse**
PT story: https://www.pivotaltracker.com/story/show/109438952

This PR updates the outcome for marriage abroad in Japan for opposite sex couples. 

As well as small content change in wording, it changes the outcome so that marriages with a local or British partner, now show the same content.

## Fact check

https://enigmatic-wave-6182.herokuapp.com/marriage-abroad/y/japan

## Expected changes
 *[URL on gov.uk](https://www.gov.uk/marriage-abroad/y/japan/ceremony_country/partner_local/opposite_sex)
  * Under "What happens next", the first sentence changes from ending with "your notice of marriage" to "the completed affirmation/affidavit".

### Before
screen shot 2015-12-21 at 10 25 32 am

### After
screen shot 2015-12-21 at 10 25 42 am

 * [URL on gov.uk](https://www.gov.uk/marriage-abroad/y/japan/uk/partner_british/opposite_sex)
  * Under "What you need to do", the content changes so it's inline with the content of partner local

### Before
screen shot 2015-12-21 at 10 30 11 am

### After
screen shot 2015-12-21 at 10 30 16 am

### CODE REVIEW

**Comment by erikse** [comment]
I've just rebased this with master and force pushed back to this PR's branch

**Comment by erikse** [comment]
I've just rebased this with the master branch and forced pushed to this PR's branch

**Comment by erikse** [comment]
I've just rebased this with the master branched and force pushed back to the branch of this PR

**Comment by erikse** [comment]
I've just rebased this with the master branched and force pushed back to the branch of this PR

**Comment by tadast** [comment]
Looks flawless :+1:

**Comment by erikse** [comment]
I'll just rebase before merging

**Pull request merged**
