### PR TITLE
Amendments to Simplified expenses checker tool

### PR DESCRIPTION
**Pull request by ikennaokpala**
[Trello card](https://trello.com/c/8Hgtl17t/280-8-updates-for-simplified-expenses-smart-answer)

## Motivation

Prior to this change request, business owners were unable properly claim the right amounts on simplified expenses from usage of capital equipments like cars, vans and motorbikes. 

The simplified expenses checker was limited with the options provided, loosely graded emissions levels and the wrongly used context of existing versus new business to estimate claims.

Here in this PR, logic changes have been introduced to cater for the aforementioned gaps.

## Factcheck
- [Preview link](https://smart-answers-pr-2900.herokuapp.com/simplified-expenses-checker/y)
- [GOV.UK](https://www.gov.uk/simplified-expenses-checker/y)

## Expected changes

- Removal of former question 1
- Reordering of questions 
- Logic changes to question 2
- Split "yes" decision in question 3 (are you buying a new car?) into "new" and "used" options
- Change question 6 (is the car you're buying green?) to ask about the car's emissions
- Update logic in "calculating expenses the usual way" for vehicles with high emissions
- Logic changes to question 5
- Save input as expenses_or_allowances and vehicle_status
- Making logic changes to question 5
- Pre-define vehicle_status and vehicle_is_green
- Replacement of the YES/No option with emission grades
  (i.e low, medium and high)
- Add filthy_vehicle_write_off to list of deductions under
  "calculating expenses the usual way"
- Include filthy_vehicle_write_off in calculation of current_scheme_costs
- Made logic changes as well as introduced new calculate blocks
- Pre-define vehicle_status and vehicle_is_green
- Updated the question title
- Several content update across question and outcomes

### Before

screen shot 2017-01-30 at 00 45 54

### After

screen shot 2017-01-30 at 11 35 11

### CODE REVIEW

**Comment by leenagupte** [comment]
In commit 407bbc6 shouldn't `motorcycle` to be changed to `motorbike` in the outcome text as well?

**Comment by ikennaokpala** [comment]
@leenagupte Good point I will ask he Content team

**Comment by leenagupte** [comment]
In commit 2d5277c45e1b4e617317975ddf9709debef76396, the questions and responses need to be regenerated so that the correct test artefacts are updated. I would only expect to see changes in the test artefacts for `used` vehicles.

**Comment by ikennaokpala** [comment]
No superseded by #2944

**Pull request closed without merging**
