### PR TITLE
Same and Opposite sex Marriage outcome changes in Dominican Republic 

### PR DESCRIPTION
**Pull request by ikennaokpala**
Pivotal Tracker: https://www.pivotaltracker.com/projects/1270592/stories/109437774

* Replace contact details with appointment booking link same sex marriage.
* Content Updates for Same sex outcomes
* Changes to the fees table for Dominican Republic
* Change to UK residents getting married in the Dominican Republic

## Factcheck

[Dominican Republic Factcheck](https://smart-answers-pr-2406.herokuapp.com/marriage-abroad/y/dominican-republic)

## Expected Changes

* Fact Check for [Replace contact details with appointment booking link same sex marriage.](https://smart-answers-pr-2406.herokuapp.com/marriage-abroad/y/dominican-republic/ceremony_country/partner_local/same_sex)

* [URL on GOV.UK](https://www.gov.uk/marriage-abroad/y/dominican-republic/ceremony_country/partner_local/same_sex)

### Before

screen shot 2016-03-24 at 14 41 12

### After

screen shot 2016-03-24 at 14 41 28

* Fact Check for [Content Updates for Same sex outcomes](https://smart-answers-pr-2406.herokuapp.com/marriage-abroad/y/dominican-republic/ceremony_country/partner_local/same_sex)

* [URL on GOV.UK](https://www.gov.uk/marriage-abroad/y/dominican-republic/ceremony_country/partner_local/same_sex)

### Before

screen shot 2016-03-24 at 14 48 00

### After

screen shot 2016-03-24 at 14 47 37

* Fact Check for [Changes to the fees table for Dominican Republic](https://smart-answers-pr-2406.herokuapp.com/marriage-abroad/y/dominican-republic/ceremony_country/partner_local/same_sex)
* [URL on GOV.UK](https://www.gov.uk/marriage-abroad/y/dominican-republic/ceremony_country/partner_local/same_sex)

### Before

screen shot 2016-03-24 at 14 48 00

### After

screen shot 2016-03-24 at 14 51 32

* Fact Check for [Change to UK residents getting married in the Dominican Republic](https://smart-answers-pr-2406.herokuapp.com/marriage-abroad/y/dominican-republic/uk/partner_local/opposite_sex)
* [URL on GOV.UK](https://www.gov.uk/marriage-abroad/y/dominican-republic/uk/partner_local/opposite_sex)

### Before

screen shot 2016-03-24 at 15 03 52

### After

screen shot 2016-03-24 at 15 04 16

### CODE REVIEW

**Comment by ikennaokpala** [comment]
This PR supersedes  #2287

**Comment by floehopper** [comment]
Currently you have the following commits:

  1. Responses and expected results (Dominica Rep)
  2. Generate regression test artefacts (Marriage abroad)
  3. Regenerate checksum data (Marriage abroad)
  4. Define Marriage outcomes for Dominican Republic
  5. Regenerate regression test artefacts (Marriage abroad)
  6. Regenerate checksum data (Marriage abroad)

This is what I would do differently:

  * Minor: I would prefer it if commits 1, 2 & 3 were combined into a single commit labelled something like "Add Dominican Republic path to regression test for Marriage Abroad".
  * More important: I would prefer if commit 4 was split multiple commits as follows:
    1. A commit in which the country-specific outcome is introduced, but **no changes to the artefacts are needed to pass the regression tests**. The checksums could therefore also be updated in this commit.
    2. One or more subsequent commits which make any necessary changes to the country-specific outcome.

I hope that all makes sense. I realise you're under time pressure for this, so I'm sorry to be suggesting more changes. I guess I'm still nervous about the size of the change in commit 4 i.e. a whole load of code has appeared seemingly from nowhere, so it's hard for me to say it's ok - especially given the size of commit 5.

**Comment by ikennaokpala** [comment]
I have fixup the previous commits 1,2,3

**Comment by floehopper** [comment]
Cool. This is definitely better than #2287 from the point of view that you've generated the regression test artefacts for the Dominican Republic *before* making any changes. This makes it easier to see what's actually changed.

Given that you're under deadline pressure for this, I'm happy for it to be merged.

**Pull request merged**
