### PR TITLE
Split required document list by area for Landlord Immigration Check

### PR DESCRIPTION
**Pull request by erikse**
PT story: https://www.pivotaltracker.com/story/show/110973118

Adds new partials showing acceptable documents that a prospective tenant has to show a landlord for properties in the pilot area, and in England (non-pilot) area. 

## Fact check

https://mighty-beach-3538.herokuapp.com/landlord-immigration-check

## Expected changes
 * [URL on gov.uk](https://www.gov.uk/landlord-immigration-check/y/B5%204RU/yes/yes/no/no/no/somewhere_else)
  * The page heading changes to "Does the person have 2 of the following:"
  * The listed documents under the pilot and non-pilot area change

### Before
screen shot 2016-01-11 at 2 11 51 pm

### After
screen shot 2016-01-11 at 2 11 58 pm

This PR supersedes #2229, #2230 and #2231.

### CODE REVIEW

**Comment by keithiopia** [comment]
@erikse Can we just merge /landlord-immigration-check/landlord_immigration_check.govspeak.erb?
The other changes have now been superseded.

**Comment by erikse** [comment]
Yep, so you only want this [commit](https://github.com/alphagov/smart-answers/commit/2aa908c8dca4df88b749c586535051844644e98b) ?

**Comment by keithiopia** [comment]
Yep.

**Comment by erikse** [comment]
This PR has been replaced by #2252

**Pull request closed without merging**
