### PR TITLE
Germany and Morocco marriage abroad amends

### PR DESCRIPTION
**Pull request by erikse**
The latest set of change requested by FCO content designer for marriage abroad in Germany and Morocco outcomes.

Expected changes:
 * [Marriage in Germany](https://www.gov.uk/marriage-abroad/y/germany/uk/partner_british/opposite_sex#result-title) should now include that couples need to contact the registry office or the church where they intend to marry.

screen shot 2015-12-03 at 17 57 12

* [Marriage in Morocco](https://www.gov.uk/marriage-abroad/y/morocco/ceremony_country/partner_british/opposite_sex#what-you-need-to-do) will state you need to bring your partner's passport, under what you need to do.

screen shot 2015-12-03 at 17 58 38

### CODE REVIEW

**Comment by erikse** [comment]
Just rebased this with master and force pushed

**Comment by erikse** [comment]
I've just rebased this with the master branch and forced pushed back to this PR's branch

**Comment by erikse** [comment]
I've just rebased this with the master branch and forced pushed back to this PR's branch

**Comment by erikse** [comment]
I've just rebased this with the master branch and force pushed to the branch of this PR

**Comment by erikse** [comment]
I've just rebased this with the master branch and forced pushed back to the branch of this PR

**Comment by tadast** [comment]
LGTM

**Comment by erikse** [comment]
Have updated the 2nd commit message, rebased with the master branch and forced pushed back to the branch of this PR

**Pull request merged**
