### PR TITLE
Update artefacts for marriage-abroad

### PR DESCRIPTION
**Pull request by pmanrubia**
Complements https://github.com/alphagov/smart-answers/pull/2516, by including missing artefacts for marriage-abroad in: https://github.com/alphagov/smart-answers/pull/2516/commits/dfe3298ea55cc0d462f624f90ee92bf270e0542a
See [comment](https://github.com/alphagov/smart-answers/pull/2516#issuecomment-221726904) from @floehopper.

### CODE REVIEW

**Comment by floehopper** [comment]
As a general rule, I think we should be trying to explain any changes to the regression test artefacts in the relevant commit note. This will help someone reviewing the PR understand whether the changes are all expected changes. Otherwise I think there's a danger we just run the tests and accept all of the changes without really looking at them. I note that there is no explanation in either the [original commit][1] or [the commit in this PR][2].

[1]: dfe3298ea55cc0d462f624f90ee92bf270e0542a
[2]: 06dd399ec3910f15839c3c84e67f555c3934a20f

**Comment by pmanrubia** [comment]
I am not sure if I am getting you correctly. If the changes are small enough I can't see a big benefit in describing the changes in the commit notes. And if they are big then we would need to split them so they are easy to follow.  Could you post an example so I understand you better?

**Comment by floehopper** [comment]
I think the important thing is not to describe the changes, but to explain how you have satisfied yourself that they are all changes that you were expecting because of changes you have made to the flow and/or its templates. I'm not sure I'm explaining myself very well.

Given that we need to fix the build, as long as you are happy that the changes to the artefacts are as you expect then I think it's fine to merge this.

**Comment by pmanrubia** [comment]
Thank you @floehopper for the clarification; I have understood you and you have a point in what you suggest, it will simplify and will add security to our reviews. I will try to follow a similar approach in incoming PRs.

**Pull request merged**
