### PR TITLE
Updated list of sponsoring establishments

### PR DESCRIPTION
**Pull request by johnploughman**
Updated the list to include new entries, and change existing entries from online to print and send applications.

Zendesk: https://govuk.zendesk.com/agent/tickets/1213457
Pivotal: https://www.pivotaltracker.com/story/show/111515402

### CODE REVIEW

**Comment by erikse** [comment]
The diff isn't showing..

**Comment by keithiopia** [comment]
@erikse Does the diff not show when there's a large number of changes? It was quicker to paste in the full list - otherwise John would have had to have gone through them all and pick out the changes.

**Comment by erikse** [comment]
The current file has 3007 lines, and this PR will remove 3001 of the existing lines, and add 3032 new ones - did we really change that many?

**Comment by keithiopia** [comment]
It was a complete swap. They sent us a spreadsheet that didn't indicate which ones lines were new sponsors were etc.

**Comment by erikse** [comment]
Ok, if we can get a CVS dump from that spreadsheet, we can update the existing values with a script in a new PR.

**Comment by erikse** [comment]
This PR has been superseded by #2243

**Pull request closed without merging**
