### PR TITLE
Change to appointment procedure (Opposite sex El Salvador)

### PR DESCRIPTION
**Pull request by ikennaokpala**
Pivotal Tracker: https://www.pivotaltracker.com/projects/1270592/stories/109438210

* Change to appointment procedure (Opposite sex El Salvador) by Content team

## Factcheck
https://smart-answers-pr-2300.herokuapp.com/marriage-abroad/y/el-salvador/ceremony_country/partner_local/opposite_sex
or 
https://smart-answers-pr-109438210.herokuapp.com/marriage-abroad/y/el-salvador/ceremony_country/partner_local/opposite_sex

## Expected Changes
[URL on GOV.UK](https://www.gov.uk/marriage-abroad/y/el-salvador/ceremony_country/partner_local/opposite_sex)
     * Replace appointment procedure with new one for opposite sex marraige in El Salvador by Content team 

### Before
screen shot 2016-03-31 at 14 42 49

### After
screen shot 2016-03-31 at 14 42 57

### CODE REVIEW

**Comment by chrisroos** [comment]
This looks good to me.

It makes me ever so slightly nervous that no tests have changed (regression or otherwise) but I think the screenshots probably give enough confidence given how small the change is.

**Comment by ikennaokpala** [comment]
@chrisroos yeah I feel the same..

**Comment by floehopper** [comment]
This branch is really quite old now (~1 month). It's really not ideal that we have branches like this hanging around for so long, although I know it's because we're waiting for fact-checking.

Anyway, it might be worth chasing up the fact-check and, in the meantime, it would definitely  be worth rebasing it against master and resolving the conflicts reported by GitHub (see above). It's worth keeping old branches up-to-date regularly to reduce the pain when you come to merge it.

**Comment by ikennaokpala** [comment]
@floehopper Cheers for the heads up on this PR.. At the moment it is now in sync with master

**Comment by chrisroos** [comment]
I've added a comment on the PT story to ask whether we're still hoping to hear back from FCO about this change.

**Comment by ikennaokpala** [comment]
@chrisroos thanks.. i am chasing them as well

**Comment by chrisroos** [comment]
Hey @ikennaokpala. Why has this PR been closed?

**Comment by ikennaokpala** [comment]
@chrisroos this PR is close because.. a totally new set of changes is expected and this is looking unlikely to go live

**Comment by chrisroos** [comment]
That's good to know, thanks @ikennaokpala.

I wonder whether the new changes will also include this change. If they do, then I'd encourage us to make this live and not wait for the new changes. If they don't then I think it'd be interesting to understand why this change is no longer required. Are there things we can learn to avoid having to do unnecessary work in future?

**Comment by ikennaokpala** [comment]
@chrisroos I share your view as well..

**Pull request closed without merging**
