### PR TITLE
Update register-a-birth oru_result outcome

### PR DESCRIPTION
**Pull request by chrisroos**
PT story: https://www.pivotaltracker.com/story/show/108010578

## Fact check

* [Example change to Afghanistan outcome](https://smart-answers-pr-2101.herokuapp.com/register-a-birth/y/afghanistan/mother_and_father/yes/same_country#check-your-documents)

This branch affects outcomes for the following countries:

* afghanistan
* algeria
* libya
* morocco
* north-korea
* papua-new-guinea
* philippines
* sierra-leone
* st-martin
* timor-leste
* usa
* venezuela

## Expected observable changes

* [Example URL](https://www.gov.uk/register-a-birth/y/afghanistan/mother_and_father/yes/same_country#check-your-documents)

### Before

pr-2101-before-a

pr-2101-before-b

### After

pr-2101-after-a

pr-2101-after-b

### CODE REVIEW

**Comment by floehopper** [comment]
Other than my minor comments, this looks good to me.

**Comment by chrisroos** [comment]
I've updated this branch based on @floehopper's feedback.

**Comment by chrisroos** [comment]
These test failures are to do with the problem fixed in PR #2107. I've scheduled another build on Jenkins.

**Comment by chrisroos** [comment]
I've rebased this on master and force pushed to avoid it from getting too out of date.

**Comment by chrisroos** [comment]
I've made a minor change to oru_result.govspeak.erb based on feedback from FCO. I've also rebased on master and force-pushed in preparation for merging.

**Pull request merged**
