### PR TITLE
Replace appointment booking link (Marriage abroad SUDAN)

### PR DESCRIPTION
**Pull request by ikennaokpala**
PT Story: https://www.pivotaltracker.com/projects/1270592/stories/109439186
Trello Story: https://trello.com/c/YaDRvSFu/32-marriage-abroad-sudan

* Replace the appointment booking link with Embassy address details

## Factcheck
https://smart-answers-pr-109439186.herokuapp.com/marriage-abroad
https://smart-answers-pr-109439186.herokuapp.com/marriage-abroad/y/sudan/ceremony_country/partner_local/opposite_sex

### Expected changes
*  [URL on GOV.UK](//gov.uk/marriage-abroad/y/sudan/ceremony_country/partner_local/opposite_sex)

### Before

screen shot 2016-03-02 at 11 53 33

### After
 
screen shot 2016-03-02 at 11 53 44

### CODE REVIEW

**Comment by pmanrubia** [comment]
If we have fully migrated to Trello, it might be useful to add a link to the Trello card, so we have both links (PT and Trello)?

**Comment by ikennaokpala** [comment]
@pmanrubia  I have added the trello link for this PR

**Comment by pmanrubia** [comment]
@ikennaokpala Any reason why there are no update `artefacts`?

**Comment by ikennaokpala** [comment]
@pmanrubia that is becuase Sudan is not included in this test data file.. test/data/marriage-abroad-questions-and-responses.yml

**Comment by pmanrubia** [comment]
@ikennaokpala I guess I might be missing something.
I will hand over the PR to @erikse as I would still expect to see the artefact update as the outcome is being modified. My understanding is that the `questions-and-responses` file would need to be amended manually in case Sudan is not there.

**Comment by erikse** [comment]
@pmanrubia please see the following https://github.com/alphagov/smart-answers/pull/2200#issuecomment-199122150 for discussion on this, at the moment, it's kind of undefined when we add a country, and looking at the responses file, there are only 104 entries covering about half of the countries available in question one

**Comment by floehopper** [comment]
@pmanrubia: When @chrisroos & I originally added the regression tests, we added responses to the `questions-and-responses` file until we had the minimum set that exercised all the paths through the code using a coverage tool (see [adding-new-regression-tests docs][1]).

Since we converted from using phrase lists and YAML files (don't ask!) to using ERB templates, I think using a coverage tool might be hard, because I don't think they support ERB templates.

If new "logic paths" have been added then in the short term it would probably be sensible to make the relevant additions to `questions-and-responses`. However, I'd be wary of adding them just to see content changes.

In the long run we want to replace the regression tests with unit tests and integration tests. `part-year-profit-tax-credits` was a new flow that was written with no regression tests. However, that flow isn't particularly content-heavy and it's not entirely clear to me what we'd ideally want to do with a content-heavy flow like `marriage-abroad`. However, I doubt that having brittle tests around the exact content are going to be the answer.

Sorry - that was a bit of a ramble, but hopefully some of it helps explain things.

[1]: https://github.com/alphagov/smart-answers/blob/master/doc/adding-new-regression-tests.md

**Comment by pmanrubia** [comment]
Sure it does. Thank you @ikennaokpala, @erikse and @floehopper for the clarifications.

LGTM @ikennaokpala

**Pull request merged**
