### PR TITLE
Content changes to check-uk-visa

### PR DESCRIPTION
**Pull request by ikennaokpala**
Pivotal Tracker: https://www.pivotaltracker.com/projects/1270592/stories/113993127

* Content change to question 1& 3 (check uk visa)

## Expected Changes

* Changes made to the wording of a question 1 and question 3 in the check uk visa smart answer. These are only content changes and doesn't affect any logic or smart flow.

NB: 

This PR is now dependent on [render-questions-as-govspeak](https://github.com/alphagov/smart-answers/pull/2338)

The factcheck preview is built on a [separate branch](https://github.com/alphagov/smart-answers/tree/check-uk-visa-heroku) that is contains commits from [render-questions-as-govspeak](https://github.com/alphagov/smart-answers/pull/2338)

## Preview 1

[URL Preview](https://smart-answers-pr-113993127.herokuapp.com/check-uk-visa/y/)
[URL GOV.UK](https://gov.uk/check-uk-visa/y/)

   * Changes made to the wording of a question 1 in the check uk visa smart answer. 

### Before

screen shot 2016-03-02 at 15 01 07

### After

screen shot 2016-03-02 at 15 00 07

## Preview 2
[URL Preview](https://smart-answers-pr-113993127.herokuapp.com/check-uk-visa/y/afghanistan/transit)
[URL GOV.UK](https://gov.uk/check-uk-visa/y/afghanistan/transit)

   * Changes made to the wording of a question 3 in the check uk visa smart answer. 

### Before

screen shot 2016-03-02 at 15 00 56

### After

screen shot 2016-03-02 at 15 00 19

### CODE REVIEW

**Comment by ikennaokpala** [comment]
@dsingleton Here is the PR with content team changes

**Comment by erikse** [comment]
@ikennaokpala we've reverted the Rails 4.2.5.2 upgrade for now, so this will need a rebase with master and to run the regression tests again as the JS and CSS assets should not have checksums in the file names.

**Comment by ikennaokpala** [comment]
@erikse  Ok will re-run the regression test again

**Comment by dsingleton** [comment]
Subject to the changes [discussed in #3217](https://github.com/alphagov/smart-answers/pull/2317#issuecomment-192355449) this change LGTM.

**Comment by erikse** [comment]
@ikennaokpala - I think it's it a little easier to understand the PR description when expected changes are separated - having the url, description of changes and the before and after image per change, as you have done for previous PRs

**Comment by ikennaokpala** [comment]
@erikse I have split the changes and preceded each with the preview, gov.uk links and description of the changes

**Comment by ikennaokpala** [comment]
This PR [render-questions-as-govspeak](https://github.com/alphagov/smart-answers/tree/render-questions-as-govspeak) has been merge.. Waiting on the factcheck on this PR to come through..

**Comment by chrisroos** [comment]
I've added a comment to the PT story to ask when we might be able to merge these changes.

**Comment by ikennaokpala** [comment]
@chrisroos thanks for doing that.. still chasing as well

**Comment by ikennaokpala** [comment]
Due to changes in the flow for question 3 this PR appears no longer relevant.. How question one can has been accepted and will be release separately. SEE [Trello Card](https://trello.com/c/u9YpSyLi/31-check-if-you-need-a-uk-visa-content-change-to-question-1) for more.

**Pull request closed without merging**
