### PR TITLE
Standardise conditions around draught proofing text

### PR DESCRIPTION
**Pull request by leenagupte**
Supersedes: https://github.com/alphagov/smart-answers/pull/2672

Trello card: https://trello.com/c/FJVXjW0E

## Motivation

Draught proofing can be displayed by four outcome templates.

Of those four, only one displays the text is Draught proofing hasn't been selected in the previous question.

In the other three outcomes, Mains gas has to not have been selected (deselected) as well.

So this link will show draught proofing: https://www.gov.uk/energy-grants-calculator/y/all_help/benefits,permission/1954-01-01/none/1940s-1984/flat/top_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,modern_boiler,modern_double_glazing,solid_wall_insulation

but this one will not: https://www.gov.uk/energy-grants-calculator/y/all_help/benefits,permission/1954-01-01/none/1940s-1984/flat/top_floor/cavity_wall_insulation,electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation

To be consistent, and as there is a clear majority, I have changed the one outlying outcome to match the others.

## Factcheck

Will be added to final PR created on the feature branch.

## Expected Changes

[URL on GOV.UK](https://www.gov.uk/energy-grants-calculator/y/help_energy_efficiency/permission/before-1940/house/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation)

[Heroku Preview](https://smart-answers-pr-2672.herokuapp.com/energy-grants-calculator/y/help_energy_efficiency/permission/before-1940/house/electric_heating,loft_attic_conversion,loft_insulation,mains_gas,modern_boiler,modern_double_glazing,solid_wall_insulation)
* Only show "draught proofing" bullet if both "main gas" and "draught proofing" are selected in the previous question.

### Before

screen shot 2016-07-29 at 11 03 53

screen shot 2016-07-29 at 11 04 27

### After

screen shot 2016-07-29 at 11 07 12

screen shot 2016-07-29 at 11 08 04

### CODE REVIEW

**Comment by leenagupte** [comment]
Test artefacts where created in PR https://github.com/alphagov/smart-answers/pull/2672

See discussion about why they were removed:

https://github.com/alphagov/smart-answers/pull/2672#issuecomment-237226743
https://github.com/alphagov/smart-answers/pull/2672#issuecomment-238200349
https://github.com/alphagov/smart-answers/pull/2672#issuecomment-238205175

**Comment by leenagupte** [comment]
@pmanrubia I have closed the previous PR, and opened this one (without the test artefacts) against master.

**Comment by pmanrubia** [comment]
Thank you @leenagupte

**Comment by leenagupte** [comment]
Superseeded by #2734

**Pull request closed without merging**
