### PR TITLE
Replace appointment booking link (Marriage abroad Moldova)

### PR DESCRIPTION
**Pull request by ikennaokpala**
PT Story: https://www.pivotaltracker.com/projects/1270592/stories/109439130

* Replace the appointment booking link with Embassy address details

## Factcheck
https://smart-answers-pr-109439130.herokuapp.com/marriage-abroad
https://smart-answers-pr-109439130.herokuapp.com/marriage-abroad/y/moldova/ceremony_country/partner_local/opposite_sex

### Expected changes
*  [URL on GOV.UK](//gov.uk/marriage-abroad/y/moldova/ceremony_country/partner_local/opposite_sex)

### Before

screen shot 2016-03-02 at 11 51 45

### After
 
screen shot 2016-03-14 at 12 15 02

### CODE REVIEW

**Comment by floehopper** [comment]
Note that [CI build #4238][1] for this branch was hanging so I cancelled it and manually triggered a new build.

[1]:https://ci.dev.publishing.service.gov.uk/job/govuk_smartanswers_branches/4238/

**Comment by ikennaokpala** [comment]
@floehopper thanks for rebuilding the branch.

**Comment by erikse** [comment]
It would be good if we could use correct capitalisation for country names in PR titles, descriptions as well as git commit notes.

Also, some of the commit notes wrap when I view them in github, which might be an indicator they are going over 72 characters in length.

**Comment by ikennaokpala** [comment]
@erikse will looking that

**Comment by ikennaokpala** [comment]
@erikse I have squashed this and rebased with master

**Comment by erikse** [comment]
Thanks for amending @ikennaokpala looks good to merge

**Pull request merged**
