### PR TITLE
Quick improvements to views: Remove unused partials and improve folder structure

### PR DESCRIPTION
**Pull request by selfthinker**
[Trello card](https://trello.com/c/yszihFOa/221-easy-frontend-fixes-and-cleanup)

While looking at the code I identified some quick things to improve.
I **removed 3 partials** which don't seem to be used. I searched the code base for them and couldn't find any reference. I found only a 100% [proof for `optional_date_question`](https://github.com/alphagov/smart-answers/commit/6275d7689549de9763c3b2ff2987555f525f3687). Although I found [where `country_question` and `text_question` were removed](https://github.com/alphagov/smart-answers/pull/2050), it was difficult to find evidence for their substitutes.
I also **improved the folder structure of the views** by moving all question types into their own folder.

## Expected change

Nothing visible/noticeable for the user. I ran the regression tests and they passed.

### CODE REVIEW

**Comment by floehopper** [comment]
> Although I found where country_question and text_question were removed, it was difficult to find evidence for their substitutes.

Well done for tracking things down in the git history.

That PR (#2035) removed all Smartdown related functionality. The motivations behind the removal of Smartdown are documented in [ADR 1: Remove Smartdown code](https://github.com/alphagov/smart-answers/blob/master/doc/arch/adr-001-removing-smartdown.md).

There were only two published Smartdown flows:

* [Convert landlord-immigration-check from Smartdown to Smart Answer](https://github.com/alphagov/smart-answers/pull/1900)
* [Convert pay-leave-for-parents to Ruby](https://github.com/alphagov/smart-answers/pull/2035)

I imagine that the `country_question` and `text_question` were not used by either of these flows and so there was no need to create the non-Smartdown equivalent when they were converted.

I'm not sure whether I've explained that very well, so do ask me if it doesn't. In any case, it's not hugely important - the main thing is that the partials you have removed are not currently used.

**Comment by pmanrubia** [comment]
@selfthinker did you run the regression tests after the last commit?

**Comment by selfthinker** [comment]
As I mentioned in the description, I did run the regression tests and they passed. But now that there is a conflict, I can resolve it and run the tests again afterwards.

**Comment by pmanrubia** [comment]
LGTM

**Pull request merged**
