### PR TITLE
Update opposite sex outcome to reflect current process

### PR DESCRIPTION
**Pull request by lamussel1**
Made the content clearer and made corrections.

https://trello.com/c/mQTvWYd5/2588-getting-married-in-egypt

### CODE REVIEW

**Comment by edwardkerry** [comment]
The last heroku app failed for some reason and the current preview didn't appear here, but it's up at
https://smart-answer-lamussel1-xnrvglb.herokuapp.com/

**Comment by benthorner** [comment]
Hi @lamussel1. Do we still need this PR, or can we close it?

**Comment by lamussel1** [comment]
Hi Ben,

Is there a way of reopening this pull request?

I was off sick, so hadn't had a chance to add a note.

Thanks,
Lucy

**Comment by benthorner** [comment]
Sure, no problem 👍.

**Comment by lamussel1** [comment]
Thank you. Please can you leave this open? - L

**Comment by benthorner** [comment]
Yup, that's absolutely fine. 

I noticed there were a lot of open, old PRs on Smart Answers, which makes it harder to find active dev work. One thing that would help is if the PR has a link to a ticket or card, so it's clear it's being tracked somewhere and not forgotten about (we have quite a few forgotten PRs across GOV.UK). This is something we do with most dev PRs, and provides more context in future when someone wonders why a particular change was made.

Would it be possible to do that here?

**Comment by lamussel1** [comment]
Hi Ben,

Yes no problem. Here's the Trello:
https://trello.com/c/mQTvWYd5/2588-getting-married-in-egypt

**Pull request merged**
