### PR TITLE
(3/6) HolidayEntitlementCalculator: Update entitlement for compressed hours worked per week

### PR DESCRIPTION
**Pull request by MahmudH**
Follows on from #4157 

https://trello.com/c/EPpMt8Yh/1329-8-implement-revised-logic-for-compressed-hours-for-holiday-entitlement-calculator

Co-Authored-By: @deborahchua @callumknights

### CODE REVIEW

**Comment by issyl0** [comment]
If you add `Co-authored-by: name <email-address>` to the commit message, your pairs actually get credit in commit messages and they get green dots on their contribution graphs. Depends on your love of typing `@digital.cabinet-office.gov.uk` multiple times...

**Comment by issyl0** [comment]
Brilliant! I thought this happened a bit fast! It's nice that it's the same as the other one.

**Comment by deborahchua** [comment]
I wonder whether for consistency we should up date all the methods with `_full_time_part_time_hours` to `_full_time_part_time_compressed_hours`?

**Comment by deborahchua** [comment]
I'm going to close the PR as it's not mergeable until we're done with all of the changes and have fixed the flows.

**Pull request closed without merging**
