### PR TITLE
Update outdated marriage abroad outcome links

### PR DESCRIPTION
**Pull request by edwardkerry**
This PR updates two outdated links Northern Ireland and Isle of Man registry office information in Marriage Abroad outcomes.

`http://www.nidirect.gov.uk/index/information-and-services/government-citizens-and-rights/births-and-registration/district-registrars-in-northern-ireland.htm` => `https://www.nidirect.gov.uk/contacts/district-registrars-northern-ireland`

`http://www.gov.im/registries/general/civilregistry` => `https://www.gov.im/categories/births-deaths-and-marriages`

[Trello](https://trello.com/c/E7WMHXU6/2212-update-broken-links-in-smart-answers)

### CODE REVIEW

**Review by AlanGabbianelli — APPROVED** [review]
Not going to check 263 files one by one. I assume a global search and replace works. 😄

**Comment by edwardkerry** [comment]
> Not going to check 263 files one by one. I assume a global search and replace works. 😄

they were all bespoke by hand actually

**Comment by richardskipper** [comment]
I'm happy with this! It's good to know we have this functionality (and it does make me reflect on how quickly I could've done the rest of the links if I had known this was an option...)

**Comment by richardskipper** [comment]
Is there something I should be pressing to approve this? Not sure how this works, sorry!

**Review by richardskipper — APPROVED** [review]
Ah here we are! All good to go.

**Pull request merged**
