### PR TITLE
Use next_node blocks in maternity-paternity-calculator

### PR DESCRIPTION
**Pull request by chrisroos**
We've agreed to consistently use `next_node {}` to define our next node rules. Having a single way of defining the rules will hopefully make Smart Answers easier to develop and maintain.

This will ultimately allow us to remove the predicate code (`define_predicate`, `on_condition`, `next_node_if` etc).

### CODE REVIEW

**Comment by floehopper** [comment]
@chrisroos: I'm investigating this build failure, because it looks as if it might be related to changes I've made recently.

**Comment by chrisroos** [comment]
I've rebased on master and force pushed. I'm expecting the build to pass. The previous failure was unrelated to these changes.

**Comment by floehopper** [comment]
Assuming the checksums are correct, this looks good to me. :+1:

**Comment by chrisroos** [comment]
I've rebased on master and force pushed in preparation for merging.

**Pull request merged**
