### PR TITLE
[WIP] Add script for flattening

### PR DESCRIPTION
**Pull request by cbaines**
This is still a work in progress, and I'm not sure how much time I'll have to work on this now that I'll have another team after my time.

### CODE REVIEW

**Comment by pmanrubia** [comment]
@ikennaokpala have you tried it locally with a couple of countries? 
@chao-xian Why did you change the title to [WIP]? The PR is approved, but still the title does not match the status.

**Comment by ikennaokpala** [comment]
I don't this is a script that is meant to be perfect.. given the anomalies that may come up..I see it as a script that jet start the flattening process.. Hence why it serve as a starting point. The developer that uses this script should then review the changes and make sure that it is in order before checking it in.

**Comment by pmanrubia** [comment]
@ikennaokpala I don't think so. The script is supposed to flatten countries following a set of steps. It should generally work, and the developer has to review the output in any case.
I don't think we should approve this PR without running it locally for a couple of countries.

**Comment by ikennaokpala** [comment]
That is my humble opinion.. There is not point trying to perfect it knowing that Marriage abroad templates may present a few anomalies

**Comment by chao-xian** [comment]
@pmanrubia I added the `[WIP]` to the title because that's what @cbaines said the status is in the PR, which I did before the PR was approved.

**Comment by pmanrubia** [comment]
@chao-xian could you please run the script locally and see if it is fit for purpose? if not, could you please find out if there are any steps we could take?

**Comment by pmanrubia** [comment]
@ikennaokpala there is no point in approving a PR without even running it locally. This is not how we work.

**Comment by ikennaokpala** [comment]
FYI.. I have run it locally and found it sufficient

**Comment by pmanrubia** [comment]
@chao-xian thank you for having a look at it. 

Could you please add a comment to this PR with the countries you have run the script against? and the anomalies that you have found, if any?
If the script is running smoothly, we would only need to update the documentation before merging.

**Comment by chao-xian** [comment]
@pmanrubia this seems fine. I can't see any obvious problems with it. All it does is create the outcome per path files that would normally be quite a laborious manual process - assuming you are doing an 18 outcome flattening. 

And it's definitely not complete because you are left with files that need cleaning up, so for a `_opposite_sex.erb` file it has alongside it a `_opposite_sex.erb-e` that needs removing.

I ran this against:

* Malaysia
* Singapore
* Finland

**Comment by cbaines** [comment]
> And it's definitely not complete because you are left with files that need cleaning up, so for a _opposite_sex.erb file it has alongside it a _opposite_sex.erb-e that needs removing.

Interesting, I don't think I encountered this. I just ran the flatten script locally for the 3 countries you mentioned, and I didn't get any odd files generated. Perhaps the perl or sed you are using works differently to the one I'm using?

**Comment by chao-xian** [comment]
@cbaines I had been running it on OS X.

Another issue is that it doesn't work on the VM at the moment 

```
vagrant@development:/var/govuk/smart-answers$ script/flatten.sh malaysia
script/flatten.sh: 12: read: Illegal option -d
script/flatten.sh: 19: script/flatten.sh: Bad substitution
```

But weirdly if I run that read command with the same options on the command line it doesn't complain.

**Comment by cbaines** [comment]
> But weirdly if I run that read command with the same options on the command line it doesn't complain.

I'm running it with bash, but I guess that in the govuk-puppet development VM, you are using dash. Try running it explicitly with bash perhaps? (e.g. `bash ./scripts/flatten.sh ...`).

**Comment by chao-xian** [comment]
@cbaines yeah that worked and without the `-e` erb templates.

**Comment by cbaines** [comment]
> @cbaines yeah that worked and without the -e erb templates.

Great :+1:

**Comment by chao-xian** [comment]
@mgrassotti have you been using this script at all?

**Comment by mgrassotti** [comment]
@chao-xian yes I am

**Comment by chao-xian** [comment]
@mgrassotti both on your Mac or just in the VM? Any changes that you've made? If you have been using it in anger and it's fine, then I think we need to update this PR and look to merge it in (unless that's already been done somewhere else).

What do you reckon?

**Comment by chao-xian** [comment]
Hi @mgrassotti we really should merge this into master if we are actively using it. Can you please add your review to this PR. I'd be happy to update our docs if you can let me know that the script is ok.

**Comment by chao-xian** [comment]
@mgrassotti hi I'm going to close this PR as we are slowing down on the number of requests we get for flattening Marriage Abroad. The only other option is to merge into `master`. I'll close it by the end of tomorrow. Cc @pmanrubia

**Comment by cbaines** [comment]
Matteo is no longer active, and I'm currently trying to cut down on the number of Pull Requests I have open. I'm going to close this for now, but I'll leave the branch around. I think this script is still a real time saver when it comes to flattening.

**Pull request closed without merging**
