### PR TITLE
Move smart answer test flows and locales to single directory

### PR DESCRIPTION
**Pull request by chrisroos**
This is based on PR #2047 (i.e. I'm assuming that'll be merged first).

This moves all test Smart Answer flows and locale files to test/fixtures/smart_answer_flows, rather than having them spread across different directories in test/fixtures.

### CODE REVIEW

**Comment by floehopper** [comment]
LGTM :+1:

**Comment by chrisroos** [comment]
I've rebased this on master and force pushed. Merging to master.

**Comment by chrisroos** [comment]
Right. I haven't merged it to master because this PR was based on a branch other than master. I'll come back to this in the morning.

**Comment by chrisroos** [comment]
I've opened a new PR #2054 and merged these changes to master from there.

**Pull request merged**
