### PR TITLE
Add an option for the 2014-2015 tax year to estimate self assessment penalties

### PR DESCRIPTION
**Pull request by leenagupte**
Trello card: https://trello.com/c/kPcIQYAL/191-estimate-your-penalty-for-late-self-assessment-tax-returns-and-payments-content-change-request

## Factcheck
[Estimate self assessment penalties](https://smart-answers-pr-2590.herokuapp.com/estimate-self-assessment-penalties/y)

## Expected changes
[URL on GOV.UK](https://www.gov.uk/estimate-self-assessment-penalties/y)
* Add an option for the 2014-2015 tax year

### Before

screen shot 2016-06-16 at 17 27 12

### After

screen shot 2016-06-16 at 17 28 29

### CODE REVIEW

**Comment by pmanrubia** [comment]
Minor: What about renaming the commit title from `estimate-self-assesment-penalties` to `self-assesment-penalties`? I would also add that prefix to the end of the commit, as it seems to be less important than what the commit does. It is just adding some context to it.

Minor: I would squash e9d906d575fb9bb288dc65861a0451dcd77e9c24 into dc555cf0f1ac41967ef3e88f81dc479854ae69f9. It seems sensible to have them together if we follow a TDD approach.

**Comment by pmanrubia** [comment]
@leenagupte good work. 👍 
Just two minor comments for your consideration.

**Comment by leenagupte** [comment]
@pmanrubia The commit headings are named after the calculator estimate-self-assesment-penalties.
Unless you mean the PR heading?

**Comment by leenagupte** [comment]
@pmanrubia I can squash the commits if you want. Makes no difference to me.

**Comment by leenagupte** [comment]
Passed Factcheck

**Pull request merged**
