### PR TITLE
Register a birth Libya

### PR DESCRIPTION
**Pull request by leenagupte**
Trello card: https://trello.com/c/b4Gim4JW/210-30-june-changes-to-registering-a-birth-in-libya-content-change-request

## Factcheck
[Register a birth Libya](https://smart-answers-pr-2610.herokuapp.com/register-a-birth/y/libya)

## Expected Changes

[URL on GOV.UK](https://www.gov.uk/register-a-birth/y/libya)
    * Selecting Libya should send you straight to an outcome

### Before

screen shot 2016-07-01 at 12 34 00

### After

screen shot 2016-07-01 at 12 34 29

### CODE REVIEW

**Comment by pmanrubia** [comment]
@leenagupte could you please accommodate your commits to [50 chars for the title and 72 characters per line in the description](https://github.com/alphagov/styleguides/blob/master/git.md#example-1)

**Comment by leenagupte** [comment]
@pmanrubia Done.

**Comment by pmanrubia** [comment]
Thank you @leenagupte. Still, the lines of the description are not 72 characters max. I guess you are doing it because Github is able to wrap it nicely, but there are other editors out there that are not that smart /user friendly (particularly terminal-based editors). So, I would follow the conventions until it is agreed that this is not necessary any more.

**Comment by leenagupte** [comment]
@pmanrubia Oops! I was in a rush and only did the titles. Fixed now.

**Comment by pmanrubia** [comment]
Great work @leenagupte LGTM

**Pull request merged**
