### PR TITLE
Dry up marriage-abroad same-sex ceremony-not-possible outcomes

### PR DESCRIPTION
**Pull request by chrisroos**
__This supersedes PR #2410. I've updated the branch to consistently use "your same-sex" instead of "a same-sex". See the previous PR for more information.__

I noticed that `outcome_same_sex_marriage_and_civil_partnership_in_other_countries` and `outcome_same_sex_marriage_and_civil_partnership_not_possible` were almost identical. The only difference was the use of "a same-sex relationship" versus "your same-sex relationship".

I've removed that duplication by standardising on "your same-sex relationship" based on the discussion in PR #2410.

## Expected changes

This affects same sex outcomes for ceremonies in 151 countries (see the bottom of this description for the full list).

### Before

* Example outcome - https://www.gov.uk/marriage-abroad/y/poland/uk/partner_british/same_sex
  * Outcome contains "a same-sex relationship".

pr-2530-before

### After

* Example outcome -  https://smart-answers-pr-2530.herokuapp.com/marriage-abroad/y/poland/uk/partner_british/same_sex
  * Outcome contains "your same-sex relationship".

pr-2530-after

## List of affected ceremony countries

* afghanistan
* algeria
* american-samoa
* angola
* anguilla
* antigua-and-barbuda
* armenia
* aruba
* bahamas
* bahrain
* bangladesh
* barbados
* belarus
* belize
* benin
* bermuda
* bhutan
* bosnia-and-herzegovina
* botswana
* british-indian-ocean-territory
* british-virgin-islands
* brunei
* burkina-faso
* burma
* cameroon
* cape-verde
* cayman-islands
* central-african-republic
* chad
* comoros
* congo
* costa-rica
* cote-d-ivoire
* cuba
* curacao
* democratic-republic-of-congo
* djibouti
* dominica
* egypt
* el-salvador
* equatorial-guinea
* eritrea
* ethiopia
* falkland-islands
* fiji
* gabon
* gambia
* georgia
* ghana
* gibraltar
* greece
* grenada
* guinea
* guinea-bissau
* guyana
* haiti
* honduras
* hong-kong
* india
* indonesia
* iran
* iraq
* israel
* italy
* jamaica
* jordan
* kazakhstan
* kenya
* kiribati
* kuwait
* kyrgyzstan
* laos
* lebanon
* lesotho
* liberia
* libya
* lithuania
* macao
* macedonia
* madagascar
* malawi
* malaysia
* maldives
* mali
* marshall-islands
* mauritania
* mauritius
* micronesia
* montserrat
* morocco
* mozambique
* namibia
* nauru
* nepal
* niger
* nigeria
* north-korea
* oman
* pakistan
* palau
* papua-new-guinea
* paraguay
* pitcairn-island
* poland
* qatar
* romania
* rwanda
* samoa
* sao-tome-and-principe
* saudi-arabia
* senegal
* sierra-leone
* singapore
* slovakia
* solomon-islands
* somalia
* south-georgia-and-south-sandwich-islands
* south-korea
* south-sudan
* sri-lanka
* st-helena-ascension-and-tristan-da-cunha
* st-kitts-and-nevis
* st-lucia
* st-maarten
* st-vincent-and-the-grenadines
* sudan
* suriname
* swaziland
* syria
* taiwan
* tajikistan
* tanzania
* thailand
* timor-leste
* togo
* tonga
* trinidad-and-tobago
* tunisia
* turkey
* turkmenistan
* turks-and-caicos-islands
* tuvalu
* uganda
* ukraine
* united-arab-emirates
* uzbekistan
* vanuatu
* western-sahara
* yemen
* zambia
* zimbabwe

### CODE REVIEW

**Comment by chrisroos** [comment]
@floehopper: I know that you've given PR #2410 the thumbs up but I'd appreciate you taking a look at this given that I've rewritten the commits.

**Comment by floehopper** [comment]
It sounds as if you are often running the regression tests for *all* countries. I think you've previously suggested we make this the case in `master`. If running the regression tests for all countries doesn't take too long, I think this might be a good idea. If not, perhaps we can look at some optimisations to speed up the regression tests e.g. https://trello.com/c/T69SfCaC. If we had complete coverage at the regression test level, we could consider removing the integration tests for `marriage-abroad` if that helped.

**Comment by floehopper** [comment]
Other than my suggested change to one of the the commit notes, this looks good to me. 👍

**Comment by chrisroos** [comment]
Thanks for reviewing, @floehopper. I'm closing this to address your feedback. I'll open a new PR and get that merged to master soon.

**Comment by chrisroos** [comment]
> It sounds as if you are often running the regression tests for all countries. I think you've previously suggested we make this the case in master. If running the regression tests for all countries doesn't take too long, I think this might be a good idea. If not, perhaps we can look at some optimisations to speed up the regression tests e.g. https://trello.com/c/T69SfCaC. If we had complete coverage at the regression test level, we could consider removing the integration tests for marriage-abroad if that helped.

I am indeed running the regression tests for all countries fairly regularly. I suggested we make this the case in master in PR #2395 although we decided against it. It wasn't obvious that it was the right thing to do as making the change means that the tests take almost double the time to run.

Investigating some performance improvements definitely sounds good. I'll try to do that soon.

**Pull request closed without merging**
