### PR TITLE
Remove unused data attribute from content partial

### PR DESCRIPTION
**Pull request by floehopper**
This was added in a *very* early [commit][1] and as far as I can see has never
been used. The value of the data attribute also sounds suspiciously
flow-specific even though it appears in a generic template. On that basis, I
think it's safe to remove it.

[1]: b5df0c1bfb43e9840b4251cb84214e66eb1820a9

### CODE REVIEW

**Comment by chrisroos** [comment]
Looks good to me, although I think you're going to regenerate the question page artefacts as they all seem to contain this `data-partial` attribute.

**Comment by floehopper** [comment]
Well spotted. That's a shame :confounded:

**Comment by chrisroos** [comment]
I'm running all the regression tests locally in preparation for getting this merged.

**Comment by chrisroos** [comment]
I've rebased and force-pushed in preparation for merging.

**Pull request merged**
