### PR TITLE
Update country specific outcomes for marriage abroad

### PR DESCRIPTION
**Pull request by erik-eide**
This is a batch of marriage abroad process changes in Poland, United Arab Emirates, Indonesia, Vietnam, Cambodia and Thailand, started some time ago.

This PR supersedes #1933, closed after a rebase to master to retain its history.

Changes have been through fact check and this PR represented the fixes to be applied afterwards.

## Expected changes 

[Example URL](https:/www.gov.uk/marriage-abroad/y/vietnam/uk/partner_british/opposite_sex)
 * Callout starting with: "You must stay in Vietnam for 14 days" should be visible

screen shot 2015-11-09 at 6 11 24 pm

### CODE REVIEW

**Comment by chrisroos** [comment]
I'm slightly confused as to why this has the "Don't merge" label when it appears to have come back from factcheck. I'm going to leave this for now (mostly because it's huge :-)) and wait to see if anyone starts asking for it.

**Comment by erik-eide** [comment]
We have a google doc that keeps getting new items added to it. It's been through fact check, but until no new items are added to that google doc, I guess we should hold off?

**Comment by chrisroos** [comment]
Holly has said we've got the OK to deploy this. I'm going to review it, rebase on master and get it merged.

**Comment by chrisroos** [comment]
I've rebased, double checked that all regression tests pass and force pushed. I'm going to merge this now.

**Pull request merged**
