### PR TITLE
Added a link to the 2015 to 2016 CCG2 form

### PR DESCRIPTION
**Pull request by keithiopia**
https://govuk.zendesk.com/agent/tickets/1173599

Don't deploy before SLC tell us the new pdf is live.

### CODE REVIEW

**Comment by er-ke-de** [comment]
@keithiopia Can you add a comment here when the PDF is live, otherwise looks good to me

**Comment by lutgendorff** [comment]
This is now good to deploy, the PDF is live (Keith is on holiday).

**Comment by er-ke-de** [comment]
@lutgendorff I'm still seeing a 404 (Not Found) when trying to access the new PDF, can we verify if the URL is correct?

 http://media.slc.co.uk/sfe/1516/ft/sfe_ccg2_1516_d.pdf

**Comment by lutgendorff** [comment]
Looks like there was a slight typo. This is the right link: http://media.slc.co.uk/sfe/1516/ft/sfe_ccg2_form_1516_d.pdf

**Comment by floehopper** [comment]
Superseded by #2036.

**Pull request closed without merging**
