### PR TITLE
Policy changes for roll out on 1 Feb 2016

### PR DESCRIPTION
**Pull request by keithiopia**
As of 1 Feb 2016 - this is the document list for landlords needing to verify tenant eligibility. 
Comes from: https://govuk.zendesk.com/agent/tickets/1236957

### CODE REVIEW

**Comment by keithiopia** [comment]
Will require preview for factcheck with Home Office.

**Comment by issyl0** [comment]
I just read "tenancies" as "tentacles". :octopus: :worried:

**Comment by keithiopia** [comment]
I'm not sure if it would hurt if you substituted that word. 
I might have another commit for this PR...sorry.

**Comment by daibach** [comment]
Marking this as `do not merge` until @keithiopia is happy he's got everything :)

**Comment by keithiopia** [comment]
These are all the commits I'm going to do for now. Otherwise this will never get merged!

**Comment by erikse** [comment]
Superseded by #2256

**Pull request closed without merging**
