### PR TITLE
Update Heroku settings and documentation from preview to integration

### PR DESCRIPTION
**Pull request by erikse**
Now that preview has been replaced in favour of integration, updating the Heroku variables set by this script for setting up new staging servers

@dsingleton @jennyd

### CODE REVIEW

**Comment by jennyd** [comment]
The Errbit URL on line 45 also needs updating - otherwise :+1:

**Comment by erikse** [comment]
Thanks, updated that. But I found a bunch of other references to preview in the docs folder, just looking at those

**Comment by erikse** [comment]
Think I've got them all now, there are two historical references to the preview environment about how smart answers was previously developed, which doesn't seem correct to change.

**Comment by daibach** [comment]
:+1:

**Comment by erikse** [comment]
Just rebased this with master & force pushed back to this PR's branch

**Pull request merged**
