### PR TITLE
Content Update (21092016) for State pension through partner Smart Answer

### PR DESCRIPTION
**Pull request by ikennaokpala**
Supersedes #2738

[Trello card](https://trello.com/c/jVxRQVUn/362-pull-request-2738-content-changes-to-state-pension-through-partner)

## Description 

Content changes made to the outcomes for this (State pension through partner) smart answer to correct some errors and typos.

## Factcheck

[Preview link](https://smart-answers-pr-2777.herokuapp.com/state-pension-through-partner/y/divorced/female_gender)
[GOV.UK](https://gov.uk/state-pension-through-partner/y/divorced/female_gender)

### Expected changes

* Content updates to various sections and outcomes

### Before 

screen shot 2016-10-07 at 16 08 07

### After

screen shot 2016-10-07 at 16 08 20

### Affected outcomes

- https://smart-answers-pr-2777.herokuapp.com/state-pension-through-partner/y/divorced/female_gender
- https://smart-answers-pr-2777.herokuapp.com/state-pension-through-partner/y/married/your_pension_age_after_specific_date/partner_pension_age_after_specific_date/female_gender
- https://smart-answers-pr-2777.herokuapp.com/state-pension-through-partner/y/married/your_pension_age_after_specific_date/partner_pension_age_before_specific_date/female_gender
- https://smart-answers-pr-2777.herokuapp.com/state-pension-through-partner/y/widowed/your_pension_age_after_specific_date/female_gender
- https://smart-answers-pr-2777.herokuapp.com/state-pension-through-partner/y/widowed/your_pension_age_before_specific_date

### CODE REVIEW

**Comment by selfthinker** [comment]
Code-wise this LGTM.
I only wonder if we should rather squash some of the commits and rewrite the commit messages to make the commit history cleaner? If no-one objects, I can do that tomorrow.

**Comment by ikennaokpala** [comment]
@selfthinker I have consolidated the commits as requested..

**Comment by selfthinker** [comment]
I would squash the first 3 commits as they are all the same change. I would add the 4th commit to it as well as we would usually add 2i changes to the original change. I suspect the first 3 commits were only done separately because GitHub's interface doesn't make it easy to do them together.

I would also rewrite the commit messages as they are reiterating what the exact change is and is therefore duplicating things unnecessarily. I would keep the heading and the reason, e.g.

> 1. Lower case for ‘reduced rate election’
>
> CHANGE
> The Reduced Rate Election reduced rate election must have applied to you at some point within the 35 years...
> 
> TO
> The reduced rate election reduced rate election must have applied to you at some point within the 35 years…
> 
> REASON
> Not GOV.UK style to capitalise this.

would change to

> 1. Lower case for ‘reduced rate election’ because it's not GOV.UK style to capitalise this.

**Comment by selfthinker** [comment]
The title of "Correct content errors in age_dependent_pension_outcome.govspeak.erb" is now incorrect and should be changed to something like "Correct content errors in State pension through partner outcomes".

You have now removed some of the detailed change descriptions but not all of them. Is there a reason why you haven't adjusted 3. and 5. as well?

Minor: I would think the `--` was only there because there was a lot of text. But when it's less text now, it could fit easily into just one list without spacing or lines inbetween.

**Pull request merged**
