### PR TITLE
Remove hardcoded fee and payment information for marriages in Brazil

### PR DESCRIPTION
**Pull request by ikennaokpala**
[Trello card](https://trello.com/c/nPY5hcnA/159-remove-hardcoded-fee-from-brazil-outcomes-marriage-abroad)

* This PR removes hardcoded fees and payment information existing within the Brazilian marriage abroad pages.

* Some of the outcomes for Brazil display a hardcoded fee of £55. See[this](https://www.gov.uk/marriage-abroad/y/brazil/third_country/partner_british/opposite_sex#what-you-need-to-do) .

### Expected change

* Removal of this hardcoded fee

[Preview link](https://smart-answers-pr-2582.herokuapp.com/marriage-abroad/y/brazil/third_country/partner_british/opposite_sex)
[GOV.UK](https://gov.uk/marriage-abroad/y/brazil/third_country/partner_british/opposite_sex)

### Before
screen shot 2016-06-14 at 15 30 02

### After
screen shot 2016-06-14 at 15 30 13

### Expected changes

* Add fees table with on Affidavit or affirmation for marriage fee within

[Preview link](https://smart-answers-pr-2582.herokuapp.com/marriage-abroad/y/brazil/third_country/partner_british/opposite_sex#fees)
[GOV.UK](https://gov.uk/marriage-abroad/y/brazil/third_country/partner_british/opposite_sex#fees)

### Before
screen shot 2016-06-14 at 15 59 38

### After

screen shot 2016-06-14 at 15 59 21

### Affected pages

https://smart-answers-pr-2582.herokuapp.com/marriage-abroad/y/brazil/third_country/partner_british/opposite_sex
https://smart-answers-pr-2582.herokuapp.com/marriage-abroad/y/brazil/third_country/partner_british/same_sex
https://smart-answers-pr-2582.herokuapp.com/marriage-abroad/y/brazil/third_country/partner_local/opposite_sex
https://smart-answers-pr-2582.herokuapp.com/marriage-abroad/y/brazil/third_country/partner_local/same_sex
https://smart-answers-pr-2582.herokuapp.com/marriage-abroad/y/brazil/third_country/partner_other/opposite_sex
https://smart-answers-pr-2582.herokuapp.com/marriage-abroad/y/brazil/third_country/partner_other/same_sex
https://smart-answers-pr-2582.herokuapp.com/marriage-abroad/y/brazil/uk/partner_british/opposite_sex
https://smart-answers-pr-2582.herokuapp.com/marriage-abroad/y/brazil/uk/partner_local/opposite_sex
https://smart-answers-pr-2582.herokuapp.com/marriage-abroad/y/brazil/uk/partner_other/opposite_sex

### CODE REVIEW

**Comment by chrisroos** [comment]
This looks good to me, @ikennaokpala.

**Comment by chrisroos** [comment]
I've added the "Waiting on factcheck" label as I don't believe we've heard back from the department yet.

**Comment by ikennaokpala** [comment]
@chrisroos thanks for reviewing.. we haven't eard back from the department.. @sistephens

**Comment by sistephens** [comment]
This is good to go, thanks 👍

**Pull request merged**
