### PR TITLE
Student form finder change for EU students

### PR DESCRIPTION
**Pull request by pmanrubia**
Piv: https://www.pivotaltracker.com/story/show/115249327
Zen: https://govuk.zendesk.com/agent/tickets/1275668

Update the forms for new, full-time, EU students

## Factcheck

https://smart-answers-pr-2369.herokuapp.com/student-finance-forms/y/eu-full-time/year-1617/new-student

## Expected changes

* [URL on gov.uk](https://www.gov.uk/student-finance-forms/y/eu-full-time/year-1617/new-student)
  * Add advice on how to apply for a Tuition Fee Loan, and provide additional information of other forms that might be needed.

### Before
screen shot 2016-03-18 at 10 57 52

### After
screen shot 2016-03-18 at 10 57 26

### CODE REVIEW

**Comment by stwalsh** [comment]
Fact check is fine:
https://govuk.zendesk.com/agent/tickets/1275668 
Can we get this in on the morning of the 28th? (or 29th if there's no deployment on Easter Monday)

**Comment by pmanrubia** [comment]
@stwalsh it is difficult to the deploy on the 28th because it is Easter Monday, but I have just scheduled it for 29 March at 11am. I hope this is fine with you?

**Comment by stwalsh** [comment]
Hi @pmanrubia - 11am is great - thank you very much.

**Comment by floehopper** [comment]
I wonder whether it's worth creating a milestone of 29th March for this to make it clearer that it can't be deployed until then.

**Comment by pmanrubia** [comment]
@floehopper I have created the milestone. We might need to tackle scheduled deploys with a custom label?

**Comment by pmanrubia** [comment]
Rebased against master and force pushed in preparation release.

**Pull request merged**
