### PR TITLE
Renew student finance calculator for 2016/17 academic year

### PR DESCRIPTION
**Pull request by tadast**
Summary of changes:

- minor copy improvements for clarity
- updated links (some of them are pointing to non-existent paths at the moment, they should be published before deploying this, check with @stwalsh)
- remove 2014-2015 branch
- add 2016-2017
  - no more maintenance grants are to be provided
  - maintenance loans are bigger to compensate for the above
  - copy changes related to the above

By the way, @stwalsh has been amazing to work with on this change, thanks!

### CODE REVIEW

**Comment by tadast** [comment]
@floehopper @chrisroos this came back clear from fact check. It needs to be deployed on 5th Oct 2015. Please inform Sean or Lucy once you've booked a deploy slot. If you're not planning to be in the office on 5th Oct, let them know in advance so they can find another developer to deploy this. Thanks

**Comment by chrisroos** [comment]
I've rebased this on master and force pushed. I've also split the final commit to make it easier to see the changes that are being made. I've split it into:

* Update YAML syntax for student-finance-calculator regression files
* Update option in student-finance-calculator-questions-and-responses
* Update checksum data for student-finance-calculator

**Comment by chrisroos** [comment]
I've booked a deploy slot for 10:30 on Mon 5 Oct. @floehopper and I won't be around but @lutgendorff has said she's happy to sit with 2nd line to deploy.

**Comment by stwalsh** [comment]
Cool,
thank you - I should be around if we need to do anything.
CCing Lucy in case she wants to let SLC know.
Thanks again!
Sean

On Tue, Sep 29, 2015 at 11:34 AM, Chris Roos <notifications@github.com>
wrote:

> I've booked a deploy slot for 10:30 on Mon 5 Oct. @floehopper
> <https://github.com/floehopper> and I won't be around but @lutgendorff
> <https://github.com/lutgendorff> has said she's happy to sit with 2nd
> line to deploy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alphagov/smart-answers/pull/1972#issuecomment-144019096>
> .
>



-- 
Sean Walsh
205 Springbank Road
London
SE13 6ST

Mobile: 07803 248 372

**Comment by chrisroos** [comment]
I've rebased this on master and force pushed.

I've reviewed the PR in more detail and am happy for it to be merged. I'll merge it after we deploy tomorrow, so that it's ready to go live on Monday.

**Comment by chrisroos** [comment]
I've rebased and force pushed this branch. I'll merge it if/when all the tests pass.

**Pull request merged**
