### PR TITLE
Calculate married couples allowance: 6th April ratings update for 2017-18

### PR DESCRIPTION
**Pull request by ikennaokpala**
[Trello card](https://trello.com/c/nb8VFuyF/577-uprating-calculate-your-married-couple-s-allowance)

## Description 
This PR contains rate update for next financial that affect married couples allowance.

## Factcheck

[Preview link](https://smart-answers-pr-2965.herokuapp.com/calculate-married-couples-allowance/y/yes/yes/1950-01-01/28001.0/yes/10000.0/5000.0/0.0)
[GOVUK](https://www.gov.uk/calculate-married-couples-allowance/y/yes/yes/1950-01-01/27701.0/yes/10000.0/5000.0/0.0)
**NB: RATES_QUERY_DATE: 2018-04-05 and [Jenkins job for all regression tests](https://ci.integration.publishing.service.gov.uk/job/smartanswers/job/calculate-married-couples-allowance%252Fupratings/10/console)**

## Expected changes
- Married couples allowance:
   - maximum_married_couple_allowance: 8445
   - minimum_married_couple_allowance: 3260

- Personal allowance:
   - income_limit_for_personal_allowances: 28000.0

### Before
screen shot 2017-03-17 at 13 59 01

### After
screen shot 2017-03-17 at 13 58 50

### CODE REVIEW

**Comment by ikennaokpala** [comment]
@leenagupte By Increasing the income from 27701 to 28001.. is an attempt to remove the old artefacts from the previous years, allowing the new `income_within_limit_for_personal_allowance` to be created first.. The context is within these two question `whats_the_husbands_income?` and `whats_the_highest_earners_income ?` See https://github.com/alphagov/smart-answers/blob/master/lib/smart_answer_flows/calculate-married-couples-allowance.rb#L70

**Comment by leenagupte** [comment]
@ikennaokpala Can you update the commit to that effect? Something like, the personal allowance for income tax is increasing... To be able to see the effect that the change has I am updating earning amount to one that is over the current limit (2016-2017 tax year) but is below the new personal allowance that is coming into effect for the 2017-2018 tax year. If that is indeed what is happening?

**Comment by ikennaokpala** [comment]
@leelongmore 2a40543's commit not contains more

**Comment by leenagupte** [comment]
@ikennaokpala The commit title for 2a40543 is:
`Preparatory: Update 2016-04-06 to 2017-04-06`

What does this refer to?

**Comment by ikennaokpala** [comment]
@leenagupte I have updated the title 28eaf99

**Pull request merged**
