### PR TITLE
Content changes to Personal Independence Payment

### PR DESCRIPTION
**Pull request by ikennaokpala**
[Trello Story](https://trello.com/c/oiF97JOL/111-pip-checker)

* Content changes to PIP Checker as per this document https://docs.google.com/document/d/1mmyFN1zyjxgonN40wnbPcTuTYb4FUxzqEcJFWHQgctg/edit and https://docs.google.com/document/d/1KbYzCS0Weq0t_YQpmuVebkSPP0AgObq6ZqT5RSw3p2Q/edit

## Factcheck
[Preview Link](https://smart-answers-pr-2482.herokuapp.com/pip-checker/)
[GOV.UK](https://gov.uk/pip-checker/)

### Expected changes
*  Content changes Personal Independence Payment 
*  Rename the pip-checker outcomes to names that are relative to the audience and/or content within each

    The following files were renamed accordingly:

    * result_1.govspeak.erb to under_16.govspeak.erb
    * result_2.govspeak.erb to over_65.govspeak.erb
    * result_3.govspeak.erb to no_claim_for_dla.govspeak.erb
    * result_5.govspeak.erb to qualifies_for_pip_at_16.govspeak.erb
    * result_6.govspeak.erb to over_65_in_2013.govspeak.erb
    * result_7.govspeak.erb to qualifies_for_pip.govspeak.erb

    SEE: https://github.com/alphagov/smart-answers/tree/pip-checker/lib/smart_answer_flows/pip-checker/outcomes

### Before

screen shot 2016-04-27 at 10 36 13

### After

screen shot 2016-05-16 at 12 28 53

Affected pages:

https://smart-answers-pr-2482.herokuapp.com/pip-checker/y/no/1948-03-01
https://smart-answers-pr-2482.herokuapp.com/pip-checker/y/no/1949-02-03
https://smart-answers-pr-2482.herokuapp.com/pip-checker/y/no/1990-03-05
https://smart-answers-pr-2482.herokuapp.com/pip-checker/y/no/1997-05-08
https://smart-answers-pr-2482.herokuapp.com/pip-checker/y/no/2000-04-05
https://smart-answers-pr-2482.herokuapp.com/pip-checker/y/yes/2000-04-05
https://smart-answers-pr-2482.herokuapp.com/pip-checker/y/

### CODE REVIEW

**Comment by chrisroos** [comment]
@ikennaokpala: Can this be reviewed given our recent change in workflow?

**Comment by ikennaokpala** [comment]
@chrisroos This is a bit on hold at the moment.. the team are sorting things out

**Comment by pmanrubia** [comment]
Great work @ikennaokpala. Just a few thoughts:

1. I would have renamed the outcomes in the first commit, so I can run regression tests and be confident that they are passing. Artefacts should not change.
2. I would have split the first commit per outcome, and I would have used the `reason` section in the document in the commit notes, and the new outcome name in the commit title. This could be valuable information for Git history. 

We can pair on this if you want.

**Comment by ikennaokpala** [comment]
@pmanrubia Thanks.. this was done prior to you introducing me to that line of tracking the changes..
Notwithstanding, I ahve taken you comments onboard and will implement your suggestions

**Comment by ikennaokpala** [comment]
@pmanrubia I have applied the changes as requested

**Comment by ikennaokpala** [comment]
@chrisroos @pmanrubia kindly review these changes.. we are very close to the dealine.. and this needs to out.

**Comment by chrisroos** [comment]
This looks good to me, @ikennaokpala.

The only minor comment I have is that some of the commit notes contain long lines. It'd be great if you can configure your editor so that they [wrap according to the Git styleguide](https://github.com/alphagov/styleguides/blob/master/git.md#structure).

**Pull request merged**
