### PR TITLE
Document the use of the "In code review" label

### PR DESCRIPTION
**Pull request by chrisroos**
We're currently using the assignment of a user to a PR to indicate that it's being reviewed. I think it's worth making that more explicit by using a (to be created) "In code review" label.

### CODE REVIEW

**Comment by chrisroos** [comment]
What do you think @ikennaokpala, @floehopper, @pmanrubia, @selfthinker, @leenagupte?

**Comment by ikennaokpala** [comment]
@chrisroos  Looks good to me..

**Comment by floehopper** [comment]
LGTM 👍

**Comment by leenagupte** [comment]
Since @chrisroos and @floehopper are leaving, how do I get permissions to add and edit labels?

**Comment by chrisroos** [comment]
> Since @chrisroos and @floehopper are leaving, how do I get permissions to add and edit labels?

I know we've spoken about this in person but for the benefit of anyone else viewing this PR: I believe we can all edit/create labels by visiting [Pull Requests > Labels](https://github.com/alphagov/smart-answers/labels).

**Comment by chrisroos** [comment]
@leenagupte, @pmanrubia and @ikennaokpala. I'll leave it for you to decide whether or not to go with this suggestion. Feel free to close and delete this branch if you decide no to do it.

**Comment by pmanrubia** [comment]
Rebasing and force pushing in preparation for merging.

LGTM

**Pull request merged**
