### PR TITLE
Raise exceptions when marriage abroad is misused

### PR DESCRIPTION
**Pull request by tadast**
I added a couple of errors to inform developers when they're doing things in a manner that is unexpected by the existing logic.

Detailed explanations can be found in the commit messages.

Pro tip: add `?w=1` to the url param to ignore withespace changes when reviewing.

### CODE REVIEW

**Comment by BenJanecke** [comment]
This needs a rebase

**Comment by chrisroos** [comment]
I've left a couple of comments but overall I think this looks good to me.

**Comment by chrisroos** [comment]
> The whole reason for the change is basically to make it obvious that this outcome does not have a default set of phrases.
>
> Having said it all I do not feel strongly about it, but I believe it's more useful than harmful.

That sounds entirely sensible to me. I hadn't considered the case you've demonstrated with the multiple `if ... end`'s versus the `if ... elsif ... else ... end`'s.

**Comment by tadast** [comment]
Merged manually: 554aacf9ae2871293e8d12b5f81304fb78e8558f aa8fc2dc4d2dbfb9e8340a9e22e576790b02bee3 0d714cf79d13377cd3bca63f58328d88bec67331

**Pull request closed without merging**
