### PR TITLE
Allow for indented content in ERB templates

### PR DESCRIPTION
**Pull request by chrisroos**
I've updated `OutcomePresenter#title`, `OutcomePresenter#body` and `OutcomePresenter#next_steps` so that they strip leading spaces found within the `content_for` blocks. This allows us to indent content in our ERB templates which should make them easier to read and work with.

After making the change I ran all the regression tests. There were a number of differences in the rendered govspeak outcomes as some of our templates already contain some leading spaces. I reviewed each change and committed them once I was happy that they didn't affect the HTML that's ultimately generated.

The final commit demonstrates indenting the content in the overseas-passports ERB templates. If we're happy with the approach in this pull request then I'll exclude this final commit from master as this Smart Answer is actively being worked on at the moment.

There's one main (as far as I'm aware) limitation to this change in that it'll prevent us from using Markdown that relies on a number of leading spaces. Two examples that come to mind are indented list items and code blocks. I don't think we use these at the moment but it's worth bearing in mind that we'd have to do some work if we wanted to support them in future.

### CODE REVIEW

**Comment by chrisroos** [comment]
The build has failed because some of the checksum data is now out of date. I'll update that now.

**Comment by chrisroos** [comment]
@tadast: I'd be interested in whether you think these changes to overseas-passports would make your life any easier when making changes to that Smart Answer.

**Comment by tadast** [comment]
@chrisroos I checked it out locally and I think it's a lot easier to follow the conditional branch flows. I can also collapse code/text within conditional branches in my editor to reduce visual noise, this helps a lot in large erb files with conditional branches. So definitely :+1: for that.

Have you checked if the overall performance cost of this change is acceptable?

**Comment by chrisroos** [comment]
> Have you checked if the overall performance cost of this change is acceptable?

I haven't! I think I'll change the implementation to use `+` instead of `*` (I had no idea that there would be the noticeable difference that your benchmarks showed) and, convert a few of the larger flows and then run the regression tests for those flows before and after the change.

**Comment by chrisroos** [comment]
I've timed how long it takes to run the regression tests for two Smart Answers; comparing the YAML text, unindented ERB and indented ERB.

I ran each set of tests three times using `time` and have recorded the `real` figure from the output in this comment.

It's not scientific but unindented and indented ERB appear to take about the same amount of time, while YAML takes longer to render.

# check-uk-visa

## Unindented ERB

    $ git co master
    $ time RUN_REGRESSION_TESTS=check-uk-visa \
      ruby test/regression/smart_answers_regression_test.rb

* 0m35.575s
* 0m33.968s
* 0m36.378s
* __Average: 35.307__
  
## Indented ERB

    $ git co indent-erb-templates
    $ time RUN_REGRESSION_TESTS=check-uk-visa \
      ruby test/regression/smart_answers_regression_test.rb

* 0m35.739s
* 0m34.159s
* 0m33.002s
* __Average: 34.3__

## Before conversion to ERB

    $ git co affce36556e11a07f802fa7ba209a7a2aceab214~
    $ time RUN_REGRESSION_TESTS=check-uk-visa \
      ruby test/regression/smart_answers_regression_test.rb

* 0m46.128s
* 0m33.886s
* 0m34.573s
* __Average: 38.196__

# overseas-passports

## Unindented ERB

    $ git co master
    $ time RUN_REGRESSION_TESTS=overseas-passports \
      ruby test/regression/smart_answers_regression_test.rb

* 1m23.736s
* 1m18.246s
* 1m17.050s
* __Average: 79.677__

## Indented ERB

    $ git co indent-erb-templates
    $ time RUN_REGRESSION_TESTS=overseas-passports \
      ruby test/regression/smart_answers_regression_test.rb

* 1m18.641s
* 1m17.656s
* 1m19.415s
* __Average: 78.571__

## Before conversion to ERB

    $ git co d2aa54c6754f1c771af5da3697ed047cb640598a~
    $ time RUN_REGRESSION_TESTS=overseas-passports \
      ruby test/regression/smart_answers_regression_test.rb
    
* 1m52.068s
* 1m39.262s
* 1m38.806s
* __Average: 103.379__

**Comment by tadast** [comment]
Smartanswers pages are heavily cached in production, so it's just the initial requests that matter and if there is no evidence of a significant slowdown this will do well :+1:

**Comment by chrisroos** [comment]
Manually merged in 680b29fdae225617f07486c2d2ec10ae700679c4.

**Pull request closed without merging**
