### PR TITLE
Change Spanish translator link for register a birth and death

### PR DESCRIPTION
**Pull request by ikennaokpala**
This PR supersedes #2490

Trello Story: https://trello.com/c/nIdy7kh6/75-register-a-birth-abroad-spain-translators-link

* Change Spanish translator link in register a birth and death respectively

## Factcheck for Register-a-Birth

[Preview link](https://smart-answers-pr-2490.herokuapp.com/register-a-birth/y/spain/mother/yes/same_country) 
[GOV.UK](https://gov.uk/register-a-birth/y/spain/mother/yes/same_country) 

### Expected changes
* The link should change from:
https://www.gov.uk/government/publications/spain-list-of-lawyers to http://www.exteriores.gob.es/Portal/en/ServiciosAlCiudadano/Paginas/Traductoresas---Int%C3%A9rpretes-Juradosas.aspx

### Before
screen shot 2016-04-26 at 14 58 42

### After
 
screen shot 2016-04-26 at 14 59 22

## Factcheck for Register-a-Death

[Preview link](https://smart-answers-pr-2490.herokuapp.com/register-a-death/y/overseas/spain/same_country) 
[GOV.UK](https://gov.uk/register-a-death/y/overseas/spain/same_country) 

### Expected changes
* The link should change from:
https://www.gov.uk/government/publications/spain-list-of-lawyers to http://www.exteriores.gob.es/Portal/en/ServiciosAlCiudadano/Paginas/Traductoresas---Int%C3%A9rpretes-Juradosas.aspx

### Before
screen shot 2016-04-27 at 12 31 53

### After
 
screen shot 2016-04-27 at 12 31 23

### CODE REVIEW

**Comment by ikennaokpala** [comment]
This PR supersedes #2484

**Comment by ikennaokpala** [comment]
@gavancurley 

Kindly go through these pages 


Register-a-Birth
https://smart-answers-pr-2490.herokuapp.com/register-a-birth/y/spain/mother/yes/same_country
https://smart-answers-pr-2490.herokuapp.com/register-a-birth/y/spain/mother/no/same_country
https://smart-answers-pr-2490.herokuapp.com/register-a-birth/y/spain/father/yes/same_country
https://smart-answers-pr-2490.herokuapp.com/register-a-birth/y/spain/mother_and_father/yes/same_country
https://smart-answers-pr-2490.herokuapp.com/register-a-birth/y/spain/mother_and_father/no/same_country
https://smart-answers-pr-2490.herokuapp.com/register-a-birth/y/spain/mother/yes/in_the_uk
https://smart-answers-pr-2490.herokuapp.com/register-a-birth/y/spain/mother/no/in_the_uk
https://smart-answers-pr-2490.herokuapp.com/register-a-birth/y/spain/father/yes/in_the_uk
https://smart-answers-pr-2490.herokuapp.com/register-a-birth/y/spain/mother_and_father/yes/in_the_uk
https://smart-answers-pr-2490.herokuapp.com/register-a-birth/y/spain/mother_and_father/no/in_the_uk


Register-a-Death
https://smart-answers-pr-2490.herokuapp.com/register-a-death/y/overseas/spain/same_country
https://smart-answers-pr-2490.herokuapp.com/register-a-death/y/overseas/spain/in_the_uk
https://smart-answers-pr-2490.herokuapp.com/register-a-death/y/overseas/spain/another_country/taiwan

**Comment by floehopper** [comment]
Given that it looks as if there is already test coverage for this change in the integration test (i.e. `assert_state_variable :translator_link_url, 'xxx'`), I don't think I would bother adding `spain` to the regression test responses. So I think you could get away with just the first commit. Does that make sense?

I think it might be legitimate to add `spain` to the regression test responses locally if you wanted to see which pages are affected, but I don't think I'd commit the changes to the repo.

**Comment by ikennaokpala** [comment]
@floehopper yes that makes sense to me

**Comment by gavancurley** [comment]
Thanks Ikenna - those all look good.

**Comment by ikennaokpala** [comment]
@gavancurley thanks for the update

**Comment by pmanrubia** [comment]
Following the comment from @floehopper in https://github.com/alphagov/smart-answers/pull/2490#issuecomment-215058466, and your answer in https://github.com/alphagov/smart-answers/pull/2490#issuecomment-215059019, is there any particular reason why you have committed the test artefacts for Spain?
I am not saying you should not do it, but I am curious to know if you find any particular reason to do it.

**Comment by ikennaokpala** [comment]
@pmanrubia @floehopper  done and also rebased with current master in in partial fulfilment for merge

**Pull request merged**
