### PR TITLE
Add step to apply for an overseas passport for child in Afghanistan

### PR DESCRIPTION
**Pull request by er-ke-de**
For further details see:
  https://www.pivotaltracker.com/n/projects/1270592/stories/105008654

## Expected changes

* [Example URL](https://www.gov.uk/overseas-passports/y/afghanistan/applying/child/afghanistan)
  * Under How to Apply, a step # 5 with a link to a parent contact details form appears

screen shot 2015-10-20 at 4 11 26 pm

### CODE REVIEW

**Comment by chrisroos** [comment]
Do you need to update the regression test artefacts for this change too, @erik-eide?

**Comment by erik-eide** [comment]
Yep, I just added a new commit with a response that regresses through the new path

**Comment by chrisroos** [comment]
I hope you don't mind, @erik-eide, but I've had a go at illustrating what I meant when I talked about updating the regression tests to see the effect of this change.

See PR #2028 for a worked example of how we can temporarily update the regression tests to test the effect of a change.  It turns out to be overkill in this instance but the technique can be useful when we're making changes that can affect multiple outcomes; particularly when a change inadvertently affects an outcome that we don't expect it to.

If I was going to suggest a small change to this PR then I think it'd be good to squash the two commits. I don't think there's any real value in adding "afghanistan" to the questions-and-responses file in the first commit but then only generating the regression tests in the second.

All that aside, the actual change in this commit looks good and I apologise that the regression tests have made such a small change feel so painful!

**Comment by er-ke-de** [comment]
I think normally, I would of liked of to have squashed the commits for the reason you had given, but given we had a comment on the PR about them not being updated, I left them as 2 intentionally to show in the history.

Have squashed them now, thanks for the examples and docs on getting it right!

**Comment by floehopper** [comment]
Looks good to me :+1:

**Pull request merged**
