### PR TITLE
Convert pay-leave-for-parents to Ruby

### PR DESCRIPTION
**Pull request by chrisroos**
This PR converts the final Smartdown flow (pay-leave-for-parents) to Ruby. Although it’s really quite large I hope the commits are relatively easy to follow. I’m fairly confident that the converted Smart Answer mirrors the original as the only regression test artefact changes are due to spaces and blank lines.

I’m convinced this code can be improved but I’ve tried to make this as much of a one-to-one conversion from Smartdown as possible.

Here’s an overview of the changes:

* First 7 commits update the Smartdown conversion tool to cope with additional requirements of the pay-leave-for-parents Smart Answer.

* Next 2 commits use the Smartdown conversion tool to generate the Ruby version of pay-leave-for-parents, and to rename the Smartdown version so that the names don’t clash.

* Next 7 commits manually copy the next node rules from the Smartdown questions to the Flow.

* Next 2 commits reorder the flow so that `employment_status_of_mother` and `employment_status_of_partner` appear in the code in the order they appear in the flow.

* Next commit adds `save_input_as` to all questions. This should make the conversion easier at it replicates Smartdown functionality.

* Next commit updates the flow class name.

* Next commit adds a placeholder calculator to the flow.

* Next 11 commits add `precalculate` blocks to questions to ensure question text interpolation works as expected. This involves copying methods to the calculator where appropriate.

* Next 7 commits replace the commented out `next_node` logic with equivalent Ruby code.

* Next 7 commits add permitted next nodes to the questions that use `next_node` with a block.

* Next 7 commits replace Smartdown conditionals (e.g. `$IF`) with ERB in outcome partials.

* Next 5 commits replace YAML interpolation tags with ERB in outcome partials.

* Next 2 commits add a script to convert the Smartdown scenarios to integration tests, and the converted integration tests.

* Next commit updates responses and expected results.

* Next commit moves the outcomes to their own directories. This is a change that’s happened in master since this branch was created.

* Next commit updates checksum data.

* Next commit reverts change to preload flows if running regression tests for pay-leave-for-parents. This is no longer necessary now that it’s been converted to Ruby.

* Next 13 commits manually rename pay-leave-for-parents test artefact directories. This should make it easier to see if there are any important differences when the regression tests run.

* Next 3 commits manually update pay-leave-for-parents test artefacts for questions, to find/replace date and salary amounts. This should make it easier to see if there are any important differences when the regression tests run.

* Next commit contains the updated regression test artefacts for pay-leave-for-parents. Because of the manual renaming of test artefacts, this diff only contains blank lines and spaces.

* Next commit removes the pay-leave-for-parents Smartdown flow.

* Next 3 commits fix Rubocop violations that I'd introduced in this PR.

* Final commit updates the checksum data based on the changes introduced by the Rubocop fixes.

### CODE REVIEW

**Comment by chrisroos** [comment]
I realised after pushing that I'd introduced some Rubocop violations. I've pushed another 3 commits to fix them and will update the PR description to reference those commits.

**Comment by floehopper** [comment]
Observation: I think the mixture of using `save_input_as` in combination with stateless instance methods on the calculator is a bit odd and probably something we want to move away from, but for now I think it's more important to get this merged.

**Comment by floehopper** [comment]
This looks great to me. Good work!

The majority of my comments are very minor and could probably be ignored, but I think I would like to see the `SmartdownPlugins::PayLeaveForParentsTest` translated into a unit test for the new `SmartAnswers::Calculators::PayLeaveForParentsCalculator` as per this comment: https://github.com/alphagov/smart-answers/commit/bd35394e6e48047253d3871783c998ddf3853bc1#commitcomment-14007143.

**Comment by chrisroos** [comment]
Thanks for the review, @floehopper. I think I've addressed all your comments.

I've rebased on master and force-pushed in preparation for merging.

**Comment by floehopper** [comment]
Boom! :boom: :tada: :balloon: :balloon:

**Pull request merged**
