### PR TITLE
Update appointment links for same sex outcomes

### PR DESCRIPTION
**Pull request by erikse**
PT story: https://www.pivotaltracker.com/story/show/109437994

For same-sex marriage outcomes in Azerbaijan, Bolivia, Chile, Estonia, Hungary, Kosovo, Latvia, Lithuania, Malta and Serbia - add link for customers to book an embassy appointments, and remove the embassy address at the same time.

## Fact check

https://pt-109437994.herokuapp.com/marriage-abroad/y

## Expected changes
 [URL on gov.uk](https://www.gov.uk/marriage-abroad/y/serbia/ceremony_country/partner_british/same_sex)
  * Removes embassy address
  * Removes embassy telephone number(s)
  * Removes embassy email address removed
  * Removes link to embassy opening hours
  * Adds link to book embassy appointments

### Before
screen shot 2016-02-02 at 5 24 46 pm

### After
screen shot 2016-02-02 at 5 26 21 pm

### CODE REVIEW

**Comment by erikse** [comment]
@chrisroos I just rebased it, looks fine, all the regression tests ran without any changes

**Comment by chrisroos** [comment]
That's great, @erikse. I'm glad it wasn't too painful.

**Comment by erikse** [comment]
This has been approved by fact check, ready for code review :pencil2: :book: :pray:

**Comment by erikse** [comment]
Have just rebased this with master

**Comment by chrisroos** [comment]
Looks good to me!

**Pull request merged**
