### PR TITLE
Update worldwide location organisation data

### PR DESCRIPTION
**Pull request by chrisroos**
I've occasionally found it useful to generate regression test artefacts for all countries in marriage-abroad (when I make a change that affects every outcome, for example). Each time I do that I have to add the worldwide organisation fixture data (stored in test/fixtures/worldwide) for each of the new countries. This branch updates the existing organisation fixture data and adds new fixtures for all countries stored in worldwide_locations.yml. This will make life easier when generating regression test artefacts for all countries in marriage-abroad.

This builds on PR #2448, which I hope/plan to merge first. Without the changes to worldwide_organisation_test.rb in that PR, updating this organisation data causes some of those tests to fail.

Updating these fixtures has resulted in changes to the regression test artefacts for marriage-abroad, overseas-passports, register-a-birth, register-a-death and report-a-lost-or-stolen-passport. For all but marriage-abroad I've also had to update the checksum data as it contains links to the organisation fixtures that those flows rely on. This seems somewhat inconsistent but I plan to address that separately.

### CODE REVIEW

**Comment by floehopper** [comment]
It looks as if you might've forgotten to update the regression test checksums for `marriage-abroad`.

**Comment by floehopper** [comment]
Minor: I think I might've been inclined to group the commit updating the regression test checksums for a flow with the commit updating the regression test artefacts for the same flow. That way it would've been easier to see that the `marriage-abroad` checksums hadn't been updated.

**Comment by floehopper** [comment]
Minor: I think it would be good to explain in the commit notes why the regression test artefacts have been updated i.e. because the worldwide location organisation data has been updated.

**Comment by floehopper** [comment]
Minor: I would prefer the commit note subject lines to be "Update regression test checksums for overseas-passports-files" rather than "Update overseas-passports-files.yml". The latter could easily be gleaned just by looking at the diff.

**Comment by floehopper** [comment]
I've just noticed that you explained why you didn't have to update the regression test checksums for `marriage-abroad` in the PR description, so please ignore my earlier comment.

**Comment by floehopper** [comment]
Aside: Is it worth considering some kind of automated updating of this fixture data or at least a check that it is up-to-date? I only mention this, because it looks as if much of it hasn't been updated for quite some time.

**Comment by floehopper** [comment]
Other than my mostly minor comments above, this looks good to me. 👍

**Comment by chrisroos** [comment]
I'm closing this in order to rebase the branch on master and address @floehopper's feedback.

**Comment by chrisroos** [comment]
> Minor: I think I might've been inclined to group the commit updating the regression test checksums for a flow with the commit updating the regression test artefacts for the same flow. That way it would've been easier to see that the marriage-abroad checksums hadn't been updated.

I've combined the commits that update the regression test artefacts with those that update the checksum data. I've rewritten the commit message of the the commit that updates the marriage-abroad regression test artefacts to explain that I don't need to update the checksum data - https://github.com/alphagov/smart-answers/pull/2472/commits/9b5a6c238a8c983b050e2c14486008d1926f66ae

**Comment by chrisroos** [comment]
> Minor: I think it would be good to explain in the commit notes why the regression test artefacts have been updated i.e. because the worldwide location organisation data has been updated.

Addressed in:

* https://github.com/alphagov/smart-answers/pull/2472/commits/9b5a6c238a8c983b050e2c14486008d1926f66ae
* https://github.com/alphagov/smart-answers/pull/2472/commits/b947e90a40522a8bab1158f0c8503b6a6f900d12
* https://github.com/alphagov/smart-answers/pull/2472/commits/f7ce0d2726294000201bc0392979d79be89e1762
* https://github.com/alphagov/smart-answers/pull/2472/commits/858f554d471c8c7e517b0f3a2a62456c7eb14a04
* https://github.com/alphagov/smart-answers/pull/2472/commits/50de4c8f4e594f09e0bb0eada5d2affdc249adc2

**Comment by chrisroos** [comment]
> Minor: I would prefer the commit note subject lines to be "Update regression test checksums for overseas-passports-files" rather than "Update overseas-passports-files.yml". The latter could easily be gleaned just by looking at the diff.

This has been addressed as a side-effect of combining the commits that update the regression test artefacts with those that update the checksum data, in PR #2472.

**Comment by chrisroos** [comment]
> Aside: Is it worth considering some kind of automated updating of this fixture data or at least a check that it is up-to-date? I only mention this, because it looks as if much of it hasn't been updated for quite some time.

I think this might be a good idea. I've captured it in a Trello card for now - https://trello.com/c/LoxEFha7.

**Comment by chrisroos** [comment]
Thanks for the review, @floehopper. I've addressed your comments, rebased on master and opened PR #2372 in preparation for merging to master.

**Pull request closed without merging**
