### PR TITLE
Marriage abroad amends Bulgaria

### PR DESCRIPTION
**Pull request by erikse**
PT story: https://www.pivotaltracker.com/story/show/109437586

This PR changes the outcome content for opposite sex marriages for Bulgarian and non-UK residents in Bulgaria.

## Factcheck

https://powerful-dusk-4063.herokuapp.com/marriage-abroad/y/bulgaria/

## Expected changes
 * [URL on gov.uk](https://www.gov.uk/marriage-abroad/y/bulgaria/ceremony_country/partner_british/opposite_sex)
  * Adds the name/location of the local authorities to contact for getting married

### Before
screen shot 2015-12-18 at 2 28 38 pm

### After
screen shot 2015-12-18 at 2 28 43 pm

 * [URL on gov.uk](https://www.gov.uk/marriage-abroad/y/bulgaria/ceremony_country/partner_british/opposite_sex)
  * Adds a link to making an appointment at embassy
  * Adds a link of required documents

### Before
screen shot 2015-12-18 at 2 30 19 pm

### After
screen shot 2015-12-18 at 2 30 22 pm

 * [URL on gov.uk](https://www.gov.uk/marriage-abroad/y/bulgaria/ceremony_country/partner_british/opposite_sex)
  * Updates the fee payment methods

### Before
screen shot 2015-12-18 at 2 33 47 pm

### After
screen shot 2015-12-18 at 2 34 04 pm

### CODE REVIEW

**Comment by floehopper** [comment]
I think this PR is missing updates to the regression test artefacts.

**Comment by floehopper** [comment]
Other than my comments, this looks good to me.

**Comment by chrisroos** [comment]
@erikse: Let me know if you'd like me to rebase this now that my changes to marriage-abroad have been merged to master.

**Comment by erikse** [comment]
@floehopper - there are no artefact changes as the regression tests don't include Bulgaria. In a previous PR created around this same time, I had a review flag that adding a country to the regression tests that didn't change the logic, or include any new outcome, was unnecessary. It would be good to clarify if this has changed.

**Comment by erikse** [comment]
Have just rebased this with master. The regression suite shows no changes to existing artefacts for all other countries, but as mentioned in my comment, this PR doesn't add Bulgaria to the regression tests.

**Comment by chrisroos** [comment]
> In a previous PR created around this same time, I had a review flag that adding a country to the regression tests that didn't change the logic, or include any new outcome, was unnecessary. It would be good to clarify if this has changed.

I'm not saying that we should use it in this branch, but one technique we've used in the past is to:

1. Generate regression test artefacts for the country affected (i.e. Bulgaria).
2. Make the change and regenerate the artefacts to ensure that things have changed as expected.
3. Remove the regression test artefacts for the country affected.

There's an illustration of this technique in PR #2028. 

@erikse: I agree that clarifying/documenting this approach would be useful. Can you find a link to the comment that said it wasn't necessary to add regression tests for a new country?

**Comment by erikse** [comment]
@chrisroos this is the last time I remember seeing one mentioning not adding new countries https://github.com/alphagov/smart-answers/commit/e5f5732e882959e6e8f22c4351f56096cb28b128#commitcomment-14954333

**Comment by erikse** [comment]
Thinking about this a little more, we now have a set of conditional statements in the ERB templates that aren't exercised, so maybe adding countries to the regression tests is the right thing to do whilst these are the way we test

**Comment by chrisroos** [comment]
> Thinking about this a little more, we now have a set of conditional statements in the ERB templates that aren't exercised, so maybe adding countries to the regression tests is the right thing to do whilst these are the way we test

I agree that adding Bulgaria to the marriage-abroad regression tests sounds like the right thing to do in this case.

**Comment by pmanrubia** [comment]
Nice PR @chrisroos: real data is always helpful.

If we are able to exercise all our codebase without the need to check the content of every page, I’d say we would have a good balance between code coverage and fast tests.

A 4 minutes increase in regression tests would not be very painful for a flow that is not under active development, but following the same approach to other flows would impact the speed of our tests.

We are currently double checking the content in every PR, in every release (in staging and in production) and also by the content team with fact-checks; so I would be good with selecting the answers that exercise all our branches, and relying on human review for content changes?

So, If I would need to pick up an approach for test coverage in our tests, I would do what @erikse and @chrisroos discussed in https://github.com/alphagov/smart-answers/pull/2200#issuecomment-199122150: update the answers to cover any new branch in our templates.

**Comment by floehopper** [comment]
In @erikse's absence, it would be good if someone could take ownership of this PR. It looks as if the following things need doing:

* Add Bulgaria to the regression test paths as discussed by @erikse & @chrisroos in the comments above.
* Rebasing against master to bring it up-to-date with the latest code and to resolve the conflict identified by GitHub. The original changes are now very old - they were done in December last year.
* It doesn't look as if there are any commit-specific comments, so it's probably safe to force-push to the same branch and PR.

**Comment by floehopper** [comment]
I'm going to un-assign myself from this on GitHub, because I'm no longer reviewing this PR. I tend to use the assignment flag to try to avoid two people accidentally reviewing the same PR.

**Comment by chrisroos** [comment]
I've added a comment to the Pivotal Tracker story to ask whether we're expecting to hear back from FCO about this.

**Comment by chrisroos** [comment]
It seems as though this might have been superseded by PR #2414. I've asked for confirmation in the [Trello card associated with PR 2414](https://trello.com/c/EpD6CVwE).

**Comment by ikennaokpala** [comment]
Superseded by #2414

**Pull request closed without merging**
