### PR TITLE
Refactor register-a-death to new-style flow

### PR DESCRIPTION
**Pull request by floehopper**
## Description

Trello card: https://trello.com/c/jjPO9Leq

Similar to #2619, this moves the flow towards the style described in the [refactoring documentation][1]. I've concentrated on moving logic out of the flow and into the calculator and presentational concerns into the templates. The idea is to change all the flows to use this approach so we can significantly simplify the DSL.

In this case, I haven't done much work on the calculator itself other than extracting methods from the flow into it. Also I haven't attempted to extract any domain concepts. Some of the logic could almost certainly be simplified. There is still quite a bit of work to do to move all the *tests* for this flow towards the [new-style approach][2].

In extracting logic into the new calculator class, I've tried to keep things as similar as possible to the calculator class for `register-a-birth`. In fact this refactoring has made it clear that there is quite a bit of duplication between the two which could almost certainly be removed.

Although the PR has a lot of commits, the vast majority of them are very small and only affect a few files. Also because of the similarities between this flow and `register-a-birth`, I've tried to structure the commits in a similar way as when I refactored `register-a-birth`.

## External changes

None. This is just an internal refactoring.

[1]: https://github.com/alphagov/smart-answers/blob/master/doc/refactoring.md
[2]: https://github.com/alphagov/smart-answers/blob/master/doc/new-style-testing.md

### CODE REVIEW

**Comment by floehopper** [comment]
I've used an interactive rebase to fix the Rubocop offence in the relevant commit and have force-pushed.

**Comment by floehopper** [comment]
And now I've amended the final commit to update the checksums and force-pushed. Hopefully the latest build should pass.

**Comment by chrisroos** [comment]
Looks good to me, @floehopper.

**Comment by floehopper** [comment]
Rebasing against master and force-pushing in preparation for merging.

**Pull request merged**
