### PR TITLE
Added info about how to get a copy of a birth or death certificate

### PR DESCRIPTION
**Pull request by hannahwhittaker**
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

I've updated the outcomes for the registering a birth and death abroad smart answers to include a sentence about how to get a copy of a birth or death certificate. 

I've also updated the negative contractions in the registering a birth outcome.

### CODE REVIEW

**Review by theseanything — APPROVED** [review]

**Comment by hannahwhittaker** [comment]
Please don't merge or deploy, I need to get the previews fact checked by the department.

**Comment by theseanything** [comment]
@hannahwhittaker no worries! Just a tip - if you are still working on a PR and want to make sure it doesn't get merge, you can make it a draft 
image

**Comment by hannahwhittaker** [comment]
Amazing, thanks @theseanything! I didn't know I could do that!

**Comment by hannahwhittaker** [comment]
The dept have approved these changes, they can be merged and deployed whenever.

**Pull request merged**
