### PR TITLE
Updates for simplified expenses smart answer

### PR DESCRIPTION
**Pull request by robinjam**
[Trello card](https://trello.com/c/8Hgtl17t/280-updates-for-simplified-expenses-smart-answer)

## Description

Update content and logic in https://www.gov.uk/simplified-expenses-checker

Draft updates in https://docs.google.com/document/d/1Cp0ySNHoKdptPSXuVVDaTnak-bmW7czTM6F2m0WWUtM/edit?ts=57a89e7d

## Factcheck

* [Preview version for factcheck](https://smart-answers-pr-2705.herokuapp.com/simplified-expenses-checker)
* [Live version on gov.uk](https://www.gov.uk/simplified-expenses-checker)

## Expected changes

* Split "yes" decision in question 3 (are you buying a new car?) into "new" and "used" options
* Change question 6 (is the car you're buying green?) to ask about the car's emissions
* Update logic in "calculating expenses the usual way" for vehicles with high emissions

### Question 3

* Split "yes" decision in question 3 (are you buying a new car?) into "new" and "used" options

#### Before

Q3 before

#### After

Q3 after

### Question 6

* Change question 6 (is the car you're buying green?) to ask for the car's emissions figure

#### Before

Q6 before

#### After

Q6 after

### Main outcome

* Update logic in "calculating expenses the usual way" for vehicles with high emissions
* Before: user is entitled to £1,440
  * £10,000 (cost of vehicle) \* 80% (vehicle is used for business 80% of the time) \* **18%** (because the vehicle is not "green")
* After: user is entitled to £640
  * £10,000 (cost of vehicle) \* 80% (vehicle is used for business 80% of the time) \* **8%** (because the vehicle has high emissions)

#### Before

Main outcome before

#### After

Main outcome after

### CODE REVIEW

**Comment by leenagupte** [comment]
Just a few things:

1. Add an integration test for the "filthy" car flow.
2. Add tests that check the calculated amounts for filthy cars:
 - the write off cost
 - the vehicle price
 - the simple scheme costs
and so on.  Ideally these tests would be separate unit tests, but for now they can be added to the integration tests.
3. Fix up commit 5556dac to amend the DVLA link wording into df162cf.
4. Fix up commit 8e952c6 to resolve the lint warning into 922f76d
5. Expand the commit messages in 922f76d, df162cf, 	9971167 and 594db7b. Give more detail about what has changed, and if you can, why.
For example, in commit df162cf, mention that the question is changing from a yes/no question to a multipart radio button because the amount that the user can claim in expenses for their vehicle depends on it's CO2 emissions, of which there are three bands.... or something similar.

**Comment by leenagupte** [comment]
@robinjam Thanks for making the suggested changes.  

There a few more changes needed to the structure of the commits, before I can really review this.

In commits 94606cc and 6e023bf, I'm sure you must have made changes to the integration tests to get them to pass, and had to regenerate the checksum file. However, due to the sheet number of changes to the test artefacts, it's impossible to view these changes on github.

Can you split the changes to the test artefacts and the checksums into a separate commits? It's fine, to just have one commit at the end for the checksum update.

Thanks!

**Comment by robinjam** [comment]
@leenagupte Thanks for the tips. I've moved the regression test artefact+checksum changes to a separate commit and rewritten some of the commit messages for clarity.

**Comment by pmanrubia** [comment]
Hi @robinjam,

This PR is a bit difficult to review (1876 files to review in the last commit)

Why don't you give a try to:

1. In dda714032635c225dba40e328928da663f175b9b: Update the artefacts in this commit. If they are still too many (or they are difficult to review), would you think on a different way to split this commit? As a side note, the calculation `new_or_used` is not used in the commit
2. In 916f0504ca220e43c90adaa9355dc31e53e78712, Update the artefacts in this commit. If they are still too many (or they are difficult to review), would you think on a different way to split this commit?
3. In a64133fc5f8ea0ea9be219e0a038ca216a166d67, could you please add a test for `Money.new(vehicle + green + dirty + filthy + home)`? Again same comments as above about regression tests. I would expect to have changes in the artefacts here with the right amount of the new calculations.
3. In 31d6c37f4395e654ebd3c74d1f89145a11cb4071 Update artefacts and checksums in this commit.

Feel free to ping me if you need support with it.

**Comment by ikennaokpala** [comment]
Closing this PR as it is being superseded by #2716

**Pull request closed without merging**
