### PR TITLE
Remove example draft smartdown flows

### PR DESCRIPTION
**Pull request by floehopper**
The plan is to phase out Smartdown flows. These flows are marked as "draft" so they don't currently appear in production. Also they're clearly not intended to ever be deployed to production. So I think it's safe to remove them.

### CODE REVIEW

**Comment by chrisroos** [comment]
Can we also remove the animal-example-multiple and animal-example-simple folders from the smartdown_plugins directory?

**Comment by chrisroos** [comment]
There also appear to be a number of tests that are trying to use "animal-example-simple", although I don't really understand how this PR says all the tests passed if that's really true. Maybe "animal-example-simple" is also defined as a flow in test somewhere...?

```bash
$ grep -R animal-example . | grep -v .git | grep -v .bundle | grep -v log
./test/integration/smartdown_flows/question_types_test.rb:    visit smart_answer_path(id: "animal-example-simple")
./test/unit/smartdown_adapter/flow_registration_presenter_test.rb:        flow = SmartdownAdapter::Registry.instance(flow_registry_options).find("animal-example-simple")
./test/unit/smartdown_adapter/presenter_test.rb:        @flow = SmartdownAdapter::Registry.instance(flow_registry_options).find("animal-example-simple")
./test/unit/smartdown_adapter/presenter_test.rb:          assert_equal "animal-example-simple", @presenter.name
./test/unit/smartdown_adapter/presenter_test.rb:          assert_equal "animal-example-simple", @presenter.name
./test/unit/smartdown_adapter/presenter_test.rb:          assert_equal "animal-example-simple", @presenter.name
./test/unit/smartdown_adapter/registry_test.rb:      flow1 = instance.find("animal-example-simple")
./test/unit/smartdown_adapter/registry_test.rb:      flow2 = instance.find("animal-example-simple")
./test/unit/smartdown_adapter/registry_test.rb:      flow1 = instance.find("animal-example-simple")
./test/unit/smartdown_adapter/registry_test.rb:      flow2 = instance.find("animal-example-simple")
./test/unit/smartdown_adapter/registry_test.rb:      assert instance.flows.any? { |flow| flow.name == 'animal-example-simple' }
./test/unit/smartdown_adapter/registry_test.rb:      refute instance.flows.any? { |flow| flow.name == 'animal-example-simple' }
./test/unit/smartdown_adapter/registry_test.rb:      refute instance.flows.any? { |flow| flow.name == 'animal-example-simple' }
./test/unit/smartdown_plugins/animal-example-multiple_test.rb:require 'smartdown_plugins/animal-example-multiple/render_time'
```

**Comment by floehopper** [comment]
@chrisroos: Confusingly `animal-example-simple` is also defined as a [fixture flow](https://github.com/alphagov/smart-answers/tree/master/test/fixtures/smartdown_flows/animal-example-simple). Apart from `SmartdownPlugins:: AnimalExampleMultipeTest` which tests the plugin class directly, the tests that you list either call the `TestFixturesHelper#use_test_smartdown_flow_fixtures` method or set the `SmartdownAdapter::Registry` `smartdown_load_path ` option which means they use the fixture version:

* https://github.com/alphagov/smart-answers/blob/master/test/integration/smartdown_flows/question_types_test.rb#L5
* https://github.com/alphagov/smart-answers/blob/master/test/unit/smartdown_adapter/flow_registration_presenter_test.rb#L7-L13
* https://github.com/alphagov/smart-answers/blob/master/test/unit/smartdown_adapter/presenter_test.rb#L9-L14
* https://github.com/alphagov/smart-answers/blob/master/test/unit/smartdown_adapter/registry_test.rb#L9

**Comment by floehopper** [comment]
@chrisroos: I think you're right about removing the plugins, although looks like I might need to remove a test or two as well. I'll do that shortly and add it to this PR. Thanks.

**Comment by floehopper** [comment]
I've addressed @chrisroos' point about the plugins and updated the first commit note to mention the fixture flow with the same name. I've also rebased against master and force-pushed in preparation for merging.

**Pull request merged**
