### PR TITLE
Update list of tier 4 visa sponsoring establishments

### PR DESCRIPTION
**Pull request by erikse**
PT story: https://www.pivotaltracker.com/story/show/111519804

Updates the list of sponsoring establishments and their application methods for Tier 4 visas.

## Fact check

https://pt-111519804.herokuapp.com/apply-tier-4-visa

## Expected changes
 * [URL on gov.uk](https://www.gov.uk/apply-tier-4-visa/y/extend_general/V6G1G9F62)
  * The Moat School is now capitalised

### Before
screen shot 2016-01-16 at 8 56 03 am

### After
screen shot 2016-01-18 at 10 02 00 am

Note: This PR supersedes #2237

### CODE REVIEW

**Comment by keithiopia** [comment]
Sent to Home Office for factchecking.

**Comment by keithiopia** [comment]
Home Office have approved the changes.

**Comment by tadast** [comment]
This looks ok to merge from the code perspective, but do some entities really need to be all caps? 

Looking at [this file](https://github.com/alphagov/smart-answers/blob/johnploughman_patch_2/lib/data/apply_tier_4_visa_data.yml) it doesn't seem to be consistent. Perhaps thats for @keithiopia to answer?

**Comment by keithiopia** [comment]
@tadast I'm not particularly happy about the inconsistency in case either. I think there are also typos. The Home Office assured me that they'll be sending me a cleaned up version at some point, so this is just an interim to correct the missing or incorrect sponsors.

**Comment by tadast** [comment]
:+1:

**Comment by erikse** [comment]
I've just rebased this with the master branch and force pushed back to the branch of this PR

**Pull request merged**
