### PR TITLE
Live has been removed use on instead

### PR DESCRIPTION
**Pull request by edds**
Live is removed in the next version of jQuery, use on instead which has
the same behaviour.

http://jquery.com/upgrade-guide/1.9/#live-removed

### CODE REVIEW

**Comment by tadast** [comment]
Have you tested that this works as intended? 

It looks correct to me, but according to the docs you've linked to the preferred syntax is ` $(document).on('submit', formSelector, function(event){...}`. I believe this syntax also works in case `formSelector` content is added via ajax/pjax.

**Comment by edds** [comment]
@tadast you are indeed correct, in my head I thought I was changing `bind` to `on`. Have updated it to properly delegate rather than bind the events.

**Comment by tadast** [comment]
:cool: Looks good to me now :+1:

**Comment by chrisroos** [comment]
@edds: I don't suppose you'd be able to add some JS tests around this functionality? I realise this would be a pain because there aren't any similar tests at the moment.

**Comment by edds** [comment]
@chrisroos without rewriting all the JavaScript, no. There is no way to tie into the JavaScript as it is all just run on load rather than following our styleguide of being encapsulated methods which can then be unit tested.

**Comment by chrisroos** [comment]
@edds: Fair enough!

**Pull request merged**
