### PR TITLE
Remove apply-for-probate Smart Answer

### PR DESCRIPTION
**Pull request by chrisroos**
This was created on 26th Sep 2012 and hasn't been touched since 14th Jan 2013.

Gwen and Alex have confirmed that this can be removed.

### CODE REVIEW

**Comment by chrisroos** [comment]
My motivation for opening this pull request is to run the tests and to see whether people spot anything else that can be removed in this branch.

**Comment by floehopper** [comment]
LGTM. I can't see anything else which can be removed.

**Comment by tadast** [comment]
:+1:

**Comment by chrisroos** [comment]
Manually merged in 452f9d871054719a018910301b258464874fae1e.

**Pull request closed without merging**
