### PR TITLE
Replace standard visitor with short-term study (Content and Link) For Taiwan

### PR DESCRIPTION
**Pull request by ikennaokpala**
Zenddesk Story:  https://govuk.zendesk.com/agent/tickets/1287220
Trello Story:  https://trello.com/c/2NNNCDPL/67-change-study-visa-link

* Changed visa needed from standard visitor to short-term study.

## Factchecks
https://smart-answers-pr-2398.herokuapp.com/check-uk-visa/y/taiwan/school 
https://smart-answers-pr-2398.herokuapp.com/check-uk-visa/y/taiwan/schootourism
https://smart-answers-pr-2398.herokuapp.com/check-uk-visa/y/taiwan/medical
https://smart-answers-pr-2398.herokuapp.com/check-uk-visa/y/taiwan/study/six_months_or_less

### Expected changes
* [GOV.UK](//gov.uk/check-uk-visa/y/taiwan/school)
*  Replace visa standard visitor with short-term study.

### Before
screen shot 2016-03-22 at 17 04 09

### After
screen shot 2016-03-22 at 17 04 27

### CODE REVIEW

**Comment by keithiopia** [comment]
This doesn't need a factcheck with the department, and the preview looks good to me. 
GTG.

**Comment by ikennaokpala** [comment]
@keithiopia Thanks for letting us know will move on with code review..

**Comment by floehopper** [comment]
Minor: I think the commit note subject line for the first commit should mention "Taiwan, because as far as I can see that's the only outcome that is changing.

**Comment by floehopper** [comment]
Minor: I think the PR title should mention "Taiwan" and it could probably be less detailed e.g. "Content changes for Taiwan outcome in Check UK Visa".

**Comment by floehopper** [comment]
Very minor: The browser developer tools in the screenshots are a bit distracting.

**Comment by floehopper** [comment]
Other than my minor comments, this looks good to me. :+1:

**Pull request merged**
