### PR TITLE
Smartdown money question type

### PR DESCRIPTION
**Pull request by robmckinnon**
* REQUIRES this [smartdown money question PR 131](https://github.com/alphagov/smartdown/pull/131) to have been merged on smartdown gem.
* Adds support for new smartdown money question type.
* Required for possible MOJ fee remission smartanswers - see smartdown issue [#128](https://github.com/alphagov/smartdown/issues/128)

### CODE REVIEW

**Comment by robmckinnon** [comment]
Adding some further tests. Not yet committed.

**Comment by robmckinnon** [comment]
Have added further tests in the `smartdown` repository. Ready for merge now.

**Comment by dsingleton** [comment]
[Smartdown 0.13.0](https://rubygems.org/gems/smartdown/versions/0.13.0) is available now, with `Money` question support

**Comment by robmckinnon** [comment]
This pull request is ready to be merged now, as `money` question functionality is now in [Smartdown 0.13.0](https://github.com/alphagov/smartdown/blob/master/CHANGELOG.md#0130).

**Comment by dsingleton** [comment]
I pushed a [version of your branch](https://github.com/alphagov/smart-answers/compare/moj-money-question?expand=1) (rebased against master) so it runs through our CI - all passes and looks good. :+1:

**Comment by dsingleton** [comment]
Also, thank you again for the contribution, this has been great

**Pull request merged**
