### PR TITLE
Replaced 'vehicle weight' with 'vehicle MAM'

### PR DESCRIPTION
**Pull request by keithiopia**
__This has been superseded by PR #2074.__

Comes from: https://govuk.zendesk.com/agent/tickets/1127165

### CODE REVIEW

**Comment by erik-eide** [comment]
Can we check if this change from weight to MAM should be applied across all outcomes, as this change only effects 2:

For example, would still say 'weight'.

https://www.gov.uk/towing-rules/y/medium-sized-vehicle/yes/under-21

**Comment by chrisroos** [comment]
I've emailed Keith to ask whether these changes are ready to be deployed, or whether we're still waiting on feedback.

**Comment by chrisroos** [comment]
I've got confirmation from John that this is good to be deployed.

**Comment by chrisroos** [comment]
This has been superseded by PR #2074. Closing.

**Pull request closed without merging**
