### PR TITLE
Unify marriage abroad fees content

### PR DESCRIPTION
**Pull request by erikse**
Pivotal Ticket: https://www.pivotaltracker.com/story/show/109438906

This PR is the second part of this ticket (following on from #2350) and brings together all the fee related content throughout the marriage abroad smart answer into one partial and allows outcomes to selectively enable which consular fees to show the user.

### CODE REVIEW

**Comment by erikse** [comment]
With #2350 now merged, this is ready for review

**Comment by chrisroos** [comment]
Very minor: In the note for commit 0b12c256b2c4b0b6bf720e648c5915199b5e7785 ("Regenerate test artefacts for marriage abroad") you've mentioned two expected space changes but I noticed another one:

```diff
-Performing a marriage ceremony| £140
+Performing a marriage ceremony | £140
```

**Comment by chrisroos** [comment]
This all looks great to me, @erikse. Hopefully this'll help avoid the fees getting out of sync in future.

The only minor comment I have is about the commit titles. I realise this is possibly/probably subjective but I would've tried to avoid some of the duplication you've ended up with.

Having been through the commits, I might've used titles like:

1192199 Add consular service fees table to marriage abroad
95ae22b Replace _fee_table_affirmation_55 with _consular_fees_table
cf114ba Replace _fee_table_affidavit_55 with _consular_fees_table
903d809 Replace _fee_table_oath_55 with _consular_fees_table
28b7730 Replace _fee_table_45_70_55 with _consular_fees_table
7b86a5e Replace affidavit_for_marriage fees in _fees with _consular_fees_table
e675778 Replace fees for Finland in _fees with _consular_fees_table
c085a32 Replace affirmation_for_freedom_to_marry fees in _fees with _consular_fees_table
f48b70c Replace _fee_table_os_germany with _consular_fees_table
37d4570 Remove duplication in os_affirmation/_fees
7d6ea0d Replace fees for China in _fees with _consular_fees_table
3f5738a Replace fees for Egypt in _fees with _consular_fees_table
62cfa7e Replace fees for Peru in _fees with _consular_fees_table
4987361 Replace _fees_table_ss_marriage_and_partnership with _consular_fees_table
add3fed Replace fees in outcome_ss_marriage with _consular_fees_table
d22aba7 Replace fees in outcome_ss_marriage with _consular_fees_table
6835a5b Replace fees in outcome_cp_consular with _consular_fees_table
26de31f Replace fees in outcome_cp_or_equivalent with _consular_fees_table
4c8070d Replace fees in outcome_os_belarus with _consular_fees_table
a7fb2f3 Replace fees in outcome_os_italy with _consular_fees_table
2967e88 Replace fees in outcome_os_other_countries with _consular_fees_table
0fd638b Replace fees in outcome_os_consular_cni with _consular_fees_table
f1a2e79 Replace fees in outcome_os_kosovo with _consular_fees_table
0b12c25 Regenerate test artefacts for marriage abroad
14153b8 Regenerate file checksums for marriage abroad

**Comment by erikse** [comment]
To keep things at 50 characters or less, I've been writing pretty generic commit titles, usually mentioning the smart answer effected by the change (if it is specific). But those titles look a bit more useful, are we all okay to start going over the 50 character restriction @floehopper @ikennaokpala @pmanrubia ?

**Comment by pmanrubia** [comment]
@erikse If you all agree, I am good with going over 50 characters as long as the commit messages are not truncated in Github (I guess the limit is 72 characters in GH?)

**Comment by erikse** [comment]
It seems like the [GDS Styleguide for commit messages](https://github.com/alphagov/styleguides/blob/master/git.md#structure) still restricts us to 50 characters:

> Commit messages should start with a one-line summary no longer than 50 characters. Various Git tools (including GitHub) use this as the commit summary, so you should format it like an email subject, with a leading capital and no full stop.

**Comment by floehopper** [comment]
I've always treated the 50 character limit as a guideline, not a hard-and-fast rule i.e. I try really hard to come up with a 50-char summary line, but if I can't then I don't mind going slightly over.

For me the key thing is knowing the reason behind the limit i.e. that some git clients will not display more than 50 chars of the summary line. If I go over the limit, I try to keep the most important part at the beginning.

My preference would be to keep the 50-character limit, but accept that it's a guideline. I would prefer this to just increasing the limit in order to have it as a hard-and-fast rule. Especially if the new limit is just based on GitHub's current UI.

**Comment by erikse** [comment]
I'm finding when we have longer variable or file names, it's almost impossible to write a commit message that shows the precise context, so that's when I've been falling back tagging them with a wider scope of identifying the smart answer the change belongs to. 

What tools in particular restrict you to 50 characters? Maybe it's worth considering if there are alternatives/newer versions that would allow a longer title, 50 characters seems given the practice of having long class/method/file names in Ruby

**Comment by pmanrubia** [comment]
In refactorings, for example, the smaller the commits, the more difficult it is to write 50 characters messages without commit duplications across the PR, so I like the idea of relaxing the constraint of 50 characters but trying to stick to it. A balanced solution for me.

**Comment by erikse** [comment]
I've amended the commit titles to try and give a bit more context to the change, and rebased with master.

**Pull request merged**
