### PR TITLE
Retire student finance forms

### PR DESCRIPTION
**Pull request by mgrassotti**
Trello: https://trello.com/c/EnvfuMBh/754-3-retire-student-finance-forms-ie-firebreak-task
Retire **Student Finance Forms** Smart Answer and change its format to a _Simple Smart Answer_.

After deleting its files from smart-answers ([guide](https://github.com/alphagov/smart-answers/blob/master/doc/retiring-a-smart-answer.md)), the following steps have to be followed to apply the changes to the other applications and on **staging/production environments**:

**Retire the smart-answer via rake task**
- go to Jenkins: https://deploy.integration.publishing.service.gov.uk/job/run-rake-task/build?delay=0sec
- set & run:
  ``` 
  TARGET_APPLICATION = smartanswers
  MACHINE_CLASS = calculators_frontend
  RAKE_TASK = <rake task name only (no bundle exec rake) …. > 
  ```
  ```
  (bundle exec rake) retire:unpublish[67764435-e8ed-4700-a657-2e0432cb1f5b]
  (bundle exec rake) retire:change_owning_application[/student-finance-forms,publisher]
  ```
Verify success on Publishing API with:
  - SSH to backend: ```ssh publishing-api-1.backend.(integration|staging|production)```
  - rails console: ```govuk_app_console publishing-api```
  - check publishing_app: "publisher" (no more smart-answers) with `PathReservation.find_by(base_path: '/student-finance-forms')`

**Publish the simple smart answer document with the format manually**
  - Manually archive existing Artefact on publisher storage.
    - SSH to backend: ```ssh backend-1.backend.(integration|staging|production)```
    - rails console: ```govuk_app_console publisher```
    ``` 
    artefact = Artefact.find_by(slug: "student-finance-forms")
    artefact.state = "archived"
    artefact.save!
    artefact.slug = "archived-student-finance-forms"
    artefact.save!
    ```
  - Publish new simple smart answer for student-finance-forms from publisher
  - Update the retirement log ([link](https://github.com/alphagov/smart-answers/blob/master/doc/retirement-log.md))

** Remove the existing backend route
  - SSH to router backend ```ssh publishing-api-1.backend.(integration|staging|production)```
  - Rails console ```govuk_app_console router-api```
  - Delete the route
    ```
    route = Route.find_by(incoming_path: "/student-finance-forms/y")
    route.soft_delete
    RouterReloader.reload
    ```

This was successfully tested on integration.

### CODE REVIEW

**Comment by alecgibson** [comment]
@mgrassotti shouldn't we be deleting these files *after* retiring the base path? In which case, you may want a `[DO NOT MERGE]` on this pull request.

Also, I assume with this approach we get some downtime when visiting the retired base path, as we're switching over. Is that acceptable?

**Comment by mgrassotti** [comment]
@alecgibson 
1) yes I agree
2) I will check with Katherine, although I am not sure we can't avoid a downtime. If we ask them to already publish the simple smart answer on publisher and then change its URL right after switching, we should save some time. What do you think?

**Comment by mgrassotti** [comment]
@chao-xian it currently has a dummy base path, different from the final one

**Comment by alecgibson** [comment]
@mgrassotti yes it may well be impossible with our setup to get zero downtime; we should just make sure that the appropriate people are aware, and check if we need to communicate this in any particular way?

**Pull request merged**
