### PR TITLE
Link 'Trade Tariff' to its website

### PR DESCRIPTION
**Pull request by selfthinker**
[Trello card](https://trello.com/c/nKOf2cwy)

## Description

This implements the suggested change in #2492, i.e. it links the words 'Trade Tariff' in the `additional-commodity-code` outcome to its respective website (https://www.gov.uk/trade-tariff).

The question artefacts correctly only contain that copy change.

## Fact check

* [Preview of changed example outcome](https://smart-answers-pr-2687.herokuapp.com/additional-commodity-code/y/5/70/0/6)
* [Example outcome on production](https://www.gov.uk/additional-commodity-code/y/5/70/0/6)

## Expected changes

E.g. `/additional-commodity-code/y/5/70/0/6` includes the link. This affects any additional-commodity-code outcome if there is a commodity code.

screen shot 2016-08-12 at 14 18 04

### CODE REVIEW

**Comment by pmanrubia** [comment]
Thank you for your work on it. 

3 minor things:

1. We would need to fact-check this change with the department, so we need to create a Heroku app as described in this [document][1]. 
2. Could you please update the description following a similar structure than https://github.com/alphagov/smart-answers/pull/2653, or https://github.com/alphagov/smart-answers/pull/2688. All our PRs for smart-answers follow a similar approach. It simplifies our deployment process.

I have just checked that Github is struggling to show the commit because we have too many artefacts. In general, it is better to follow the approach you have chosen for this PR because we have atomic PRs, but in this situations we sometimes split the commit into: a) commit with the changes, b) commit with artefacts. 

I am not suggesting to do it for this PR; it is absolutely fine what you have done it.

[1]: https://github.com/alphagov/smart-answers/blob/master/doc/factcheck.md

**Comment by selfthinker** [comment]
@pmanrubia, done both. Is the description okay this way?

**Comment by pmanrubia** [comment]
LGTM 👍

**Comment by pmanrubia** [comment]
@selfthinker I last thing..., could you please add a note to the card so we close the issue once it is deployed

**Comment by selfthinker** [comment]
The issue will automatically be closed by GitHub when this is merged into master (because I added `closes #2492` to the commit message). But we should update the ticket manually anyway as it is more polite.

**Pull request merged**
