### PR TITLE
Spike: Fail fast on missing methods in SmartAnswer::State object

### PR DESCRIPTION
**Pull request by chrisroos**
__This has been superseded by PR #2099__

This is for discussion only and currently contains 4 failing tests that I've not investigated fully.

The `SmartAnswer::State` object is an `OpenStruct` which means that it responds to undefined methods with `nil`. This can lead to hard to find bugs in `next_node` blocks (particularly larger ones, e.g. [this one in pay-leave-for-parents](https://github.com/alphagov/smart-answers/blob/master/lib/smart_answer_flows/pay-leave-for-parents.rb#L385)) as a simple typo will mean that the program runs but doesn't return the desired result.

The main change in this PR overrides `SmartAnswer::State#method_missing` so that it raises a `NoMethodError` exception if we try to call a method that's not previously been defined.

```
# Behaviour before this change
>> state = SmartAnswer::State.new(start_node = nil)
>> state.foo
=> nil
>> state.foo = 'bar'
>> state.foo
=> 'bar'

# Behaviour after this change
>> state = SmartAnswer::State.new(start_node = nil)
>> state.foo
=> NoMethodError: undefined method 'foo' for SmartAnswer::State
>> state.foo = 'bar'
>> state.foo
=> 'bar'
```

I've also updated all Smart Answer flows where the code was relying on the old behaviour of the `State` object, by explicitly setting the variables to nil that are used later in the flow.

I'm not 100% convinced about this but would like to hear what other people think.

### CODE REVIEW

**Comment by floehopper** [comment]
I think this is a worthwhile change. It's not ideal that we have to introduce so many missing variables, but then that's kind of the point! Is that what you are unconvinced about?

It would be good to implement `respond_to?` or `respond_to_missing?` to match `method_missing`.

Ideally, I think each flow would automatically instantiate a flow-specific "model" class with the relevant methods defined on it. Then we'd get this kind of behaviour for free. But I think this is a good first step.

**Comment by chrisroos** [comment]
> It would be good to implement respond_to? or respond_to_missing? to match method_missing.

Do you think this is necessary given that we've not had it before now?

Interestingly, it would appear that `OpenStruct` doesn't define `respond_to?` or `respond_to_missing?` (this is against the `State` object before making the changes in this branch):

```
>> state = SmartAnswer::State.new(:start_node)
=> #<SmartAnswer::State current_node=:start_node, path=[], responses=[]>
>> state.respond_to?(:foo)
=> false
>> state.respond_to?(:foo=)
=> false
>> state.foo = 'bob'
=> "bob"
>> state.respond_to?(:foo)
=> true
>> state.respond_to?(:foo=)
=> true
```

**Comment by chrisroos** [comment]
I've rebased this on master, fixed the failing tests and force-pushed.

I've also moved the commit that overrides `State#method_missing` to the end, so that the tests should be passing for each commit in the branch.

**Comment by chrisroos** [comment]
@floehopper: Are you still happy for us to make this change?

**Comment by floehopper** [comment]
I guess it's not critical to define `respond_to?` - I tend to try to always do it whenever I define `method_missing`. However, I can see here that `OpenStruct` is already behaving weirdly.

I'm still happy for this change to be merged.

LGTM :+1:

**Comment by chrisroos** [comment]
I've tidied this branch up and opened a new pull request (PR #2099). I'm closing this and will merge from the new PR.

**Pull request closed without merging**
